package  
{
	import flash.display.Sprite;
	
	/**
	 * ...
	 * @author Vladimir
	 */
	public class PageLesson_1 extends Sprite
	{
		private var stateManager:StateManager;
		private var list:Vector.<Question> = new Vector.<Question>(); // список вопросов
		
		public function PageLesson_1(manager:StateManager) 
		{
			stateManager = manager;
			
			Add_1();
			Add_2();
			Add_3();
			Add_4();
			Add_5();
			Add_6();
			Add_7();
			Add_8();
			Add_9();
			Add_10();
			Add_11();
			Add_12();
			Add_13();
			Add_14();
			Add_15();
			Add_16();
			Add_17();
			Add_18();
			Add_19();
			
			
			var a:Lesson = new Lesson(list, stateManager, 1);
			addChild(a);
			a.x = 40;
			a.y = 25;
			
			// добавляем к уроку конспект
			var wb:WorkBook = new WorkBook(new wb_1());
			a.AddWorkBook(wb);
			
			// добавляем к уроку словарь
			var dic:WorkBook = new WorkBook(new dic_1());
			a.AddDictionary(dic);
		}
		
		// feed
		private function Add_19():void
		{
			var arr:Array = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "feed";
			arr[4] = "drank";
			arr[5] = "do";
			arr[6] = "fed";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "feeds";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Ты покормишь?", "Will you feed", arr, "sound_1_1"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "feed";
			arr[4] = "drank";
			arr[5] = "do";
			arr[6] = "fed";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "feeds";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Мы покормим.", "We will feed", arr, "sound_1_2"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "feed";
			arr[4] = "drank";
			arr[5] = "do";
			arr[6] = "fed";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "feeds";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Она не покормит.", "She will not feed", arr, "sound_1_3"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "feed";
			arr[4] = "drank";
			arr[5] = "do";
			arr[6] = "fed";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "feeds";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Они кормят?", "Do they feed", arr, "sound_1_4"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "feed";
			arr[4] = "drank";
			arr[5] = "do";
			arr[6] = "fed";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "feeds";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Он кормит?", "Does he feed", arr, "sound_1_5"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "feed";
			arr[4] = "drank";
			arr[5] = "do";
			arr[6] = "fed";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "feeds";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Я кормлю.", "I feed", arr, "sound_1_6"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "feed";
			arr[4] = "drank";
			arr[5] = "do";
			arr[6] = "fed";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "feeds";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Она кормит.", "She feeds", arr, "sound_1_7"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "feed";
			arr[4] = "drank";
			arr[5] = "do";
			arr[6] = "fed";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "feeds";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Ты не кормишь.", "You do not feed", arr, "sound_1_8"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "feed";
			arr[4] = "drank";
			arr[5] = "do";
			arr[6] = "fed";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "feeds";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Он не кормит.", "He does not feed", arr, "sound_1_9"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "feed";
			arr[4] = "drank";
			arr[5] = "do";
			arr[6] = "fed";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "feeds";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Ты кормил?", "Did you feed", arr, "sound_1_10"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "feed";
			arr[4] = "drank";
			arr[5] = "do";
			arr[6] = "fed";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "feeds";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Он кормил.", "He fed", arr, "sound_1_11"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "feed";
			arr[4] = "drank";
			arr[5] = "do";
			arr[6] = "fed";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "feeds";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Они не кормили.", "They did not feed", arr, "sound_1_12"));
		}
		
		// drink
		private function Add_18():void
		{
			var arr:Array = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "drink";
			arr[4] = "drank";
			arr[5] = "do";
			arr[6] = "dream";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "drinks";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Она выпьет?", "Will she drink", arr, "sound_1_13"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "drink";
			arr[4] = "drank";
			arr[5] = "do";
			arr[6] = "dream";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "drinks";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Я выпью.", "I will drink", arr, "sound_1_14"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "drink";
			arr[4] = "drank";
			arr[5] = "do";
			arr[6] = "dream";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "drinks";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Они не выпьют.", "They will not drink", arr, "sound_1_15"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "drink";
			arr[4] = "drank";
			arr[5] = "do";
			arr[6] = "dream";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "drinks";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Ты пьешь?", "Do you drink", arr, "sound_1_16"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "drink";
			arr[4] = "drank";
			arr[5] = "do";
			arr[6] = "dream";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "drinks";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Он пьет?", "Does he drink", arr, "sound_1_17"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "drink";
			arr[4] = "drank";
			arr[5] = "do";
			arr[6] = "dream";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "drinks";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Я пью.", "I drink", arr, "sound_1_18"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "drink";
			arr[4] = "drank";
			arr[5] = "do";
			arr[6] = "dream";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "drinks";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Она пьет.", "She drinks", arr, "sound_1_19"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "drink";
			arr[4] = "drank";
			arr[5] = "do";
			arr[6] = "dream";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "drinks";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Я не пью.", "I do not drink", arr, "sound_1_20"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "drink";
			arr[4] = "drank";
			arr[5] = "do";
			arr[6] = "dream";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "drinks";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Он не пьет.", "He does not drink", arr, "sound_1_21"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "drink";
			arr[4] = "drank";
			arr[5] = "do";
			arr[6] = "dream";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "drinks";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Мы пили?", "Did we drink", arr, "sound_1_22"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "drink";
			arr[4] = "drank";
			arr[5] = "do";
			arr[6] = "dream";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "drinks";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Мы пили.", "We drank", arr, "sound_1_23"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "drink";
			arr[4] = "drank";
			arr[5] = "do";
			arr[6] = "dream";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "drinks";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Ты не пил.", "You did not drink", arr, "sound_1_24"));
		}
		
		// fall
		private function Add_17():void
		{
			var arr:Array = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "falls";
			arr[4] = "fall";
			arr[5] = "do";
			arr[6] = "dream";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "fell";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Я упаду?", "Will I fall", arr, "sound_1_25"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "falls";
			arr[4] = "fall";
			arr[5] = "do";
			arr[6] = "dream";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "fell";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Ты упадешь.", "You will fall", arr, "sound_1_26"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "falls";
			arr[4] = "fall";
			arr[5] = "do";
			arr[6] = "dream";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "fell";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Мы не упадем.", "We will not fall", arr, "sound_1_27"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "falls";
			arr[4] = "fall";
			arr[5] = "do";
			arr[6] = "dream";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "fell";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Ты падаешь?", "Do you fall", arr, "sound_1_28"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "falls";
			arr[4] = "fall";
			arr[5] = "do";
			arr[6] = "dream";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "fell";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Она падает?", "Does she fall", arr, "sound_1_29"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "falls";
			arr[4] = "fall";
			arr[5] = "do";
			arr[6] = "dream";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "fell";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Я падаю.", "I fall", arr, "sound_1_30"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "falls";
			arr[4] = "fall";
			arr[5] = "do";
			arr[6] = "dream";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "fell";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Он падает.", "He falls", arr, "sound_1_31"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "falls";
			arr[4] = "fall";
			arr[5] = "do";
			arr[6] = "dream";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "fell";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Они не падают.", "They do not fall", arr, "sound_1_32"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "falls";
			arr[4] = "fall";
			arr[5] = "do";
			arr[6] = "dream";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "fell";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Она не падает.", "She does not fall", arr, "sound_1_33"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "falls";
			arr[4] = "fall";
			arr[5] = "do";
			arr[6] = "dream";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "fell";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Ты упал?", "Did you fall", arr, "sound_1_34"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "falls";
			arr[4] = "fall";
			arr[5] = "do";
			arr[6] = "dream";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "fell";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Она упала.", "She fell", arr, "sound_1_35"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "falls";
			arr[4] = "fall";
			arr[5] = "do";
			arr[6] = "dream";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "fell";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Мы не упали.", "We did not fall", arr, "sound_1_36"));
		}
		
		// dream
		private function Add_16():void
		{
			var arr:Array = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "crept";
			arr[4] = "dreams";
			arr[5] = "do";
			arr[6] = "dream";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "dreamt";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Ты будешь мечтать?", "Will you dream", arr, "sound_1_37"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "crept";
			arr[4] = "dreams";
			arr[5] = "do";
			arr[6] = "dream";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "dreamt";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Я буду мечтать.", "I will dream", arr, "sound_1_38"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "crept";
			arr[4] = "dreams";
			arr[5] = "do";
			arr[6] = "dream";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "dreamt";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Он не будет мечтать.", "He will not dream", arr, "sound_1_39"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "crept";
			arr[4] = "dreams";
			arr[5] = "do";
			arr[6] = "dream";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "dreamt";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Ты мечтаешь?", "Do you dream", arr, "sound_1_40"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "crept";
			arr[4] = "dreams";
			arr[5] = "do";
			arr[6] = "dream";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "dreamt";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Она мечтает?", "Does she dream", arr, "sound_1_41"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "crept";
			arr[4] = "dreams";
			arr[5] = "do";
			arr[6] = "dream";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "dreamt";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Мы мечтаем.", "We dream", arr, "sound_1_42"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "crept";
			arr[4] = "dreams";
			arr[5] = "do";
			arr[6] = "dream";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "dreamt";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Он мечтает.", "He dreams", arr, "sound_1_43"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "crept";
			arr[4] = "dreams";
			arr[5] = "do";
			arr[6] = "dream";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "dreamt";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Они не мечтают.", "They do not dream", arr, "sound_1_44"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "crept";
			arr[4] = "dreams";
			arr[5] = "do";
			arr[6] = "dream";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "dreamt";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Она не мечтает.", "She does not dream", arr, "sound_1_45"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "crept";
			arr[4] = "dreams";
			arr[5] = "do";
			arr[6] = "dream";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "dreamt";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Ты мечтал?", "Did you dream", arr, "sound_1_46"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "crept";
			arr[4] = "dreams";
			arr[5] = "do";
			arr[6] = "dream";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "dreamt";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Она мечтала.", "She dreamt", arr, "sound_1_47"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "crept";
			arr[4] = "dreams";
			arr[5] = "do";
			arr[6] = "dream";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "dreamt";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Они не мечтали.", "They did not dream", arr, "sound_1_48"));
		}
		
		// creep
		private function Add_15():void
		{
			var arr:Array = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "crept";
			arr[4] = "creeps";
			arr[5] = "do";
			arr[6] = "bless";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "creep";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Они приползут?", "Will they creep", arr, "sound_1_49"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "crept";
			arr[4] = "creeps";
			arr[5] = "do";
			arr[6] = "bless";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "creep";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Я приползу.", "I will creep", arr, "sound_1_50"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "crept";
			arr[4] = "creeps";
			arr[5] = "do";
			arr[6] = "bless";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "creep";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Мы не приползем.", "We will not creep", arr, "sound_1_51"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "crept";
			arr[4] = "creeps";
			arr[5] = "do";
			arr[6] = "bless";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "creep";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Ты ползешь?", "Do you creep", arr, "sound_1_52"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "crept";
			arr[4] = "creeps";
			arr[5] = "do";
			arr[6] = "bless";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "creep";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Он ползет?", "Does he creep", arr, "sound_1_53"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "crept";
			arr[4] = "creeps";
			arr[5] = "do";
			arr[6] = "bless";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "creep";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Я ползу.", "I creep", arr, "sound_1_54"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "crept";
			arr[4] = "creeps";
			arr[5] = "do";
			arr[6] = "bless";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "creep";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Она ползет.", "She creeps", arr, "sound_1_55"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "crept";
			arr[4] = "creeps";
			arr[5] = "do";
			arr[6] = "bless";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "creep";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Ты не ползешь.", "You do not creep", arr, "sound_1_56"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "crept";
			arr[4] = "creeps";
			arr[5] = "do";
			arr[6] = "bless";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "creep";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Он не ползет.", "He does not creep", arr, "sound_1_57"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "crept";
			arr[4] = "creeps";
			arr[5] = "do";
			arr[6] = "bless";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "creep";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Ты полз?", "Did you creep", arr, "sound_1_58"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "crept";
			arr[4] = "creeps";
			arr[5] = "do";
			arr[6] = "bless";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "creep";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Мы ползли.", "We crept", arr, "sound_1_59"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "crept";
			arr[4] = "creeps";
			arr[5] = "do";
			arr[6] = "bless";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "creep";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Они не ползли.", "They did not creep", arr, "sound_1_60"));
		}
		
		// bless
		private function Add_14():void
		{
			var arr:Array = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "blessed";
			arr[4] = "thinks";
			arr[5] = "do";
			arr[6] = "bless";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "blesses";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Ты благословишь?", "Will you bless", arr, "sound_1_61"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "blessed";
			arr[4] = "thinks";
			arr[5] = "do";
			arr[6] = "bless";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "blesses";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Я благословлю.", "I will bless", arr, "sound_1_62"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "blessed";
			arr[4] = "thinks";
			arr[5] = "do";
			arr[6] = "bless";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "blesses";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Он не благословит.", "He will not bless", arr, "sound_1_63"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "blessed";
			arr[4] = "thinks";
			arr[5] = "do";
			arr[6] = "bless";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "blesses";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Ты благословляешь?", "Do you bless", arr, "sound_1_64"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "blessed";
			arr[4] = "thinks";
			arr[5] = "do";
			arr[6] = "bless";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "blesses";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Он благословляет?", "Does he bless", arr, "sound_1_65"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "blessed";
			arr[4] = "thinks";
			arr[5] = "do";
			arr[6] = "bless";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "blesses";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Они благославляют.", "They bless", arr, "sound_1_66"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "blessed";
			arr[4] = "thinks";
			arr[5] = "do";
			arr[6] = "bless";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "blesses";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Она благословляет.", "She blesses", arr, "sound_1_67"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "blessed";
			arr[4] = "thinks";
			arr[5] = "do";
			arr[6] = "bless";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "blesses";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Я не благословляю.", "I do not bless", arr, "sound_1_68"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "blessed";
			arr[4] = "thinks";
			arr[5] = "do";
			arr[6] = "bless";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "blesses";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Он не благословляет.", "He does not bless", arr, "sound_1_69"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "blessed";
			arr[4] = "thinks";
			arr[5] = "do";
			arr[6] = "bless";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "blesses";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Они благословили?", "Did they bless", arr, "sound_1_70"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "blessed";
			arr[4] = "thinks";
			arr[5] = "do";
			arr[6] = "bless";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "blesses";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Я благословил.", "I blessed", arr, "sound_1_71"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "blessed";
			arr[4] = "thinks";
			arr[5] = "do";
			arr[6] = "bless";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "blesses";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Ты не благословил.", "You did not bless", arr, "sound_1_72"));
		}
		
		// bind
		private function Add_13():void
		{
			var arr:Array = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "come";
			arr[4] = "thinks";
			arr[5] = "do";
			arr[6] = "bound";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "binds";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Они свяжу?", "Will they bind", arr, "sound_1_73"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "come";
			arr[4] = "thinks";
			arr[5] = "do";
			arr[6] = "bound";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "binds";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Он свяжет.", "He will bind", arr, "sound_1_74"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "come";
			arr[4] = "thinks";
			arr[5] = "do";
			arr[6] = "bound";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "binds";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Она не свяжет.", "She will not bind", arr, "sound_1_75"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "come";
			arr[4] = "thinks";
			arr[5] = "do";
			arr[6] = "bound";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "binds";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Ты связываешь?", "Do you bind", arr, "sound_1_76"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "come";
			arr[4] = "thinks";
			arr[5] = "do";
			arr[6] = "bound";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "binds";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Она связывает?", "Does she bind", arr, "sound_1_77"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "come";
			arr[4] = "thinks";
			arr[5] = "do";
			arr[6] = "bound";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "binds";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Я связываю.", "I bind", arr, "sound_1_78"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "come";
			arr[4] = "thinks";
			arr[5] = "do";
			arr[6] = "bound";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "binds";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Он связывает.", "He binds", arr, "sound_1_79"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "come";
			arr[4] = "thinks";
			arr[5] = "do";
			arr[6] = "bound";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "binds";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Я не связываю.", "I do not bind", arr, "sound_1_80"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "come";
			arr[4] = "thinks";
			arr[5] = "do";
			arr[6] = "bound";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "binds";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Он не связывает.", "He does not bind", arr, "sound_1_81"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "come";
			arr[4] = "thinks";
			arr[5] = "do";
			arr[6] = "bound";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "binds";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Ты связал?", "Did you bind", arr, "sound_1_82"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "come";
			arr[4] = "thinks";
			arr[5] = "do";
			arr[6] = "bound";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "binds";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Мы связали.", "We bound", arr, "sound_1_83"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "come";
			arr[4] = "thinks";
			arr[5] = "do";
			arr[6] = "bound";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "binds";
			arr[13] = "she";
			arr[14] = "bind";
			arr[15] = "they";
			list.push(new Question("Он не связал.", "He did not bind", arr, "sound_1_84"));
		}
		
		// think
		private function Add_12():void
		{
			var arr:Array = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "come";
			arr[4] = "thinks";
			arr[5] = "do";
			arr[6] = "thought";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "think";
			arr[13] = "she";
			arr[14] = "listen";
			arr[15] = "reads";
			list.push(new Question("Он подумает?", "Will he think", arr, "sound_1_85"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "come";
			arr[4] = "thinks";
			arr[5] = "listens";
			arr[6] = "thought";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "read";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "think";
			arr[13] = "she";
			arr[14] = "listen";
			arr[15] = "they";
			list.push(new Question("Они подумают.", "They will think", arr, "sound_1_86"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "do";
			arr[4] = "thinks";
			arr[5] = "listens";
			arr[6] = "thought";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "read";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "think";
			arr[13] = "she";
			arr[14] = "listen";
			arr[15] = "they";
			list.push(new Question("Они не будут думать.", "They will not think", arr, "sound_1_87"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "come";
			arr[4] = "thinks";
			arr[5] = "do";
			arr[6] = "thought";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "read";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "think";
			arr[13] = "she";
			arr[14] = "listen";
			arr[15] = "they";
			list.push(new Question("Ты думаешь?", "Do you think", arr, "sound_1_88"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "come";
			arr[4] = "thinks";
			arr[5] = "do";
			arr[6] = "thought";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "think";
			arr[13] = "she";
			arr[14] = "listen";
			arr[15] = "they";
			list.push(new Question("Он думает?", "Does he think", arr, "sound_1_89"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "come";
			arr[4] = "thinks";
			arr[5] = "listens";
			arr[6] = "thought";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "read";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "think";
			arr[13] = "she";
			arr[14] = "listen";
			arr[15] = "they";
			list.push(new Question("Я думаю.", "I think", arr, "sound_1_90"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "come";
			arr[4] = "thinks";
			arr[5] = "listens";
			arr[6] = "thought";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "do";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "think";
			arr[13] = "she";
			arr[14] = "listen";
			arr[15] = "they";
			list.push(new Question("Она думает.", "She thinks", arr, "sound_1_91"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "do";
			arr[4] = "thinks";
			arr[5] = "listens";
			arr[6] = "thought";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "read";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "think";
			arr[13] = "she";
			arr[14] = "listen";
			arr[15] = "they";
			list.push(new Question("Они не думают.", "They do not think", arr, "sound_1_92"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "do";
			arr[4] = "thinks";
			arr[5] = "listens";
			arr[6] = "thought";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "read";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "think";
			arr[13] = "she";
			arr[14] = "does";
			arr[15] = "they";
			list.push(new Question("Она не думает.", "She does not think", arr, "sound_1_93"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "do";
			arr[4] = "thinks";
			arr[5] = "listens";
			arr[6] = "thought";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "read";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "think";
			arr[13] = "she";
			arr[14] = "does";
			arr[15] = "they";
			list.push(new Question("Он думал?", "Did he think", arr, "sound_1_94"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "do";
			arr[4] = "thinks";
			arr[5] = "listens";
			arr[6] = "thought";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "read";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "think";
			arr[13] = "she";
			arr[14] = "does";
			arr[15] = "they";
			list.push(new Question("Мы думали.", "We thought", arr, "sound_1_95"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "do";
			arr[4] = "thinks";
			arr[5] = "listens";
			arr[6] = "thought";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "read";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "think";
			arr[13] = "she";
			arr[14] = "does";
			arr[15] = "they";
			list.push(new Question("Они не думали.", "They did not think", arr, "sound_1_96"));
		}
		
		// listen
		private function Add_11():void
		{
			var arr:Array = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "come";
			arr[4] = "came";
			arr[5] = "listens";
			arr[6] = "build";
			arr[7] = "go";
			arr[8] = "you";
			arr[9] = "read";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "listened";
			arr[13] = "broke";
			arr[14] = "listen";
			arr[15] = "reads";
			list.push(new Question("Ты будешь слушать?", "Will you listen", arr, "sound_1_97"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "come";
			arr[4] = "came";
			arr[5] = "listens";
			arr[6] = "build";
			arr[7] = "go";
			arr[8] = "you";
			arr[9] = "read";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "listened";
			arr[13] = "she";
			arr[14] = "listen";
			arr[15] = "reads";
			list.push(new Question("Она будет слушать.", "She will listen", arr, "sound_1_98"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "come";
			arr[4] = "came";
			arr[5] = "listens";
			arr[6] = "build";
			arr[7] = "go";
			arr[8] = "you";
			arr[9] = "read";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "listened";
			arr[13] = "she";
			arr[14] = "listen";
			arr[15] = "they";
			list.push(new Question("Они не будут слушать.", "They will not listen", arr, "sound_1_99"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "come";
			arr[4] = "does";
			arr[5] = "listens";
			arr[6] = "build";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "read";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "listened";
			arr[13] = "she";
			arr[14] = "listen";
			arr[15] = "they";
			list.push(new Question("Ты слушаешь?", "Do you listen", arr, "sound_1_100"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "come";
			arr[4] = "does";
			arr[5] = "listens";
			arr[6] = "build";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "read";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "listened";
			arr[13] = "she";
			arr[14] = "listen";
			arr[15] = "they";
			list.push(new Question("Она слушает?", "Does she listen", arr, "sound_1_101"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "come";
			arr[4] = "does";
			arr[5] = "listens";
			arr[6] = "build";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "read";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "listened";
			arr[13] = "she";
			arr[14] = "listen";
			arr[15] = "they";
			list.push(new Question("Я слушаю.", "I listen", arr, "sound_1_102"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "he";
			arr[4] = "does";
			arr[5] = "listens";
			arr[6] = "build";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "read";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "listened";
			arr[13] = "she";
			arr[14] = "listen";
			arr[15] = "they";
			list.push(new Question("Он слушает.", "He listens", arr, "sound_1_103"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "he";
			arr[4] = "does";
			arr[5] = "listens";
			arr[6] = "build";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "we";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "listened";
			arr[13] = "she";
			arr[14] = "listen";
			arr[15] = "they";
			list.push(new Question("Мы не слушаем.", "We do not listen", arr, "sound_1_104"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "he";
			arr[4] = "does";
			arr[5] = "listens";
			arr[6] = "build";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "we";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "listened";
			arr[13] = "she";
			arr[14] = "listen";
			arr[15] = "they";
			list.push(new Question("Она не слушает.", "She does not listen", arr, "sound_1_105"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "he";
			arr[4] = "does";
			arr[5] = "listens";
			arr[6] = "build";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "we";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "listened";
			arr[13] = "she";
			arr[14] = "listen";
			arr[15] = "they";
			list.push(new Question("Они слушали?", "Did they listen", arr, "sound_1_106"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "he";
			arr[4] = "does";
			arr[5] = "listens";
			arr[6] = "build";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "we";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "listened";
			arr[13] = "she";
			arr[14] = "listen";
			arr[15] = "they";
			list.push(new Question("Мы слушали.", "We listened", arr, "sound_1_107"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "he";
			arr[4] = "does";
			arr[5] = "listens";
			arr[6] = "build";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "we";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "listened";
			arr[13] = "she";
			arr[14] = "listen";
			arr[15] = "they";
			list.push(new Question("Ты не слушал.", "You did not listen", arr, "sound_1_108"));
		}
		
		// read
		private function Add_10():void
		{
			var arr:Array = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "come";
			arr[4] = "came";
			arr[5] = "swear";
			arr[6] = "build";
			arr[7] = "go";
			arr[8] = "you";
			arr[9] = "read";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "hello";
			arr[13] = "broke";
			arr[14] = "listen";
			arr[15] = "reads";
			list.push(new Question("Ты прочитаешь?", "Will you read", arr, "sound_1_109"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "come";
			arr[4] = "came";
			arr[5] = "swear";
			arr[6] = "build";
			arr[7] = "go";
			arr[8] = "you";
			arr[9] = "read";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "hello";
			arr[13] = "broke";
			arr[14] = "reads";
			arr[15] = "break";
			list.push(new Question("Я прочитаю.", "I will read", arr, "sound_1_110"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "come";
			arr[4] = "came";
			arr[5] = "swear";
			arr[6] = "build";
			arr[7] = "go";
			arr[8] = "you";
			arr[9] = "read";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "do";
			arr[13] = "reads";
			arr[14] = "they";
			arr[15] = "break";
			list.push(new Question("Они не прочитают.", "They will not read", arr, "sound_1_111"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "come";
			arr[4] = "came";
			arr[5] = "swear";
			arr[6] = "reads";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "read";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "hello";
			arr[13] = "broke";
			arr[14] = "they";
			arr[15] = "does";
			list.push(new Question("Ты читаешь?", "Do you read", arr, "sound_1_112"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "come";
			arr[4] = "came";
			arr[5] = "she";
			arr[6] = "reads";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "read";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "hello";
			arr[13] = "does";
			arr[14] = "they";
			arr[15] = "break";
			list.push(new Question("Она читает?", "Does she read", arr, "sound_1_113"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "come";
			arr[4] = "we";
			arr[5] = "swear";
			arr[6] = "reads";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "read";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "hello";
			arr[13] = "does";
			arr[14] = "they";
			arr[15] = "break";
			list.push(new Question("Мы читаем.", "We read", arr, "sound_1_114"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "come";
			arr[4] = "we";
			arr[5] = "swear";
			arr[6] = "build";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "read";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "he";
			arr[13] = "does";
			arr[14] = "they";
			arr[15] = "reads";
			list.push(new Question("Он читает.", "He reads", arr, "sound_1_115"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "come";
			arr[4] = "we";
			arr[5] = "swear";
			arr[6] = "build";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "read";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "he";
			arr[13] = "does";
			arr[14] = "they";
			arr[15] = "reads";
			list.push(new Question("Они не читают.", "They do not read", arr, "sound_1_116"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "come";
			arr[4] = "we";
			arr[5] = "swear";
			arr[6] = "she";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "read";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "he";
			arr[13] = "does";
			arr[14] = "they";
			arr[15] = "reads";
			list.push(new Question("Она не читает.", "She does not read", arr, "sound_1_117"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "come";
			arr[4] = "we";
			arr[5] = "swear";
			arr[6] = "she";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "read";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "he";
			arr[13] = "does";
			arr[14] = "they";
			arr[15] = "reads";
			list.push(new Question("Ты читал?", "Did you read", arr, "sound_1_118"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "come";
			arr[4] = "we";
			arr[5] = "swear";
			arr[6] = "she";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "read";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "he";
			arr[13] = "does";
			arr[14] = "they";
			arr[15] = "reads";
			list.push(new Question("Я читал.", "I read", arr, "sound_1_119"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "come";
			arr[4] = "we";
			arr[5] = "swear";
			arr[6] = "she";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "read";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "he";
			arr[13] = "does";
			arr[14] = "they";
			arr[15] = "reads";
			list.push(new Question("Ты не читал.", "You did not read", arr, "sound_1_120"));
		}
		
		// draw
		private function Add_9():void
		{
			var arr:Array = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "why";
			arr[4] = "she";
			arr[5] = "draw";
			arr[6] = "drew";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "draws";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "does";
			arr[14] = "he";
			arr[15] = "they";
			list.push(new Question("Она нарисует?", "Will she draw", arr, "sound_1_121"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "why";
			arr[4] = "she";
			arr[5] = "draw";
			arr[6] = "drew";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "draws";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "does";
			arr[14] = "he";
			arr[15] = "they";
			list.push(new Question("Мы нарисуем.", "We will draw", arr, "sound_1_122"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "why";
			arr[4] = "she";
			arr[5] = "draw";
			arr[6] = "drew";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "draws";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "does";
			arr[14] = "he";
			arr[15] = "they";
			list.push(new Question("Я не буду рисовать.", "I will not draw", arr, "sound_1_123"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "why";
			arr[4] = "she";
			arr[5] = "draw";
			arr[6] = "drew";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "draws";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "does";
			arr[14] = "he";
			arr[15] = "they";
			list.push(new Question("Ты рисуешь?", "Do you draw", arr, "sound_1_124"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "why";
			arr[4] = "she";
			arr[5] = "draw";
			arr[6] = "drew";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "draws";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "does";
			arr[14] = "he";
			arr[15] = "they";
			list.push(new Question("Он рисует?", "Does he draw", arr, "sound_1_125"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "why";
			arr[4] = "she";
			arr[5] = "draw";
			arr[6] = "drew";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "draws";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "does";
			arr[14] = "he";
			arr[15] = "they";
			list.push(new Question("Мы рисуем.", "We draw", arr, "sound_1_126"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "why";
			arr[4] = "she";
			arr[5] = "draw";
			arr[6] = "drew";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "draws";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "does";
			arr[14] = "he";
			arr[15] = "they";
			list.push(new Question("Она рисует.", "She draws", arr, "sound_1_127"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "why";
			arr[4] = "she";
			arr[5] = "draw";
			arr[6] = "drew";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "draws";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "does";
			arr[14] = "he";
			arr[15] = "they";
			list.push(new Question("Я не рисую.", "I do not draw", arr, "sound_1_128"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "why";
			arr[4] = "she";
			arr[5] = "draw";
			arr[6] = "drew";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "draws";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "does";
			arr[14] = "he";
			arr[15] = "they";
			list.push(new Question("Он не рисует.", "He does not draw", arr, "sound_1_129"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "why";
			arr[4] = "she";
			arr[5] = "draw";
			arr[6] = "drew";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "draws";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "does";
			arr[14] = "he";
			arr[15] = "they";
			list.push(new Question("Ты рисовала?", "Did you draw", arr, "sound_1_130"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "why";
			arr[4] = "she";
			arr[5] = "draw";
			arr[6] = "drew";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "draws";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "does";
			arr[14] = "he";
			arr[15] = "they";
			list.push(new Question("Они нарисовали.", "They drew", arr, "sound_1_131"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "why";
			arr[4] = "she";
			arr[5] = "draw";
			arr[6] = "drew";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "draws";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "does";
			arr[14] = "he";
			arr[15] = "they";
			list.push(new Question("Я не рисовал.", "I did not draw", arr, "sound_1_132"));
		}
		
		// do
		private function Add_8():void
		{
			var arr:Array = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "why";
			arr[4] = "she";
			arr[5] = "this";
			arr[6] = "buys";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "there";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "does";
			arr[14] = "he";
			arr[15] = "they";
			list.push(new Question("Они будут делать?", "Will they do", arr, "sound_1_133"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "why";
			arr[4] = "she";
			arr[5] = "this";
			arr[6] = "buys";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "there";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "does";
			arr[14] = "he";
			arr[15] = "they";
			list.push(new Question("Она будет делать.", "She will do", arr, "sound_1_134"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "why";
			arr[4] = "she";
			arr[5] = "this";
			arr[6] = "buys";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "there";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "does";
			arr[14] = "he";
			arr[15] = "they";
			list.push(new Question("Мы не будем делать.", "We will not do", arr, "sound_1_135"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "why";
			arr[4] = "she";
			arr[5] = "this";
			arr[6] = "buys";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "there";
			arr[10] = "do";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "does";
			arr[14] = "he";
			arr[15] = "they";
			list.push(new Question("Ты делаешь?", "Do you do", arr, "sound_1_136"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "why";
			arr[4] = "she";
			arr[5] = "this";
			arr[6] = "buys";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "there";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "does";
			arr[14] = "he";
			arr[15] = "they";
			list.push(new Question("Она делает?", "Does she do", arr, "sound_1_137"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "why";
			arr[4] = "she";
			arr[5] = "this";
			arr[6] = "buys";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "there";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "does";
			arr[14] = "he";
			arr[15] = "they";
			list.push(new Question("Они делают.", "They do", arr, "sound_1_138"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "why";
			arr[4] = "she";
			arr[5] = "this";
			arr[6] = "buys";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "there";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "does";
			arr[14] = "he";
			arr[15] = "they";
			list.push(new Question("Он делает.", "He does", arr, "sound_1_139"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "why";
			arr[4] = "she";
			arr[5] = "this";
			arr[6] = "buys";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "there";
			arr[10] = "don't";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "does";
			arr[14] = "he";
			arr[15] = "they";
			list.push(new Question("Я не делаю.", "I don't do", arr, "sound_1_140"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "why";
			arr[4] = "she";
			arr[5] = "this";
			arr[6] = "buys";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "there";
			arr[10] = "don't";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "doesn't";
			arr[14] = "he";
			arr[15] = "they";
			list.push(new Question("Он не делает.", "He doesn't do", arr, "sound_1_141"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "why";
			arr[4] = "she";
			arr[5] = "this";
			arr[6] = "buys";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "there";
			arr[10] = "don't";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "doesn't";
			arr[14] = "he";
			arr[15] = "they";
			list.push(new Question("Ты сделал?", "Did you do", arr, "sound_1_142"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "why";
			arr[4] = "she";
			arr[5] = "this";
			arr[6] = "buys";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "there";
			arr[10] = "don't";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "doesn't";
			arr[14] = "he";
			arr[15] = "they";
			list.push(new Question("Мы сделали.", "We did", arr, "sound_1_143"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "why";
			arr[4] = "she";
			arr[5] = "this";
			arr[6] = "buys";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "there";
			arr[10] = "don't";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "not";
			arr[14] = "he";
			arr[15] = "they";
			list.push(new Question("Они не сделали.", "They did not do", arr, "sound_1_144"));
		}
		
		// choose
		private function Add_7():void
		{
			var arr:Array = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "chose";
			arr[4] = "she";
			arr[5] = "choose";
			arr[6] = "buys";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "chooses";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "does";
			arr[14] = "he";
			arr[15] = "they";
			list.push(new Question("Она выберет?", "Will she choose", arr, "sound_1_145"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "chose";
			arr[4] = "she";
			arr[5] = "choose";
			arr[6] = "buys";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "chooses";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "does";
			arr[14] = "he";
			arr[15] = "they";
			list.push(new Question("Я выберу.", "I will choose", arr, "sound_1_146"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "chose";
			arr[4] = "she";
			arr[5] = "choose";
			arr[6] = "buys";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "chooses";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "does";
			arr[14] = "he";
			arr[15] = "they";
			list.push(new Question("Они не выберут.", "They will not choose", arr, "sound_1_147"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "chose";
			arr[4] = "she";
			arr[5] = "choose";
			arr[6] = "buys";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "chooses";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "does";
			arr[14] = "he";
			arr[15] = "they";
			list.push(new Question("Он выбирает?", "Does he choose", arr, "sound_1_148"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "chose";
			arr[4] = "she";
			arr[5] = "choose";
			arr[6] = "buys";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "chooses";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "does";
			arr[14] = "he";
			arr[15] = "they";
			list.push(new Question("Я выбираю?", "Do I choose", arr, "sound_1_149"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "chose";
			arr[4] = "she";
			arr[5] = "choose";
			arr[6] = "buys";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "chooses";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "does";
			arr[14] = "he";
			arr[15] = "they";
			list.push(new Question("Она выбирает.", "She chooses", arr, "sound_1_150"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "chose";
			arr[4] = "she";
			arr[5] = "сhoose";
			arr[6] = "buys";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "chooses";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "does";
			arr[14] = "he";
			arr[15] = "they";
			list.push(new Question("Ты выбираешь.", "You сhoose", arr, "sound_1_151"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "chose";
			arr[4] = "she";
			arr[5] = "choose";
			arr[6] = "buys";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "chooses";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "does";
			arr[14] = "he";
			arr[15] = "they";
			list.push(new Question("Мы не выбираем.", "We do not choose", arr, "sound_1_152"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "chose";
			arr[4] = "she";
			arr[5] = "choose";
			arr[6] = "buys";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "chooses";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "does";
			arr[14] = "he";
			arr[15] = "they";
			list.push(new Question("Он не выберает.", "He does not choose", arr, "sound_1_153"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "chose";
			arr[4] = "she";
			arr[5] = "choose";
			arr[6] = "buys";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "chooses";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "does";
			arr[14] = "he";
			arr[15] = "they";
			list.push(new Question("Они выбрали?", "Did they choose", arr, "sound_1_154"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "chose";
			arr[4] = "she";
			arr[5] = "choose";
			arr[6] = "buys";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "chooses";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "does";
			arr[14] = "he";
			arr[15] = "they";
			list.push(new Question("Ты выбрал.", "You chose", arr, "sound_1_155"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "chose";
			arr[4] = "she";
			arr[5] = "choose";
			arr[6] = "buys";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "chooses";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "does";
			arr[14] = "he";
			arr[15] = "they";
			list.push(new Question("Я не выбирал.", "I did not choose", arr, "sound_1_156"));
		}
		
		// buy
		private function Add_6():void
		{
			var arr:Array = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "buy";
			arr[4] = "she";
			arr[5] = "work";
			arr[6] = "buys";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "bought";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "does";
			arr[14] = "he";
			arr[15] = "they";
			list.push(new Question("Ты купишь?", "Will you buy", arr, "sound_1_157"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "buy";
			arr[4] = "she";
			arr[5] = "work";
			arr[6] = "buys";
			arr[7] = "go";
			arr[8] = "you";
			arr[9] = "bought";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "does";
			arr[14] = "he";
			arr[15] = "they";
			list.push(new Question("Мы купим.", "We will buy", arr, "sound_1_158"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "buy";
			arr[4] = "she";
			arr[5] = "work";
			arr[6] = "buys";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "bought";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "does";
			arr[14] = "he";
			arr[15] = "they";
			list.push(new Question("Я не куплю.", "I will not buy", arr, "sound_1_159"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "buy";
			arr[4] = "she";
			arr[5] = "work";
			arr[6] = "buys";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "bought";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "does";
			arr[14] = "he";
			arr[15] = "they";
			list.push(new Question("Они покупают?", "Do they buy", arr, "sound_1_160"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "buy";
			arr[4] = "she";
			arr[5] = "work";
			arr[6] = "buys";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "bought";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "does";
			arr[14] = "he";
			arr[15] = "they";
			list.push(new Question("Она покупает?", "Does she buy", arr, "sound_1_161"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "buy";
			arr[4] = "she";
			arr[5] = "work";
			arr[6] = "buys";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "bought";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "does";
			arr[14] = "he";
			arr[15] = "they";
			list.push(new Question("Мы покупаем.", "We buy", arr, "sound_1_162"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "buy";
			arr[4] = "she";
			arr[5] = "work";
			arr[6] = "buys";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "bought";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "does";
			arr[14] = "he";
			arr[15] = "they";
			list.push(new Question("Он покупает.", "He buys", arr, "sound_1_163"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "buy";
			arr[4] = "she";
			arr[5] = "work";
			arr[6] = "buys";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "bought";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "does";
			arr[14] = "he";
			arr[15] = "they";
			list.push(new Question("Она не покупает.", "She does not buy", arr, "sound_1_164"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "buy";
			arr[4] = "she";
			arr[5] = "work";
			arr[6] = "buys";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "bought";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "does";
			arr[14] = "he";
			arr[15] = "they";
			list.push(new Question("Я не покупаю.", "I do not buy", arr, "sound_1_165"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "buy";
			arr[4] = "she";
			arr[5] = "work";
			arr[6] = "buys";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "bought";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "does";
			arr[14] = "he";
			arr[15] = "they";
			list.push(new Question("Ты купил?", "Did you buy", arr, "sound_1_166"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "buy";
			arr[4] = "she";
			arr[5] = "work";
			arr[6] = "buys";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "bought";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "does";
			arr[14] = "he";
			arr[15] = "they";
			list.push(new Question("Ты купил.", "You bought", arr, "sound_1_167"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "buy";
			arr[4] = "she";
			arr[5] = "work";
			arr[6] = "buys";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "bought";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "does";
			arr[14] = "he";
			arr[15] = "they";
			list.push(new Question("Они не купили.", "They did not buy", arr, "sound_1_168"));
			
			
		}
		
		// work
		private function Add_5():void
		{
			var arr:Array = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "worked";
			arr[4] = "she";
			arr[5] = "work";
			arr[6] = "build";
			arr[7] = "go";
			arr[8] = "you";
			arr[9] = "works";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "does";
			arr[14] = "he";
			arr[15] = "they";
			list.push(new Question("Ты будешь работать?", "Will you work", arr, "sound_1_169"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "worked";
			arr[4] = "came";
			arr[5] = "work";
			arr[6] = "build";
			arr[7] = "go";
			arr[8] = "you";
			arr[9] = "works";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "loved";
			arr[14] = "he";
			arr[15] = "they";
			list.push(new Question("Я буду работать.", "I will work", arr, "sound_1_170"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "worked";
			arr[4] = "came";
			arr[5] = "work";
			arr[6] = "build";
			arr[7] = "go";
			arr[8] = "you";
			arr[9] = "works";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "does";
			arr[14] = "he";
			arr[15] = "they";
			list.push(new Question("Мы не будем работать.", "We will not work", arr, "sound_1_171"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "worked";
			arr[4] = "came";
			arr[5] = "work";
			arr[6] = "build";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "works";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "does";
			arr[14] = "he";
			arr[15] = "they";
			list.push(new Question("Они работают?", "Do they work", arr, "sound_1_172"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "worked";
			arr[4] = "came";
			arr[5] = "work";
			arr[6] = "build";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "works";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "does";
			arr[14] = "he";
			arr[15] = "they";
			list.push(new Question("Он работает?", "Does he work", arr, "sound_1_173"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "worked";
			arr[4] = "came";
			arr[5] = "work";
			arr[6] = "build";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "works";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "does";
			arr[14] = "he";
			arr[15] = "she";
			list.push(new Question("Она работает", "She works", arr, "sound_1_174"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "worked";
			arr[4] = "they";
			arr[5] = "work";
			arr[6] = "build";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "works";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "does";
			arr[14] = "he";
			arr[15] = "she";
			list.push(new Question("Они работают", "They work", arr, "sound_1_175"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "worked";
			arr[4] = "they";
			arr[5] = "work";
			arr[6] = "build";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "works";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "does";
			arr[14] = "he";
			arr[15] = "she";
			list.push(new Question("Он не работает", "He does not work", arr, "sound_1_176"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "worked";
			arr[4] = "they";
			arr[5] = "work";
			arr[6] = "build";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "works";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "does";
			arr[14] = "he";
			arr[15] = "she";
			list.push(new Question("Я не работаю", "I do not work", arr, "sound_1_177"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "worked";
			arr[4] = "they";
			arr[5] = "work";
			arr[6] = "build";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "works";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "does";
			arr[14] = "he";
			arr[15] = "she";
			list.push(new Question("Ты работал?", "Did you work", arr, "sound_1_178"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "worked";
			arr[4] = "they";
			arr[5] = "work";
			arr[6] = "build";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "works";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "does";
			arr[14] = "he";
			arr[15] = "she";
			list.push(new Question("Мы работали.", "We worked", arr, "sound_1_179"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "worked";
			arr[4] = "they";
			arr[5] = "work";
			arr[6] = "build";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "works";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "does";
			arr[14] = "he";
			arr[15] = "she";
			list.push(new Question("Он не работал.", "He did not work", arr, "sound_1_180"));
		}
		
		// love
		private function Add_4():void
		{
			var arr:Array = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "love";
			arr[4] = "came";
			arr[5] = "loves";
			arr[6] = "build";
			arr[7] = "go";
			arr[8] = "you";
			arr[9] = "builds";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "loved";
			arr[14] = "youre";
			arr[15] = "break";
			list.push(new Question("Ты будешь любить?", "Will you love", arr, "sound_1_181"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "love";
			arr[4] = "came";
			arr[5] = "loves";
			arr[6] = "build";
			arr[7] = "go";
			arr[8] = "you";
			arr[9] = "builds";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "loved";
			arr[14] = "she";
			arr[15] = "break";
			list.push(new Question("Она будет любить.", "She will love", arr, "sound_1_182"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "love";
			arr[4] = "came";
			arr[5] = "loves";
			arr[6] = "they";
			arr[7] = "go";
			arr[8] = "you";
			arr[9] = "builds";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "loved";
			arr[14] = "she";
			arr[15] = "break";
			list.push(new Question("Они не будут любить.", "They will not love", arr, "sound_1_183"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "love";
			arr[4] = "came";
			arr[5] = "loves";
			arr[6] = "they";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "does";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "loved";
			arr[14] = "she";
			arr[15] = "break";
			list.push(new Question("Мы любим?", "Do we love", arr, "sound_1_184"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "love";
			arr[4] = "came";
			arr[5] = "loves";
			arr[6] = "they";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "builds";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "loved";
			arr[14] = "she";
			arr[15] = "does";
			list.push(new Question("Она любит?", "Does she love", arr, "sound_1_185"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "love";
			arr[4] = "he";
			arr[5] = "loves";
			arr[6] = "they";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "builds";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "loved";
			arr[14] = "she";
			arr[15] = "does";
			list.push(new Question("Он любит.", "He loves", arr, "sound_1_186"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "love";
			arr[4] = "he";
			arr[5] = "loves";
			arr[6] = "they";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "builds";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "loved";
			arr[14] = "she";
			arr[15] = "does";
			list.push(new Question("Ты любишь.", "You love", arr, "sound_1_187"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "love";
			arr[4] = "he";
			arr[5] = "loves";
			arr[6] = "they";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "doesn't";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "loved";
			arr[14] = "she";
			arr[15] = "it";
			list.push(new Question("Он не любит.", "He doesn't love", arr, "sound_1_188"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "love";
			arr[4] = "he";
			arr[5] = "loves";
			arr[6] = "they";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "doesn't";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "loved";
			arr[14] = "she";
			arr[15] = "it";
			list.push(new Question("Я не люблю.", "I do not love", arr, "sound_1_189"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "love";
			arr[4] = "he";
			arr[5] = "loves";
			arr[6] = "they";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "doesn't";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "loved";
			arr[14] = "she";
			arr[15] = "it";
			list.push(new Question("Она любила?", "Did she love", arr, "sound_1_190"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "love";
			arr[4] = "he";
			arr[5] = "loves";
			arr[6] = "they";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "doesn't";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "loved";
			arr[14] = "she";
			arr[15] = "it";
			list.push(new Question("Мы любили.", "We loved", arr, "sound_1_191"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "love";
			arr[4] = "he";
			arr[5] = "loves";
			arr[6] = "they";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "doesn't";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "loved";
			arr[14] = "she";
			arr[15] = "it";
			list.push(new Question("Ты не любил.", "You did not love", arr, "sound_1_192"));
		}
		
		// come (came)
		private function Add_3():void
		{
			var arr:Array = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "come";
			arr[4] = "came";
			arr[5] = "swear";
			arr[6] = "build";
			arr[7] = "go";
			arr[8] = "you";
			arr[9] = "builds";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "broke";
			arr[14] = "youre";
			arr[15] = "break";
			list.push(new Question("Мы придем?", "Will we come", arr, "sound_1_193"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "come";
			arr[4] = "came";
			arr[5] = "swear";
			arr[6] = "build";
			arr[7] = "go";
			arr[8] = "you";
			arr[9] = "comes";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "broke";
			arr[14] = "youre";
			arr[15] = "break";
			list.push(new Question("Я приду.", "I will come", arr, "sound_1_194"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "come";
			arr[4] = "came";
			arr[5] = "she";
			arr[6] = "build";
			arr[7] = "go";
			arr[8] = "you";
			arr[9] = "comes";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "broke";
			arr[14] = "youre";
			arr[15] = "break";
			list.push(new Question("Она не придет.", "She will not come", arr, "sound_1_195"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "come";
			arr[4] = "came";
			arr[5] = "she";
			arr[6] = "build";
			arr[7] = "go";
			arr[8] = "you";
			arr[9] = "comes";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "broke";
			arr[14] = "youre";
			arr[15] = "do";
			list.push(new Question("Мы приходим?", "Do we come", arr, "sound_1_196"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "come";
			arr[4] = "came";
			arr[5] = "she";
			arr[6] = "build";
			arr[7] = "go";
			arr[8] = "you";
			arr[9] = "comes";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "broke";
			arr[14] = "does";
			arr[15] = "do";
			list.push(new Question("Она приходит?", "Does she come", arr, "sound_1_197"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "come";
			arr[4] = "came";
			arr[5] = "she";
			arr[6] = "build";
			arr[7] = "go";
			arr[8] = "you";
			arr[9] = "they";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "comes";
			arr[14] = "does";
			arr[15] = "do";
			list.push(new Question("Они приходят.", "They come", arr, "sound_1_198"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "come";
			arr[4] = "came";
			arr[5] = "she";
			arr[6] = "comes";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "they";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "broke";
			arr[14] = "does";
			arr[15] = "do";
			list.push(new Question("Он приходит.", "He comes", arr, "sound_1_199"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "come";
			arr[4] = "came";
			arr[5] = "she";
			arr[6] = "comes";
			arr[7] = "go";
			arr[8] = "you";
			arr[9] = "they";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "broke";
			arr[14] = "does";
			arr[15] = "do";
			//list.push(new Question("Я не прихожу.", "I do not come", arr));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "come";
			arr[4] = "came";
			arr[5] = "she";
			arr[6] = "comes";
			arr[7] = "go";
			arr[8] = "you";
			arr[9] = "they";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "broke";
			arr[14] = "does";
			arr[15] = "do";
			//list.push(new Question("Она не приходит.", "She does not come", arr));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "come";
			arr[4] = "came";
			arr[5] = "she";
			arr[6] = "comes";
			arr[7] = "go";
			arr[8] = "you";
			arr[9] = "they";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "broke";
			arr[14] = "does";
			arr[15] = "do";
			list.push(new Question("Они приходили?", "Did they come", arr, "sound_1_200"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "come";
			arr[4] = "came";
			arr[5] = "she";
			arr[6] = "comes";
			arr[7] = "go";
			arr[8] = "you";
			arr[9] = "they";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "broke";
			arr[14] = "does";
			arr[15] = "do";
			list.push(new Question("Я пришел.", "I came", arr, "sound_1_201"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "come";
			arr[4] = "came";
			arr[5] = "she";
			arr[6] = "comes";
			arr[7] = "go";
			arr[8] = "you";
			arr[9] = "they";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "broke";
			arr[14] = "does";
			arr[15] = "do";
			list.push(new Question("Они не приходили.", "They did not come", arr, "sound_1_202"));
			
		}
		
		// build
		private function Add_2():void
		{
			var arr:Array = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "come";
			arr[4] = "came";
			arr[5] = "swear";
			arr[6] = "build";
			arr[7] = "go";
			arr[8] = "you";
			arr[9] = "builds";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "broke";
			arr[14] = "youre";
			arr[15] = "break";
			list.push(new Question("Мы построим?", "Will we build", arr, "sound_1_203"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "come";
			arr[4] = "came";
			arr[5] = "you";
			arr[6] = "build";
			arr[7] = "go";
			arr[8] = "you";
			arr[9] = "builds";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "broke";
			arr[14] = "youre";
			arr[15] = "break";
			list.push(new Question("Ты построишь.", "You will build", arr, "sound_1_204"));
			
			arr = new Array(15);
			arr[0] = "they";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "come";
			arr[4] = "came";
			arr[5] = "you";
			arr[6] = "build";
			arr[7] = "go";
			arr[8] = "you";
			arr[9] = "builds";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "broke";
			arr[14] = "youre";
			arr[15] = "break";
			list.push(new Question("Они не построят.", "They will not build", arr, "sound_1_205"));
			
			arr = new Array(15);
			arr[0] = "they";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "do";
			arr[4] = "came";
			arr[5] = "you";
			arr[6] = "build";
			arr[7] = "go";
			arr[8] = "you";
			arr[9] = "builds";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "broke";
			arr[14] = "youre";
			arr[15] = "break";
			list.push(new Question("Ты строишь?", "Do you build", arr, "sound_1_206"));
			
			arr = new Array(15);
			arr[0] = "they";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "do";
			arr[4] = "came";
			arr[5] = "you";
			arr[6] = "build";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "builds";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "broke";
			arr[14] = "does";
			arr[15] = "break";
			list.push(new Question("Он строит?", "Does he build", arr, "sound_1_207"));
			
			arr = new Array(15);
			arr[0] = "they";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "do";
			arr[4] = "came";
			arr[5] = "you";
			arr[6] = "build";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "builds";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "broke";
			arr[14] = "does";
			arr[15] = "break";
			list.push(new Question("Они строят.", "They build", arr, "sound_1_208"));
			
			arr = new Array(15);
			arr[0] = "they";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "do";
			arr[4] = "she";
			arr[5] = "you";
			arr[6] = "build";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "builds";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "broke";
			arr[14] = "does";
			arr[15] = "break";
			list.push(new Question("Она строит.", "She builds", arr, "sound_1_209"));
			
			arr = new Array(15);
			arr[0] = "they";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "do";
			arr[4] = "she";
			arr[5] = "I";
			arr[6] = "build";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "builds";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "broke";
			arr[14] = "does";
			arr[15] = "break";
			list.push(new Question("Я не строю.", "I do not build", arr, "sound_1_210"));
			
			arr = new Array(15);
			arr[0] = "they";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "do";
			arr[4] = "she";
			arr[5] = "I";
			arr[6] = "build";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "builds";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "broke";
			arr[14] = "does";
			arr[15] = "break";
			list.push(new Question("Она не строит.", "She does not build", arr, "sound_1_211"));
			
			arr = new Array(15);
			arr[0] = "they";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "do";
			arr[4] = "she";
			arr[5] = "I";
			arr[6] = "build";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "builds";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "broke";
			arr[14] = "does";
			arr[15] = "break";
			list.push(new Question("Он строил?", "Did he build", arr, "sound_1_212"));
			
			arr = new Array(15);
			arr[0] = "they";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "do";
			arr[4] = "she";
			arr[5] = "I";
			arr[6] = "build";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "builds";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "built";
			arr[14] = "does";
			arr[15] = "break";
			list.push(new Question("Мы построили.", "We built", arr, "sound_1_213"));
			
			arr = new Array(15);
			arr[0] = "they";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "do";
			arr[4] = "she";
			arr[5] = "I";
			arr[6] = "build";
			arr[7] = "he";
			arr[8] = "you";
			arr[9] = "builds";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "built";
			arr[14] = "does";
			arr[15] = "break";
			list.push(new Question("Ты не строил.", "You did not build", arr, "sound_1_214"));
		}
		
		// break
		private function Add_1():void
		{
			var arr:Array = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "come";
			arr[4] = "came";
			arr[5] = "swear";
			arr[6] = "build";
			arr[7] = "go";
			arr[8] = "you";
			arr[9] = "breakable";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "hello";
			arr[13] = "broke";
			arr[14] = "listen";
			arr[15] = "break";
			list.push(new Question("Ты будешь ломать?", "Will you break", arr, "sound_1_215"));
			
			arr = new Array(15);
			arr[0] = "they";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "come";
			arr[4] = "she";
			arr[5] = "swear";
			arr[6] = "build";
			arr[7] = "go";
			arr[8] = "you";
			arr[9] = "conglatulation";
			arr[10] = "did not";
			arr[11] = "did";
			arr[12] = "he";
			arr[13] = "broke";
			arr[14] = "youre listen";
			arr[15] = "break";
			list.push(new Question("Она будет ломать.", "She will break", arr, "sound_1_216"));
			
			arr = new Array(15);
			arr[0] = "us";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "not";
			arr[4] = "she";
			arr[5] = "swear";
			arr[6] = "we";
			arr[7] = "go";
			arr[8] = "you";
			arr[9] = "breaks";
			arr[10] = "well";
			arr[11] = "did";
			arr[12] = "he";
			arr[13] = "broke";
			arr[14] = "does";
			arr[15] = "break";
			list.push(new Question("Мы не сломаем.", "We will not break", arr, "sound_1_217"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "not";
			arr[4] = "she";
			arr[5] = "swear";
			arr[6] = "we";
			arr[7] = "go";
			arr[8] = "you";
			arr[9] = "new";
			arr[10] = "get";
			arr[11] = "did";
			arr[12] = "he";
			arr[13] = "broke";
			arr[14] = "do";
			arr[15] = "break";
			list.push(new Question("Я ломаю?", "Do I break", arr, "sound_1_218"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "not";
			arr[4] = "she";
			arr[5] = "swear";
			arr[6] = "we";
			arr[7] = "go";
			arr[8] = "break";
			arr[9] = "they";
			arr[10] = "breaks";
			arr[11] = "did";
			arr[12] = "he";
			arr[13] = "broke";
			arr[14] = "do";
			arr[15] = "you";
			list.push(new Question("Они ломают.", "They break", arr, "sound_1_219"));
			
			arr = new Array(15);
			arr[0] = "has";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "not";
			arr[4] = "she";
			arr[5] = "swear";
			arr[6] = "we";
			arr[7] = "go";
			arr[8] = "break";
			arr[9] = "they";
			arr[10] = "breaks";
			arr[11] = "did";
			arr[12] = "he";
			arr[13] = "broke";
			arr[14] = "do";
			arr[15] = "you";
			list.push(new Question("Она ломает.", "She breaks", arr, "sound_1_220"));
			
			arr = new Array(15);
			arr[0] = "has";
			arr[1] = "me";
			arr[2] = "break";
			arr[3] = "not";
			arr[4] = "she";
			arr[5] = "does";
			arr[6] = "we";
			arr[7] = "go";
			arr[8] = "break";
			arr[9] = "they";
			arr[10] = "breaks";
			arr[11] = "did";
			arr[12] = "he";
			arr[13] = "broke";
			arr[14] = "don't";
			arr[15] = "I";
			list.push(new Question("Я не ломаю.", "I don't break", arr, "sound_1_221"));
			
			arr = new Array(15);
			arr[0] = "has";
			arr[1] = "me";
			arr[2] = "break";
			arr[3] = "not";
			arr[4] = "she";
			arr[5] = "does";
			arr[6] = "we";
			arr[7] = "go";
			arr[8] = "break";
			arr[9] = "they";
			arr[10] = "breaks";
			arr[11] = "did";
			arr[12] = "he";
			arr[13] = "broke";
			arr[14] = "don't";
			arr[15] = "I";
			list.push(new Question("Он не ломает.", "He does not break", arr, "sound_1_222"));
			
			arr = new Array(15);
			arr[0] = "you";
			arr[1] = "me";
			arr[2] = "break";
			arr[3] = "not";
			arr[4] = "she";
			arr[5] = "does";
			arr[6] = "we";
			arr[7] = "go";
			arr[8] = "break";
			arr[9] = "they";
			arr[10] = "breaks";
			arr[11] = "did";
			arr[12] = "he";
			arr[13] = "broke";
			arr[14] = "don't";
			arr[15] = "I";
			list.push(new Question("Ты сломал?", "Did you break", arr, "sound_1_223"));
			
			arr = new Array(15);
			arr[0] = "you";
			arr[1] = "me";
			arr[2] = "break";
			arr[3] = "not";
			arr[4] = "she";
			arr[5] = "does";
			arr[6] = "we";
			arr[7] = "go";
			arr[8] = "break";
			arr[9] = "they";
			arr[10] = "breaks";
			arr[11] = "did";
			arr[12] = "he";
			arr[13] = "broke";
			arr[14] = "don't";
			arr[15] = "I";
			list.push(new Question("Он сломал.", "He broke", arr, "sound_1_224"));
			
			arr = new Array(15);
			arr[0] = "you";
			arr[1] = "me";
			arr[2] = "break";
			arr[3] = "not";
			arr[4] = "she";
			arr[5] = "does";
			arr[6] = "we";
			arr[7] = "go";
			arr[8] = "break";
			arr[9] = "they";
			arr[10] = "breaks";
			arr[11] = "did";
			arr[12] = "he";
			arr[13] = "broke";
			arr[14] = "don't";
			arr[15] = "I";
			list.push(new Question("Они не ломали.", "They did not break", arr, "sound_1_225"));
		}
		
	}

}