package  
{
	import flash.display.Sprite;
	
	/**
	 * ...
	 * @author Vladimir
	 */
	public class PageLesson_13 extends Sprite 
	{
		private var stateManager:StateManager;
		private var list:Vector.<Question> = new Vector.<Question>(); // список вопросов
		
		public function PageLesson_13(manager:StateManager) 
		{
			stateManager = manager;
			
			Add_1();
			
			
			var a:Lesson = new Lesson(list, stateManager, 13);
			addChild(a);
			a.x = 40;
			a.y = 25;
			
			// добавляем к уроку конспект
			var wb:WorkBook = new WorkBook(new wb_13());
			a.AddWorkBook(wb);
		}
		
		private function Add_1():void 
		{
			var arr:Array = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "want";
			arr[4] = "she";
			arr[5] = "any";
			arr[6] = "to";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "from";
			arr[10] = "not";
			arr[11] = "him";
			arr[12] = "we";
			arr[13] = "go";
			arr[14] = "he";
			arr[15] = "have";
			list.push(new Question("Я хочу, чтобы ты пошел.", "I want you to go", arr, "sound_13_1"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "why";
			arr[4] = "she";
			arr[5] = "him";
			arr[6] = "to";
			arr[7] = "talk";
			arr[8] = "you";
			arr[9] = "the";
			arr[10] = "go";
			arr[11] = "them";
			arr[12] = "we";
			arr[13] = "on";
			arr[14] = "let";
			arr[15] = "they";
			list.push(new Question("Позволь ему пойти.", "Let him go", arr, "sound_13_2"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "speak";
			arr[4] = "she";
			arr[5] = "him";
			arr[6] = "to";
			arr[7] = "don't";
			arr[8] = "you";
			arr[9] = "the";
			arr[10] = "go";
			arr[11] = "with";
			arr[12] = "we";
			arr[13] = "on";
			arr[14] = "let";
			arr[15] = "they";
			list.push(new Question("Не говори с ним.", "Don't speak with him", arr, "sound_13_3"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "speak";
			arr[4] = "she";
			arr[5] = "it";
			arr[6] = "to";
			arr[7] = "don't";
			arr[8] = "you";
			arr[9] = "the";
			arr[10] = "go";
			arr[11] = "let's";
			arr[12] = "we";
			arr[13] = "about";
			arr[14] = "let";
			arr[15] = "they";
			list.push(new Question("Давай поговорим об этом.", "Let's speak about it", arr, "sound_13_4"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "speak";
			arr[4] = "him";
			arr[5] = "it";
			arr[6] = "to";
			arr[7] = "don't";
			arr[8] = "you";
			arr[9] = "the";
			arr[10] = "go";
			arr[11] = "let's";
			arr[12] = "we";
			arr[13] = "about";
			arr[14] = "let";
			arr[15] = "with";
			list.push(new Question("Не говори с ним об этом.", "Don't speak about it with him", arr, "sound_13_5"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "where";
			arr[4] = "him";
			arr[5] = "did";
			arr[6] = "to";
			arr[7] = "don't";
			arr[8] = "you";
			arr[9] = "the";
			arr[10] = "go";
			arr[11] = "let's";
			arr[12] = "we";
			arr[13] = "about";
			arr[14] = "let";
			arr[15] = "she";
			list.push(new Question("Куда она пошла?", "Where did she go", arr, "sound_13_6"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "went";
			arr[4] = "him";
			arr[5] = "did";
			arr[6] = "to";
			arr[7] = "don't";
			arr[8] = "you";
			arr[9] = "the";
			arr[10] = "go";
			arr[11] = "let's";
			arr[12] = "we";
			arr[13] = "dance";
			arr[14] = "let";
			arr[15] = "she";
			list.push(new Question("Она пошла танцевать.", "She went to dance", arr, "sound_13_7"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "tell";
			arr[4] = "her";
			arr[5] = "did";
			arr[6] = "to";
			arr[7] = "don't";
			arr[8] = "you";
			arr[9] = "the";
			arr[10] = "go";
			arr[11] = "let's";
			arr[12] = "we";
			arr[13] = "dance";
			arr[14] = "let";
			arr[15] = "everything";
			list.push(new Question("Пусть она расскажет тебе все.", "Let her tell me everything", arr, "sound_13_8"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "work";
			arr[4] = "her";
			arr[5] = "did";
			arr[6] = "to";
			arr[7] = "don't";
			arr[8] = "you";
			arr[9] = "the";
			arr[10] = "our";
			arr[11] = "let's";
			arr[12] = "we";
			arr[13] = "dance";
			arr[14] = "let";
			arr[15] = "discuss";
			list.push(new Question("Давайте обсудим нашу работу.", "Let's discuss our work", arr, "sound_13_9"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "work";
			arr[4] = "him";
			arr[5] = "did";
			arr[6] = "to";
			arr[7] = "don't";
			arr[8] = "you";
			arr[9] = "the";
			arr[10] = "our";
			arr[11] = "let's";
			arr[12] = "we";
			arr[13] = "dance";
			arr[14] = "let";
			arr[15] = "help";
			list.push(new Question("Позволь ему помочь мне.", "Let him help me", arr, "sound_13_10"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "today";
			arr[4] = "him";
			arr[5] = "did";
			arr[6] = "to";
			arr[7] = "don't";
			arr[8] = "you";
			arr[9] = "the";
			arr[10] = "our";
			arr[11] = "let's";
			arr[12] = "we";
			arr[13] = "go";
			arr[14] = "let";
			arr[15] = "there";
			list.push(new Question("Не ходи туда сегодня.", "Don't go there today", arr, "sound_13_11"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "can";
			arr[4] = "him";
			arr[5] = "did";
			arr[6] = "to";
			arr[7] = "don't";
			arr[8] = "you";
			arr[9] = "the";
			arr[10] = "our";
			arr[11] = "let's";
			arr[12] = "we";
			arr[13] = "go";
			arr[14] = "let";
			arr[15] = "smoke";
			list.push(new Question("Можно я закурю?", "Can I smoke", arr, "sound_13_12"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "can";
			arr[4] = "him";
			arr[5] = "did";
			arr[6] = "to";
			arr[7] = "don't";
			arr[8] = "you";
			arr[9] = "the";
			arr[10] = "our";
			arr[11] = "let's";
			arr[12] = "we";
			arr[13] = "go";
			arr[14] = "let";
			arr[15] = "out";
			list.push(new Question("Можно я выйду?", "Can I go out", arr, "sound_13_13"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "can";
			arr[4] = "him";
			arr[5] = "did";
			arr[6] = "to";
			arr[7] = "don't";
			arr[8] = "you";
			arr[9] = "the";
			arr[10] = "with";
			arr[11] = "let's";
			arr[12] = "we";
			arr[13] = "go";
			arr[14] = "let";
			arr[15] = "speak";
			list.push(new Question("Можно я поговорю с тобой?", "Can I speak with you", arr, "sound_13_14"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "can";
			arr[4] = "him";
			arr[5] = "did";
			arr[6] = "to";
			arr[7] = "don't";
			arr[8] = "you";
			arr[9] = "the";
			arr[10] = "it";
			arr[11] = "let's";
			arr[12] = "we";
			arr[13] = "one";
			arr[14] = "let";
			arr[15] = "do";
			list.push(new Question("Это можно сделать.", "One can do it", arr, "sound_13_15"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "can't";
			arr[4] = "him";
			arr[5] = "did";
			arr[6] = "to";
			arr[7] = "don't";
			arr[8] = "you";
			arr[9] = "the";
			arr[10] = "it";
			arr[11] = "let's";
			arr[12] = "we";
			arr[13] = "one";
			arr[14] = "let";
			arr[15] = "do";
			list.push(new Question("Этого нельзя сделать.", "One can't do it", arr, "sound_13_16"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "can";
			arr[4] = "somebody";
			arr[5] = "did";
			arr[6] = "to";
			arr[7] = "don't";
			arr[8] = "you";
			arr[9] = "the";
			arr[10] = "it";
			arr[11] = "let's";
			arr[12] = "we";
			arr[13] = "one";
			arr[14] = "let";
			arr[15] = "do";
			list.push(new Question("Кто-то может сделать это.", "Somebody can do it", arr, "sound_13_17"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "can";
			arr[4] = "somebody";
			arr[5] = "did";
			arr[6] = "to";
			arr[7] = "don't";
			arr[8] = "you";
			arr[9] = "should";
			arr[10] = "it";
			arr[11] = "let's";
			arr[12] = "go";
			arr[13] = "one";
			arr[14] = "let";
			arr[15] = "do";
			list.push(new Question("Надо ли мне идти?", "Should I go", arr, "sound_13_18"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "can";
			arr[4] = "somebody";
			arr[5] = "did";
			arr[6] = "to";
			arr[7] = "don't";
			arr[8] = "you";
			arr[9] = "should";
			arr[10] = "it";
			arr[11] = "let's";
			arr[12] = "go";
			arr[13] = "one";
			arr[14] = "let";
			arr[15] = "do";
			list.push(new Question("Стоит ли это делать?", "Should I do it", arr, "sound_13_19"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "remember";
			arr[3] = "can";
			arr[4] = "always";
			arr[5] = "did";
			arr[6] = "to";
			arr[7] = "don't";
			arr[8] = "you";
			arr[9] = "should";
			arr[10] = "it";
			arr[11] = "let's";
			arr[12] = "go";
			arr[13] = "one";
			arr[14] = "let";
			arr[15] = "do";
			list.push(new Question("Надо всегда помнить.", "One should always remember", arr, "sound_13_20"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "remember";
			arr[3] = "can";
			arr[4] = "talk";
			arr[5] = "did";
			arr[6] = "to";
			arr[7] = "don't";
			arr[8] = "you";
			arr[9] = "should";
			arr[10] = "it";
			arr[11] = "let's";
			arr[12] = "him";
			arr[13] = "one";
			arr[14] = "let";
			arr[15] = "think";
			list.push(new Question("Я думаю тебе надо поговорить с ним.", "I think you should talk to him", arr, "sound_13_21"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "call";
			arr[3] = "can";
			arr[4] = "talk";
			arr[5] = "did";
			arr[6] = "to";
			arr[7] = "don't";
			arr[8] = "you";
			arr[9] = "should";
			arr[10] = "it";
			arr[11] = "let's";
			arr[12] = "him";
			arr[13] = "one";
			arr[14] = "let";
			arr[15] = "think";
			list.push(new Question("Можно тебе позвонить?", "Can I call you", arr, "sound_13_22"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "call";
			arr[3] = "can";
			arr[4] = "talk";
			arr[5] = "did";
			arr[6] = "to";
			arr[7] = "don't";
			arr[8] = "you";
			arr[9] = "should";
			arr[10] = "it";
			arr[11] = "let's";
			arr[12] = "him";
			arr[13] = "one";
			arr[14] = "let";
			arr[15] = "think";
			list.push(new Question("Должен ли я тебе позвонить?", "Should I call you", arr, "sound_13_23"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "I";
			arr[2] = "call";
			arr[3] = "don't";
			arr[4] = "talk";
			arr[5] = "go";
			arr[6] = "to";
			arr[7] = "don't";
			arr[8] = "you";
			arr[9] = "should";
			arr[10] = "it";
			arr[11] = "if";
			arr[12] = "him";
			arr[13] = "one";
			arr[14] = "let";
			arr[15] = "know";
			list.push(new Question("Я не знаю нужно ли мне идти.", "I don't know if I should go", arr, "sound_13_24"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "can't";
			arr[2] = "call";
			arr[3] = "don't";
			arr[4] = "smoke";
			arr[5] = "go";
			arr[6] = "to";
			arr[7] = "don't";
			arr[8] = "you";
			arr[9] = "should";
			arr[10] = "it";
			arr[11] = "here";
			arr[12] = "him";
			arr[13] = "one";
			arr[14] = "let";
			arr[15] = "one";
			list.push(new Question("Здесь нельзя курить.", "One can't smoke here", arr, "sound_13_25"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "can't";
			arr[2] = "call";
			arr[3] = "don't";
			arr[4] = "smoke";
			arr[5] = "go";
			arr[6] = "about";
			arr[7] = "don't";
			arr[8] = "you";
			arr[9] = "shouldn't";
			arr[10] = "it";
			arr[11] = "here";
			arr[12] = "him";
			arr[13] = "think";
			arr[14] = "we";
			arr[15] = "one";
			list.push(new Question("Мы не должны думать об этом.", "We shouldn't think about it", arr, "sound_13_26"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "can't";
			arr[2] = "call";
			arr[3] = "don't";
			arr[4] = "talk";
			arr[5] = "go";
			arr[6] = "about";
			arr[7] = "don't";
			arr[8] = "you";
			arr[9] = "shouldn't";
			arr[10] = "it";
			arr[11] = "here";
			arr[12] = "him";
			arr[13] = "that";
			arr[14] = "we";
			arr[15] = "like";
			list.push(new Question("Ты не должен так говорить.", "You shouldn't talk like that", arr, "sound_13_27"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "can't";
			arr[2] = "call";
			arr[3] = "don't";
			arr[4] = "talk";
			arr[5] = "go";
			arr[6] = "about";
			arr[7] = "don't";
			arr[8] = "you";
			arr[9] = "shouldn't";
			arr[10] = "it";
			arr[11] = "here";
			arr[12] = "like";
			arr[13] = "that";
			arr[14] = "we";
			arr[15] = "one";
			list.push(new Question("Никто не может так говорить.", "One shouldn't talk like that", arr, "sound_13_28"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "know";
			arr[2] = "if";
			arr[3] = "don't";
			arr[4] = "I";
			arr[5] = "go";
			arr[6] = "about";
			arr[7] = "don't";
			arr[8] = "you";
			arr[9] = "should";
			arr[10] = "it";
			arr[11] = "here";
			arr[12] = "about";
			arr[13] = "speak";
			arr[14] = "him";
			arr[15] = "with";
			list.push(new Question("Я не знаю можно ли говорить с ним об этом.", "I don't know if I should speak about it with him", arr, "sound_13_29"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "can't";
			arr[2] = "call";
			arr[3] = "don't";
			arr[4] = "talk";
			arr[5] = "go";
			arr[6] = "about";
			arr[7] = "don't";
			arr[8] = "you";
			arr[9] = "should";
			arr[10] = "it";
			arr[11] = "here";
			arr[12] = "like";
			arr[13] = "help";
			arr[14] = "we";
			arr[15] = "one";
			list.push(new Question("Можно ли помочь тебе?", "Should I help you", arr, "sound_13_30"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "can't";
			arr[2] = "call";
			arr[3] = "don't";
			arr[4] = "talk";
			arr[5] = "go";
			arr[6] = "about";
			arr[7] = "don't";
			arr[8] = "you";
			arr[9] = "should";
			arr[10] = "it";
			arr[11] = "do";
			arr[12] = "like";
			arr[13] = "now";
			arr[14] = "we";
			arr[15] = "one";
			list.push(new Question("Мы не можем делать этого сейчас.", "We can't do it now", arr, "sound_13_31"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "can't";
			arr[2] = "call";
			arr[3] = "tell";
			arr[4] = "talk";
			arr[5] = "go";
			arr[6] = "about";
			arr[7] = "don't";
			arr[8] = "you";
			arr[9] = "should";
			arr[10] = "it";
			arr[11] = "do";
			arr[12] = "like";
			arr[13] = "me";
			arr[14] = "we";
			arr[15] = "one";
			list.push(new Question("Скажите мне.", "Tell me", arr, "sound_13_32"));
		}
	}

}