package  
{
	import flash.display.Sprite;
	
	/**
	 * ...
	 * @author Vladimir
	 */
	public class PageLesson_8 extends Sprite 
	{
		private var stateManager:StateManager;
		private var list:Vector.<Question> = new Vector.<Question>(); // список вопросов
		
		public function PageLesson_8(manager:StateManager) 
		{
			stateManager = manager;
			
			Add_1();
			
			
			var a:Lesson = new Lesson(list, stateManager, 8);
			addChild(a);
			a.x = 40;
			a.y = 25;
		}
		
		private function Add_1():void 
		{
			var arr:Array = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "why";
			arr[4] = "she";
			arr[5] = "far";
			arr[6] = "to";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "from";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "does";
			arr[14] = "he";
			arr[15] = "they";
			list.push(new Question("Я от тебя далеко.", "I far from you", arr, "sound_8_1"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "why";
			arr[4] = "she";
			arr[5] = "food";
			arr[6] = "to";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "the";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "on";
			arr[14] = "table";
			arr[15] = "they";
			list.push(new Question("Еда на столе.", "Food on the table", arr, "sound_8_2"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "why";
			arr[4] = "she";
			arr[5] = "food";
			arr[6] = "to";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "the";
			arr[10] = "knocked";
			arr[11] = "he";
			arr[12] = "we";
			arr[13] = "on";
			arr[14] = "table";
			arr[15] = "they";
			list.push(new Question("Он стучал по столу.", "He knocked on the table", arr, "sound_8_3"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "at";
			arr[5] = "food";
			arr[6] = "to";
			arr[7] = "do";
			arr[8] = "children";
			arr[9] = "the";
			arr[10] = "knocked";
			arr[11] = "he";
			arr[12] = "we";
			arr[13] = "on";
			arr[14] = "school";
			arr[15] = "they";
			list.push(new Question("Дети в школе.", "Children at school", arr, "sound_8_4"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "at";
			arr[5] = "home";
			arr[6] = "to";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "the";
			arr[10] = "yesterday";
			arr[11] = "he";
			arr[12] = "we";
			arr[13] = "on";
			arr[14] = "was";
			arr[15] = "they";
			list.push(new Question("Вчера я был дома.", "Yesterday I was at home", arr, "sound_8_5"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "be";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "at";
			arr[5] = "home";
			arr[6] = "to";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "the";
			arr[10] = "room";
			arr[11] = "he";
			arr[12] = "we";
			arr[13] = "on";
			arr[14] = "was";
			arr[15] = "this";
			list.push(new Question("Я буду в этой комнате.", "I will be in this room", arr, "sound_8_6"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "be";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "at";
			arr[5] = "meet";
			arr[6] = "to";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "the";
			arr[10] = "o'clock";
			arr[11] = "he";
			arr[12] = "we";
			arr[13] = "on";
			arr[14] = "3";
			arr[15] = "this";
			list.push(new Question("Встретимся в 3 часа.", "I will meet you at 3 o'clock", arr, "sound_8_7"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "be";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "at";
			arr[5] = "and";
			arr[6] = "to";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "the";
			arr[10] = "between";
			arr[11] = "me";
			arr[12] = "we";
			arr[13] = "on";
			arr[14] = "his";
			arr[15] = "this";
			list.push(new Question("Между мной и тобой.", "Between you and me", arr, "sound_8_8"));
			
			arr = new Array(15);
			arr[0] = "us";
			arr[1] = "be";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "at";
			arr[5] = "and";
			arr[6] = "to";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "the";
			arr[10] = "between";
			arr[11] = "is";
			arr[12] = "we";
			arr[13] = "on";
			arr[14] = "just";
			arr[15] = "this";
			list.push(new Question("Это останется между нами.", "This is just between us", arr, "sound_8_9"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "be";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "at";
			arr[5] = "and";
			arr[6] = "to";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "the";
			arr[10] = "go";
			arr[11] = "is";
			arr[12] = "without";
			arr[13] = "on";
			arr[14] = "with";
			arr[15] = "this";
			list.push(new Question("Я пойду без тебя.", "I will go without you", arr, "sound_8_10"));
			
			arr = new Array(15);
			arr[0] = "he";
			arr[1] = "be";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "a";
			arr[5] = "and";
			arr[6] = "to";
			arr[7] = "do";
			arr[8] = "friend";
			arr[9] = "the";
			arr[10] = "go";
			arr[11] = "is";
			arr[12] = "without";
			arr[13] = "on";
			arr[14] = "with";
			arr[15] = "come";
			list.push(new Question("Он придет с другом.", "He will come with a friend", arr, "sound_8_11"));
			
			arr = new Array(15);
			arr[0] = "he";
			arr[1] = "sugar";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "a";
			arr[5] = "and";
			arr[6] = "to";
			arr[7] = "do";
			arr[8] = "tea";
			arr[9] = "the";
			arr[10] = "go";
			arr[11] = "is";
			arr[12] = "without";
			arr[13] = "on";
			arr[14] = "with";
			arr[15] = "come";
			list.push(new Question("Чай с сахаром.", "Tea with sugar", arr, "sound_8_12"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "it";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "a";
			arr[5] = "and";
			arr[6] = "to";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "the";
			arr[10] = "for";
			arr[11] = "is";
			arr[12] = "without";
			arr[13] = "on";
			arr[14] = "with";
			arr[15] = "come";
			list.push(new Question("Я делаю это для тебя.", "I do it for you", arr, "sound_8_13"));
			
			arr = new Array(15);
			arr[0] = "me";
			arr[1] = "it";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "a";
			arr[5] = "and";
			arr[6] = "to";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "the";
			arr[10] = "for";
			arr[11] = "is";
			arr[12] = "without";
			arr[13] = "on";
			arr[14] = "with";
			arr[15] = "come";
			list.push(new Question("Сделай это для меня.", "Do it for me", arr, "sound_8_14"));
			
			arr = new Array(15);
			arr[0] = "me";
			arr[1] = "it";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "father";
			arr[5] = "your";
			arr[6] = "to";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "the";
			arr[10] = "for";
			arr[11] = "is";
			arr[12] = "about";
			arr[13] = "on";
			arr[14] = "with";
			arr[15] = "tell";
			list.push(new Question("Расскажи мне о своем отце.", "Tell me about your father", arr, "sound_8_15"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "it";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "think";
			arr[5] = "your";
			arr[6] = "to";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "the";
			arr[10] = "for";
			arr[11] = "is";
			arr[12] = "about";
			arr[13] = "on";
			arr[14] = "with";
			arr[15] = "tell";
			list.push(new Question("Я думаю о тебе.", "I think about you", arr, "sound_8_16"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "it";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "think";
			arr[5] = "your";
			arr[6] = "to";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "the";
			arr[10] = "for";
			arr[11] = "is";
			arr[12] = "about";
			arr[13] = "on";
			arr[14] = "with";
			arr[15] = "tell";
			list.push(new Question("Подумай об этом.", "Think about it", arr, "sound_8_17"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "it";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "years";
			arr[5] = "your";
			arr[6] = "20";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "the";
			arr[10] = "for";
			arr[11] = "is";
			arr[12] = "about";
			arr[13] = "on";
			arr[14] = "was";
			arr[15] = "she";
			list.push(new Question("Ей около 20 лет.", "She was about 20 years", arr, "sound_8_18"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "it";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "minutes";
			arr[5] = "your";
			arr[6] = "3";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "the";
			arr[10] = "for";
			arr[11] = "is";
			arr[12] = "about";
			arr[13] = "on";
			arr[14] = "was";
			arr[15] = "she";
			list.push(new Question("Около 3 минут.", "About 3 minutes", arr, "sound_8_19"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "it";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "to";
			arr[5] = "room";
			arr[6] = "go";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "the";
			arr[10] = "up";
			arr[11] = "is";
			arr[12] = "my";
			arr[13] = "on";
			arr[14] = "was";
			arr[15] = "she";
			list.push(new Question("Поднимись в мою комнату.", "Go up to my room", arr, "sound_8_20"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "it";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "to";
			arr[5] = "basement";
			arr[6] = "go";
			arr[7] = "do";
			arr[8] = "down";
			arr[9] = "the";
			arr[10] = "up";
			arr[11] = "is";
			arr[12] = "my";
			arr[13] = "on";
			arr[14] = "went";
			arr[15] = "we";
			list.push(new Question("Мы спустились в подвал.", "We went down to the basement", arr, "sound_8_21"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "it";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "to";
			arr[5] = "basement";
			arr[6] = "go";
			arr[7] = "do";
			arr[8] = "down";
			arr[9] = "the";
			arr[10] = "up";
			arr[11] = "is";
			arr[12] = "me";
			arr[13] = "on";
			arr[14] = "went";
			arr[15] = "we";
			list.push(new Question("Спустись ко мне.", "Go down to me", arr, "sound_8_22"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "it";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "to";
			arr[5] = "get";
			arr[6] = "go";
			arr[7] = "do";
			arr[8] = "down";
			arr[9] = "the";
			arr[10] = "back";
			arr[11] = "you";
			arr[12] = "me";
			arr[13] = "on";
			arr[14] = "went";
			arr[15] = "we";
			list.push(new Question("Я вернусь к тебе.", "I will get back to you", arr, "sound_8_23"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "it";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "to";
			arr[5] = "road";
			arr[6] = "go";
			arr[7] = "away";
			arr[8] = "down";
			arr[9] = "the";
			arr[10] = "back";
			arr[11] = "you";
			arr[12] = "me";
			arr[13] = "on";
			arr[14] = "from";
			arr[15] = "we";
			list.push(new Question("Отойди с дороги.", "Go away from the road", arr, "sound_8_24"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "it";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "to";
			arr[5] = "road";
			arr[6] = "go";
			arr[7] = "tomorrow";
			arr[8] = "down";
			arr[9] = "the";
			arr[10] = "back";
			arr[11] = "you";
			arr[12] = "me";
			arr[13] = "on";
			arr[14] = "from";
			arr[15] = "we";
			list.push(new Question("Завтра мы к тебе зайдем.", "Tomorrow we will go to you", arr, "sound_8_25"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "it";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "to";
			arr[5] = "road";
			arr[6] = "go";
			arr[7] = "today";
			arr[8] = "down";
			arr[9] = "not";
			arr[10] = "back";
			arr[11] = "you";
			arr[12] = "me";
			arr[13] = "on";
			arr[14] = "out";
			arr[15] = "we";
			list.push(new Question("Сегодня я не выйду.", "Today I will not go out", arr, "sound_8_26"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "it";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "to";
			arr[5] = "look";
			arr[6] = "go";
			arr[7] = "today";
			arr[8] = "down";
			arr[9] = "if";
			arr[10] = "back";
			arr[11] = "you";
			arr[12] = "me";
			arr[13] = "on";
			arr[14] = "out";
			arr[15] = "we";
			list.push(new Question("Если ты оглянешься...", "If you look back", arr, "sound_8_27"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "it";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "to";
			arr[5] = "look";
			arr[6] = "go";
			arr[7] = "today";
			arr[8] = "down";
			arr[9] = "if";
			arr[10] = "back";
			arr[11] = "you";
			arr[12] = "me";
			arr[13] = "on";
			arr[14] = "up";
			arr[15] = "we";
			list.push(new Question("Посмотри вверх.", "Look up", arr, "sound_8_28"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "from";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "to";
			arr[5] = "look";
			arr[6] = "go";
			arr[7] = "away";
			arr[8] = "down";
			arr[9] = "if";
			arr[10] = "back";
			arr[11] = "you";
			arr[12] = "me";
			arr[13] = "on";
			arr[14] = "do";
			arr[15] = "not";
			list.push(new Question("Не отворачивайся от меня.", "Do not look away from me", arr, "sound_8_29"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "from";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "to";
			arr[5] = "look";
			arr[6] = "go";
			arr[7] = "window";
			arr[8] = "out";
			arr[9] = "yesterday";
			arr[10] = "looked";
			arr[11] = "you";
			arr[12] = "me";
			arr[13] = "on";
			arr[14] = "the";
			arr[15] = "she";
			list.push(new Question("Вчера она выглянула в окно.", "Yesterday she looked out the window", arr, "sound_8_30"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "from";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "to";
			arr[5] = "look";
			arr[6] = "go";
			arr[7] = "her";
			arr[8] = "out";
			arr[9] = "away";
			arr[10] = "looked";
			arr[11] = "you";
			arr[12] = "get";
			arr[13] = "on";
			arr[14] = "the";
			arr[15] = "she";
			list.push(new Question("Я отделался от нее.", "I get away from her", arr, "sound_8_31"));
		}
	}

}