package  
{
	import flash.display.Sprite;
	
	/**
	 * ...
	 * @author Vladimir
	 */
	public class PageLesson_9 extends Sprite 
	{
		private var stateManager:StateManager;
		private var list:Vector.<Question> = new Vector.<Question>(); // список вопросов
		
		public function PageLesson_9(manager:StateManager) 
		{
			stateManager = manager;
			
			Add_1();
			
			
			var a:Lesson = new Lesson(list, stateManager, 9);
			addChild(a);
			a.x = 40;
			a.y = 25;
		}
		
		private function Add_1():void 
		{
			var arr:Array = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "questions";
			arr[4] = "she";
			arr[5] = "any";
			arr[6] = "to";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "from";
			arr[10] = "not";
			arr[11] = "him";
			arr[12] = "we";
			arr[13] = "for";
			arr[14] = "he";
			arr[15] = "have";
			list.push(new Question("У тебя есть вопросы к нему?", "Do you have any questions for him", arr, "sound_9_1"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "why";
			arr[4] = "she";
			arr[5] = "yesterday";
			arr[6] = "to";
			arr[7] = "talk";
			arr[8] = "you";
			arr[9] = "the";
			arr[10] = "not";
			arr[11] = "them";
			arr[12] = "we";
			arr[13] = "on";
			arr[14] = "talked";
			arr[15] = "they";
			list.push(new Question("Вчера я разговаривал с ними.", "Yesterday I talked to them", arr, "sound_9_2"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "why";
			arr[4] = "she";
			arr[5] = "must";
			arr[6] = "to";
			arr[7] = "about";
			arr[8] = "you";
			arr[9] = "the";
			arr[10] = "not";
			arr[11] = "them";
			arr[12] = "we";
			arr[13] = "on";
			arr[14] = "forget";
			arr[15] = "they";
			list.push(new Question("Ты должен забыть обо мне.", "You must forget about me", arr, "sound_9_3"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "want";
			arr[2] = "will";
			arr[3] = "why";
			arr[4] = "an";
			arr[5] = "interesting";
			arr[6] = "to";
			arr[7] = "about";
			arr[8] = "you";
			arr[9] = "the";
			arr[10] = "tell";
			arr[11] = "them";
			arr[12] = "we";
			arr[13] = "on";
			arr[14] = "story";
			arr[15] = "they";
			list.push(new Question("Я хочу рассказать тебе интересную историю.", "I want to tell you an interesting story", arr, "sound_9_4"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "why";
			arr[4] = "she";
			arr[5] = "get";
			arr[6] = "to";
			arr[7] = "about";
			arr[8] = "you";
			arr[9] = "the";
			arr[10] = "not";
			arr[11] = "how";
			arr[12] = "we";
			arr[13] = "on";
			arr[14] = "did";
			arr[15] = "role";
			list.push(new Question("Как ты получил эту роль?", "How did you get the role", arr, "sound_9_5"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "why";
			arr[4] = "she";
			arr[5] = "be";
			arr[6] = "to";
			arr[7] = "about";
			arr[8] = "you";
			arr[9] = "the";
			arr[10] = "not";
			arr[11] = "how";
			arr[12] = "we";
			arr[13] = "on";
			arr[14] = "glad";
			arr[15] = "see";
			list.push(new Question("Я буду рад видеть тебя.", "I will be glad to see you", arr, "sound_9_6"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "why";
			arr[4] = "she";
			arr[5] = "be";
			arr[6] = "to";
			arr[7] = "about";
			arr[8] = "you";
			arr[9] = "the";
			arr[10] = "something";
			arr[11] = "how";
			arr[12] = "am";
			arr[13] = "on";
			arr[14] = "happy";
			arr[15] = "with";
			list.push(new Question("Я доволен чем-то.", "I am happy with something", arr, "sound_9_7"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "why";
			arr[4] = "she";
			arr[5] = "be";
			arr[6] = "to";
			arr[7] = "about";
			arr[8] = "you";
			arr[9] = "it";
			arr[10] = "myself";
			arr[11] = "how";
			arr[12] = "am";
			arr[13] = "do";
			arr[14] = "yourself";
			arr[15] = "with";
			list.push(new Question("Я сам сделаю это.", "I will do it myself", arr, "sound_9_8"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "why";
			arr[4] = "she";
			arr[5] = "be";
			arr[6] = "to";
			arr[7] = "about";
			arr[8] = "you";
			arr[9] = "it";
			arr[10] = "myself";
			arr[11] = "yourself";
			arr[12] = "am";
			arr[13] = "do";
			arr[14] = "happy";
			arr[15] = "with";
			list.push(new Question("Сделай это сам.", "Do it yourself", arr, "sound_9_9"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "he";
			arr[2] = "will";
			arr[3] = "why";
			arr[4] = "she";
			arr[5] = "be";
			arr[6] = "to";
			arr[7] = "with";
			arr[8] = "you";
			arr[9] = "it";
			arr[10] = "myself";
			arr[11] = "yourself";
			arr[12] = "himself";
			arr[13] = "do";
			arr[14] = "happy";
			arr[15] = "is";
			list.push(new Question("Он доволен сам собой.", "He is happy with himself", arr, "sound_9_10"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "why";
			arr[4] = "she";
			arr[5] = "be";
			arr[6] = "to";
			arr[7] = "with";
			arr[8] = "you";
			arr[9] = "it";
			arr[10] = "myself";
			arr[11] = "yourself";
			arr[12] = "himself";
			arr[13] = "do";
			arr[14] = "ourselves";
			arr[15] = "is";
			list.push(new Question("Мы сделаем это сами.", "We will do it ourselves", arr, "sound_9_11"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "they";
			arr[2] = "will";
			arr[3] = "why";
			arr[4] = "themselves";
			arr[5] = "be";
			arr[6] = "to";
			arr[7] = "with";
			arr[8] = "you";
			arr[9] = "it";
			arr[10] = "myself";
			arr[11] = "yourself";
			arr[12] = "himself";
			arr[13] = "do";
			arr[14] = "ourselves";
			arr[15] = "is";
			list.push(new Question("Они делают это сами.", "They do it themselves", arr, "sound_9_12"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "they";
			arr[2] = "will";
			arr[3] = "why";
			arr[4] = "short";
			arr[5] = "be";
			arr[6] = "to";
			arr[7] = "with";
			arr[8] = "you";
			arr[9] = "it";
			arr[10] = "did";
			arr[11] = "are";
			arr[12] = "himself";
			arr[13] = "do";
			arr[14] = "was";
			arr[15] = "is";
			list.push(new Question("Я буду краток.", "I will be short", arr, "sound_9_13"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "they";
			arr[2] = "will";
			arr[3] = "was";
			arr[4] = "good";
			arr[5] = "be";
			arr[6] = "to";
			arr[7] = "with";
			arr[8] = "you";
			arr[9] = "it";
			arr[10] = "weather";
			arr[11] = "are";
			arr[12] = "fortunately";
			arr[13] = "do";
			arr[14] = "the";
			arr[15] = "is";
			list.push(new Question("К счастью была хорошая погода.", "Fortunately the weather was good", arr, "sound_9_14"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "they";
			arr[2] = "will";
			arr[3] = "was";
			arr[4] = "am";
			arr[5] = "be";
			arr[6] = "to";
			arr[7] = "with";
			arr[8] = "you";
			arr[9] = "it";
			arr[10] = "late";
			arr[11] = "are";
			arr[12] = "Unfortunately";
			arr[13] = "do";
			arr[14] = "the";
			arr[15] = "is";
			list.push(new Question("К сожалению я опоздал.", "Unfortunately I am late", arr, "sound_9_15"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "gone";
			arr[2] = "will";
			arr[3] = "was";
			arr[4] = "all";
			arr[5] = "be";
			arr[6] = "to";
			arr[7] = "that";
			arr[8] = "you";
			arr[9] = "it";
			arr[10] = "late";
			arr[11] = "are";
			arr[12] = "after";
			arr[13] = "do";
			arr[14] = "the";
			arr[15] = "is";
			list.push(new Question("После этого все ушли.", "After that all gone", arr, "sound_9_16"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "is";
			arr[2] = "will";
			arr[3] = "was";
			arr[4] = "my";
			arr[5] = "be";
			arr[6] = "to";
			arr[7] = "try";
			arr[8] = "you";
			arr[9] = "it";
			arr[10] = "late";
			arr[11] = "are";
			arr[12] = "this";
			arr[13] = "do";
			arr[14] = "the";
			arr[15] = "first";
			list.push(new Question("Это моя первая попытка.", "This is my first try", arr, "sound_9_17"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "is";
			arr[2] = "will";
			arr[3] = "was";
			arr[4] = "my";
			arr[5] = "be";
			arr[6] = "to";
			arr[7] = "eat";
			arr[8] = "you";
			arr[9] = "it";
			arr[10] = "very";
			arr[11] = "are";
			arr[12] = "often";
			arr[13] = "do";
			arr[14] = "the";
			arr[15] = "first";
			list.push(new Question("Я ем очень часто.", "I eat very often", arr, "sound_9_18"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "is";
			arr[2] = "will";
			arr[3] = "gym";
			arr[4] = "goes";
			arr[5] = "be";
			arr[6] = "to";
			arr[7] = "go";
			arr[8] = "you";
			arr[9] = "it";
			arr[10] = "very";
			arr[11] = "are";
			arr[12] = "seldom";
			arr[13] = "do";
			arr[14] = "the";
			arr[15] = "she";
			list.push(new Question("Она редко ходит в спортзал.", "She seldom goes to the gym", arr, "sound_9_19"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "is";
			arr[2] = "will";
			arr[3] = "ends";
			arr[4] = "well";
			arr[5] = "be";
			arr[6] = "to";
			arr[7] = "go";
			arr[8] = "you";
			arr[9] = "it";
			arr[10] = "usually";
			arr[11] = "are";
			arr[12] = "all";
			arr[13] = "do";
			arr[14] = "the";
			arr[15] = "she";
			list.push(new Question("Обычно все заканчивается хорошо.", "Usually all ends well", arr, "sound_9_20"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "is";
			arr[2] = "will";
			arr[3] = "role";
			arr[4] = "this";
			arr[5] = "be";
			arr[6] = "to";
			arr[7] = "go";
			arr[8] = "you";
			arr[9] = "it";
			arr[10] = "play";
			arr[11] = "are";
			arr[12] = "all";
			arr[13] = "do";
			arr[14] = "the";
			arr[15] = "she";
			list.push(new Question("Я играю эту роль.", "I play this role", arr, "sound_9_21"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "is";
			arr[2] = "will";
			arr[3] = "won";
			arr[4] = "this";
			arr[5] = "be";
			arr[6] = "to";
			arr[7] = "go";
			arr[8] = "you";
			arr[9] = "it";
			arr[10] = "win";
			arr[11] = "are";
			arr[12] = "all";
			arr[13] = "do";
			arr[14] = "the";
			arr[15] = "she";
			list.push(new Question("Я выиграл.", "I won", arr, "sound_9_22"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "is";
			arr[2] = "will";
			arr[3] = "won";
			arr[4] = "this";
			arr[5] = "be";
			arr[6] = "to";
			arr[7] = "go";
			arr[8] = "you";
			arr[9] = "it";
			arr[10] = "win";
			arr[11] = "are";
			arr[12] = "game";
			arr[13] = "do";
			arr[14] = "the";
			arr[15] = "she";
			list.push(new Question("Я выиграю эту игру.", "I will win this game", arr, "sound_9_23"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "is";
			arr[2] = "will";
			arr[3] = "won";
			arr[4] = "this";
			arr[5] = "be";
			arr[6] = "to";
			arr[7] = "go";
			arr[8] = "you";
			arr[9] = "it";
			arr[10] = "win";
			arr[11] = "are";
			arr[12] = "lose";
			arr[13] = "do";
			arr[14] = "the";
			arr[15] = "me";
			list.push(new Question("Ты проиграешь мне.", "You will lose me", arr, "sound_9_24"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "is";
			arr[2] = "will";
			arr[3] = "won";
			arr[4] = "this";
			arr[5] = "be";
			arr[6] = "to";
			arr[7] = "go";
			arr[8] = "you";
			arr[9] = "it";
			arr[10] = "win";
			arr[11] = "are";
			arr[12] = "lose";
			arr[13] = "he";
			arr[14] = "the";
			arr[15] = "lost";
			list.push(new Question("Он проиграл.", "He lost", arr, "sound_9_25"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "is";
			arr[2] = "will";
			arr[3] = "how";
			arr[4] = "this";
			arr[5] = "be";
			arr[6] = "to";
			arr[7] = "don't";
			arr[8] = "you";
			arr[9] = "it";
			arr[10] = "win";
			arr[11] = "are";
			arr[12] = "know";
			arr[13] = "he";
			arr[14] = "did";
			arr[15] = "lost";
			list.push(new Question("Я не понимаю, как ты сделал это.", "I don't know how you did it", arr, "sound_9_26"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "is";
			arr[2] = "will";
			arr[3] = "how";
			arr[4] = "this";
			arr[5] = "be";
			arr[6] = "to";
			arr[7] = "don't";
			arr[8] = "you";
			arr[9] = "it";
			arr[10] = "like";
			arr[11] = "are";
			arr[12] = "look";
			arr[13] = "he";
			arr[14] = "did";
			arr[15] = "him";
			list.push(new Question("Ты похожа на него.", "You look like him", arr, "sound_9_27"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "is";
			arr[2] = "will";
			arr[3] = "we";
			arr[4] = "this";
			arr[5] = "be";
			arr[6] = "to";
			arr[7] = "time";
			arr[8] = "you";
			arr[9] = "it";
			arr[10] = "spend";
			arr[11] = "are";
			arr[12] = "look";
			arr[13] = "he";
			arr[14] = "did";
			arr[15] = "together";
			list.push(new Question("Мы проведем время вместе.", "We will spend time together", arr, "sound_9_28"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "is";
			arr[2] = "will";
			arr[3] = "we";
			arr[4] = "this";
			arr[5] = "be";
			arr[6] = "met";
			arr[7] = "time";
			arr[8] = "you";
			arr[9] = "it";
			arr[10] = "never";
			arr[11] = "are";
			arr[12] = "look";
			arr[13] = "he";
			arr[14] = "did";
			arr[15] = "before";
			list.push(new Question("Мы раньше не встречались.", "We never met before", arr, "sound_9_29"));
			
			
		}
	}

}