package  
{
	import flash.display.Sprite;
	
	/**
	 * ...
	 * @author Vladimir
	 */
	public class PageLesson_4 extends Sprite 
	{
		private var stateManager:StateManager;
		private var list:Vector.<Question> = new Vector.<Question>(); // список вопросов
		
		public function PageLesson_4(manager:StateManager) 
		{
			stateManager = manager;
			
			Add_1();
			
			var a:Lesson = new Lesson(list, stateManager, 4);
			addChild(a);
			a.x = 40;
			a.y = 25;
			
			// добавляем к уроку конспект
			var wb:WorkBook = new WorkBook(new wb_4());
			a.AddWorkBook(wb);
			
			// добавляем к уроку словарь
			var dic:WorkBook = new WorkBook(new dic_4());
			a.AddDictionary(dic);
		}
		
		private function Add_1():void
		{
			var arr:Array = new Array(15);
			arr[0] = "I";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "to";
			arr[5] = "your";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "what";
			arr[9] = "as";
			arr[10] = "taxi";
			arr[11] = "is";
			arr[12] = "you";
			arr[13] = "a";
			arr[14] = "work";
			arr[15] = "when";
			list.push(new Question("Я работаю в такси.", "I work in a taxi", arr, "sound_4_1"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "to";
			arr[5] = "your";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "what";
			arr[9] = "as";
			arr[10] = "museum";
			arr[11] = "is";
			arr[12] = "you";
			arr[13] = "a";
			arr[14] = "work";
			arr[15] = "when";
			list.push(new Question("Я работаю в музее.", "I work in a museum", arr, "sound_4_2"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "to";
			arr[5] = "as";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "what";
			arr[9] = "are";
			arr[10] = "writer";
			arr[11] = "is";
			arr[12] = "you";
			arr[13] = "a";
			arr[14] = "work";
			arr[15] = "when";
			list.push(new Question("Я работаю писателем.", "I work as a writer", arr, "sound_4_3"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "to";
			arr[5] = "as";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "what";
			arr[9] = "are";
			arr[10] = "writer";
			arr[11] = "is";
			arr[12] = "you";
			arr[13] = "a";
			arr[14] = "work";
			arr[15] = "when";
			list.push(new Question("Я писатель.", "I am a writer", arr, "sound_4_4"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "to";
			arr[5] = "as";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "what";
			arr[9] = "are";
			arr[10] = "driver";
			arr[11] = "is";
			arr[12] = "you";
			arr[13] = "a";
			arr[14] = "work";
			arr[15] = "when";
			list.push(new Question("Я работаю водителем.", "I work as a driver", arr, "sound_4_5"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "to";
			arr[5] = "as";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "what";
			arr[9] = "are";
			arr[10] = "driver";
			arr[11] = "is";
			arr[12] = "you";
			arr[13] = "a";
			arr[14] = "work";
			arr[15] = "an";
			list.push(new Question("Я водитель.", "I am a driver", arr, "sound_4_6"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "to";
			arr[5] = "as";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "what";
			arr[9] = "are";
			arr[10] = "actor";
			arr[11] = "is";
			arr[12] = "you";
			arr[13] = "a";
			arr[14] = "work";
			arr[15] = "an";
			list.push(new Question("Я актер.", "I am an actor", arr, "sound_4_7"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "to";
			arr[5] = "as";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "what";
			arr[9] = "are";
			arr[10] = "actor";
			arr[11] = "is";
			arr[12] = "you";
			arr[13] = "a";
			arr[14] = "work";
			arr[15] = "an";
			list.push(new Question("Я работаю актером.", "I work as an actor", arr, "sound_4_8"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "to";
			arr[5] = "as";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "what";
			arr[9] = "are";
			arr[10] = "nice";
			arr[11] = "is";
			arr[12] = "you";
			arr[13] = "a";
			arr[14] = "meet";
			arr[15] = "an";
			list.push(new Question("Приятно познакомиться.", "Nice to meet you", arr, "sound_4_9"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "evening";
			arr[4] = "to";
			arr[5] = "night";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "afternoon";
			arr[9] = "are";
			arr[10] = "morning";
			arr[11] = "is";
			arr[12] = "you";
			arr[13] = "a";
			arr[14] = "good";
			arr[15] = "an";
			list.push(new Question("Доброе утро.", "Good morning", arr, "sound_4_10"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "evening";
			arr[4] = "to";
			arr[5] = "night";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "afternoon";
			arr[9] = "are";
			arr[10] = "morning";
			arr[11] = "is";
			arr[12] = "you";
			arr[13] = "a";
			arr[14] = "good";
			arr[15] = "an";
			list.push(new Question("Добрый день.", "Good afternoon", arr, "sound_4_11"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "evening";
			arr[4] = "to";
			arr[5] = "night";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "afternoon";
			arr[9] = "are";
			arr[10] = "morning";
			arr[11] = "is";
			arr[12] = "you";
			arr[13] = "a";
			arr[14] = "good";
			arr[15] = "an";
			list.push(new Question("Добрый вечер.", "Good evening", arr, "sound_4_12"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "evening";
			arr[4] = "to";
			arr[5] = "night";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "afternoon";
			arr[9] = "are";
			arr[10] = "morning";
			arr[11] = "is";
			arr[12] = "you";
			arr[13] = "a";
			arr[14] = "good";
			arr[15] = "an";
			list.push(new Question("Спокойной ночи.", "Good night", arr, "sound_4_13"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "evening";
			arr[4] = "to";
			arr[5] = "night";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "sorry";
			arr[9] = "are";
			arr[10] = "morning";
			arr[11] = "is";
			arr[12] = "you";
			arr[13] = "a";
			arr[14] = "good";
			arr[15] = "an";
			list.push(new Question("Приношу извинения.", "I am sorry", arr, "sound_4_14"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "evening";
			arr[4] = "to";
			arr[5] = "night";
			arr[6] = "he";
			arr[7] = "be";
			arr[8] = "sorry";
			arr[9] = "are";
			arr[10] = "doctor";
			arr[11] = "is";
			arr[12] = "you";
			arr[13] = "a";
			arr[14] = "good";
			arr[15] = "an";
			list.push(new Question("Ты будешь врачом.", "You will be a doctor", arr, "sound_4_15"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "wanted";
			arr[4] = "to";
			arr[5] = "become";
			arr[6] = "he";
			arr[7] = "be";
			arr[8] = "sorry";
			arr[9] = "are";
			arr[10] = "scientist";
			arr[11] = "is";
			arr[12] = "you";
			arr[13] = "a";
			arr[14] = "good";
			arr[15] = "an";
			list.push(new Question("Я хотел стать ученым.", "I wanted to become a scientist", arr, "sound_4_16"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "work";
			arr[4] = "to";
			arr[5] = "as";
			arr[6] = "he";
			arr[7] = "be";
			arr[8] = "sorry";
			arr[9] = "are";
			arr[10] = "businessman";
			arr[11] = "is";
			arr[12] = "you";
			arr[13] = "a";
			arr[14] = "do";
			arr[15] = "an";
			list.push(new Question("Ты работаешь бизнесменом?", "Do you work as a businessman", arr, "sound_4_17"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "work";
			arr[4] = "to";
			arr[5] = "as";
			arr[6] = "want";
			arr[7] = "be";
			arr[8] = "didn't";
			arr[9] = "are";
			arr[10] = "shop-assistant";
			arr[11] = "is";
			arr[12] = "you";
			arr[13] = "a";
			arr[14] = "do";
			arr[15] = "an";
			list.push(new Question("Я не хотел работать продавцом.", "I didn't want to work as a shop-assistant", arr, "sound_4_18"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "am";
			arr[2] = "won't";
			arr[3] = "work";
			arr[4] = "to";
			arr[5] = "as";
			arr[6] = "want";
			arr[7] = "be";
			arr[8] = "didn't";
			arr[9] = "are";
			arr[10] = "dentist";
			arr[11] = "is";
			arr[12] = "you";
			arr[13] = "a";
			arr[14] = "do";
			arr[15] = "an";
			list.push(new Question("Ты не будешь работать стоматологом?", "Won't you work as a dentist", arr, "sound_4_19"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "my";
			arr[2] = "brother";
			arr[3] = "strong";
			arr[4] = "and";
			arr[5] = "as";
			arr[6] = "he";
			arr[7] = "is";
			arr[8] = "didn't";
			arr[9] = "are";
			arr[10] = "bodyguard";
			arr[11] = "is";
			arr[12] = "you";
			arr[13] = "a";
			arr[14] = "do";
			arr[15] = "an";
			list.push(new Question("Мой брат сильный и он телохранитель.", "My brother is strong and he is a bodyguard", arr, "sound_4_20"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "am";
			arr[2] = "won't";
			arr[3] = "work";
			arr[4] = "to";
			arr[5] = "as";
			arr[6] = "want";
			arr[7] = "be";
			arr[8] = "did";
			arr[9] = "are";
			arr[10] = "photographer";
			arr[11] = "is";
			arr[12] = "you";
			arr[13] = "a";
			arr[14] = "do";
			arr[15] = "an";
			list.push(new Question("Ты работал фотографом?", "Did you work as a photographer", arr, "sound_4_21"));
			
			arr = new Array(15);
			arr[0] = "my";
			arr[1] = "am";
			arr[2] = "parents";
			arr[3] = "work";
			arr[4] = "are";
			arr[5] = "as";
			arr[6] = "teachers";
			arr[7] = "be";
			arr[8] = "the";
			arr[9] = "and";
			arr[10] = "photographer";
			arr[11] = "in";
			arr[12] = "you";
			arr[13] = "a";
			arr[14] = "school";
			arr[15] = "an";
			list.push(new Question("Мои родители - учителя работают в школе.", "My parents are teachers and work in the school", arr, "sound_4_22"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "am";
			arr[2] = "don't";
			arr[3] = "work";
			arr[4] = "to";
			arr[5] = "as";
			arr[6] = "want";
			arr[7] = "be";
			arr[8] = "did";
			arr[9] = "are";
			arr[10] = "cleaner";
			arr[11] = "is";
			arr[12] = "you";
			arr[13] = "a";
			arr[14] = "do";
			arr[15] = "an";
			list.push(new Question("Я не работаю уборщицей.", "I don't work as a cleaner", arr, "sound_4_23"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "am";
			arr[2] = "she";
			arr[3] = "work";
			arr[4] = "to";
			arr[5] = "as";
			arr[6] = "secretary";
			arr[7] = "be";
			arr[8] = "did";
			arr[9] = "are";
			arr[10] = "nurse";
			arr[11] = "is";
			arr[12] = "you";
			arr[13] = "a";
			arr[14] = "or";
			arr[15] = "an";
			list.push(new Question("Она секретарь или няня?", "Is she secretary or a nurse", arr, "sound_4_24"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "my";
			arr[2] = "uncle";
			arr[3] = "work";
			arr[4] = "to";
			arr[5] = "as";
			arr[6] = "producer";
			arr[7] = "be";
			arr[8] = "did";
			arr[9] = "are";
			arr[10] = "very";
			arr[11] = "is";
			arr[12] = "you";
			arr[13] = "a";
			arr[14] = "good";
			arr[15] = "an";
			list.push(new Question("Мой дядя очень хороший продюсер.", "My uncle is a very good producer", arr, "sound_4_25"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "will";
			arr[2] = "uncle";
			arr[3] = "work";
			arr[4] = "to";
			arr[5] = "as";
			arr[6] = "policeman";
			arr[7] = "be";
			arr[8] = "did";
			arr[9] = "are";
			arr[10] = "very";
			arr[11] = "is";
			arr[12] = "you";
			arr[13] = "a";
			arr[14] = "good";
			arr[15] = "an";
			list.push(new Question("Ты будешь полицейским?", "Will you be a policeman", arr, "sound_4_26"));
			
			arr = new Array(15);
			arr[0] = "my";
			arr[1] = "will";
			arr[2] = "uncle";
			arr[3] = "works";
			arr[4] = "to";
			arr[5] = "interpreter";
			arr[6] = "friend";
			arr[7] = "be";
			arr[8] = "did";
			arr[9] = "as";
			arr[10] = "very";
			arr[11] = "is";
			arr[12] = "you";
			arr[13] = "a";
			arr[14] = "best";
			arr[15] = "an";
			list.push(new Question("Мой лучший друг работает переводчиком.", "My best friend works as an interpreter", arr, "sound_4_27"));
			
			arr = new Array(15);
			arr[0] = "my";
			arr[1] = "will";
			arr[2] = "does";
			arr[3] = "works";
			arr[4] = "to";
			arr[5] = "mother";
			arr[6] = "waiter";
			arr[7] = "be";
			arr[8] = "bar";
			arr[9] = "as";
			arr[10] = "in";
			arr[11] = "is";
			arr[12] = "you";
			arr[13] = "a";
			arr[14] = "the";
			arr[15] = "an";
			list.push(new Question("Моя мама работает официантом в баре?", "Does my mother works as a waiter in the bar", arr, "sound_4_28"));
			
			arr = new Array(15);
			arr[0] = "my";
			arr[1] = "will";
			arr[2] = "Russia";
			arr[3] = "in";
			arr[4] = "to";
			arr[5] = "Kirkorov";
			arr[6] = "friend";
			arr[7] = "be";
			arr[8] = "the";
			arr[9] = "as";
			arr[10] = "singer";
			arr[11] = "is";
			arr[12] = "you";
			arr[13] = "a";
			arr[14] = "best";
			arr[15] = "an";
			list.push(new Question("Киркоров - лучший певец в России.", "Kirkorov is the best singer in Russia", arr, "sound_4_29"));
			
			arr = new Array(15);
			arr[0] = "my";
			arr[1] = "will";
			arr[2] = "baker";
			arr[3] = "in";
			arr[4] = "to";
			arr[5] = "this";
			arr[6] = "friend";
			arr[7] = "be";
			arr[8] = "the";
			arr[9] = "as";
			arr[10] = "super";
			arr[11] = "is";
			arr[12] = "you";
			arr[13] = "a";
			arr[14] = "best";
			arr[15] = "an";
			list.push(new Question("Этот пекарь просто супер.", "This baker is super", arr, "sound_4_30"));
			
			arr = new Array(15);
			arr[0] = "my";
			arr[1] = "will";
			arr[2] = "brings";
			arr[3] = "in";
			arr[4] = "to";
			arr[5] = "day";
			arr[6] = "postman";
			arr[7] = "be";
			arr[8] = "the";
			arr[9] = "as";
			arr[10] = "letters";
			arr[11] = "is";
			arr[12] = "you";
			arr[13] = "a";
			arr[14] = "every";
			arr[15] = "an";
			list.push(new Question("Почтальон приносит письма каждый день.", "Postman brings letters every day", arr, "sound_4_31"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "went";
			arr[2] = "year";
			arr[3] = "in";
			arr[4] = "to";
			arr[5] = "day";
			arr[6] = "last";
			arr[7] = "to";
			arr[8] = "the";
			arr[9] = "as";
			arr[10] = "oculist";
			arr[11] = "is";
			arr[12] = "you";
			arr[13] = "a";
			arr[14] = "every";
			arr[15] = "an";
			list.push(new Question("В прошлом году я ходил к окулисту.", "Last year I went to the oculist", arr, "sound_4_32"));
			
			arr = new Array(15);
			arr[0] = "my";
			arr[1] = "brother";
			arr[2] = "always";
			arr[3] = "in";
			arr[4] = "to";
			arr[5] = "wanted";
			arr[6] = "last";
			arr[7] = "to";
			arr[8] = "the";
			arr[9] = "as";
			arr[10] = "builder";
			arr[11] = "is";
			arr[12] = "you";
			arr[13] = "a";
			arr[14] = "be";
			arr[15] = "an";
			list.push(new Question("Мой брат всегда хотел быть строителем.", "My brother always wanted to be a builder", arr, "sound_4_33"));
			
			arr = new Array(15);
			arr[0] = "my";
			arr[1] = "sister";
			arr[2] = "was";
			arr[3] = "in";
			arr[4] = "to";
			arr[5] = "not";
			arr[6] = "good";
			arr[7] = "to";
			arr[8] = "the";
			arr[9] = "as";
			arr[10] = "model";
			arr[11] = "is";
			arr[12] = "you";
			arr[13] = "a";
			arr[14] = "be";
			arr[15] = "an";
			list.push(new Question("Моя сестра не была хорошей моделью.", "My sister was not а good model", arr, "sound_4_34"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "future";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "to";
			arr[5] = "not";
			arr[6] = "good";
			arr[7] = "to";
			arr[8] = "the";
			arr[9] = "as";
			arr[10] = "designer";
			arr[11] = "is";
			arr[12] = "you";
			arr[13] = "a";
			arr[14] = "be";
			arr[15] = "an";
			list.push(new Question("В будущем я буду дизайнером.", "In future I will be a designer", arr, "sound_4_35"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "loader";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "to";
			arr[5] = "not";
			arr[6] = "hard";
			arr[7] = "to";
			arr[8] = "the";
			arr[9] = "as";
			arr[10] = "profession";
			arr[11] = "is";
			arr[12] = "you";
			arr[13] = "a";
			arr[14] = "be";
			arr[15] = "an";
			list.push(new Question("Грузчик - тяжелая профессия.", "The loader is hard profession", arr, "sound_4_36"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "know";
			arr[2] = "do";
			arr[3] = "in";
			arr[4] = "to";
			arr[5] = "not";
			arr[6] = "many";
			arr[7] = "to";
			arr[8] = "good";
			arr[9] = "as";
			arr[10] = "artists";
			arr[11] = "is";
			arr[12] = "you";
			arr[13] = "a";
			arr[14] = "be";
			arr[15] = "an";
			list.push(new Question("Ты знаешь много хороших актеров?", "Do you know many good artists", arr, "sound_4_37"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "am";
			arr[2] = "do";
			arr[3] = "in";
			arr[4] = "to";
			arr[5] = "not";
			arr[6] = "did";
			arr[7] = "to";
			arr[8] = "good";
			arr[9] = "as";
			arr[10] = "driver";
			arr[11] = "is";
			arr[12] = "you";
			arr[13] = "a";
			arr[14] = "be";
			arr[15] = "an";
			list.push(new Question("Я не хороший водитель.", "I am not a good driver", arr, "sound_4_38"));
		}
		
	}

}