package  
{
	import flash.display.Sprite;
	
	/**
	 * ...
	 * @author Vladimir
	 */
	public class PageLesson_6 extends Sprite 
	{
		private var stateManager:StateManager;
		private var list:Vector.<Question> = new Vector.<Question>(); // список вопросов
		
		public function PageLesson_6(manager:StateManager) 
		{
			stateManager = manager;
			
			Add_1();
			
			
			var a:Lesson = new Lesson(list, stateManager, 6);
			addChild(a);
			a.x = 40;
			a.y = 25;
			
			// добавляем к уроку конспект
			var wb:WorkBook = new WorkBook(new wb_6());
			a.AddWorkBook(wb);
		}
		
		private function Add_1():void
		{
			var arr:Array = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "why";
			arr[4] = "she";
			arr[5] = "much";
			arr[6] = "many";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "have";
			arr[10] = "not";
			arr[11] = "time";
			arr[12] = "we";
			arr[13] = "does";
			arr[14] = "he";
			arr[15] = "they";
			list.push(new Question("У меня много времени.", "I have much time", arr, "sound_6_1"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "why";
			arr[4] = "she";
			arr[5] = "much";
			arr[6] = "many";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "have";
			arr[10] = "not";
			arr[11] = "money";
			arr[12] = "we";
			arr[13] = "does";
			arr[14] = "he";
			arr[15] = "has";
			list.push(new Question("У нее много денег.", "She has much money", arr, "sound_6_2"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "why";
			arr[4] = "she";
			arr[5] = "much";
			arr[6] = "many";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "have";
			arr[10] = "not";
			arr[11] = "friends";
			arr[12] = "we";
			arr[13] = "does";
			arr[14] = "he";
			arr[15] = "has";
			list.push(new Question("У меня много друзей.", "I have many friends", arr, "sound_6_3"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "why";
			arr[4] = "she";
			arr[5] = "much";
			arr[6] = "many";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "have";
			arr[10] = "not";
			arr[11] = "little";
			arr[12] = "we";
			arr[13] = "does";
			arr[14] = "time";
			arr[15] = "has";
			list.push(new Question("У меня мало времени.", "I have little time", arr, "sound_6_4"));
			
			arr = new Array(15);
			arr[0] = "he";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "days";
			arr[4] = "she";
			arr[5] = "much";
			arr[6] = "many";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "have";
			arr[10] = "a";
			arr[11] = "few";
			arr[12] = "we";
			arr[13] = "does";
			arr[14] = "time";
			arr[15] = "has";
			list.push(new Question("У него осталось мало дней.", "He has a few days", arr, "sound_6_5"));
			
			arr = new Array(15);
			arr[0] = "he";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "rest";
			arr[4] = "she";
			arr[5] = "much";
			arr[6] = "many";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "have";
			arr[10] = "a";
			arr[11] = "I";
			arr[12] = "we";
			arr[13] = "good";
			arr[14] = "had";
			arr[15] = "has";
			list.push(new Question("Я хорошо отдохнул.", "I had good rest", arr, "sound_6_6"));
			
			arr = new Array(15);
			arr[0] = "he";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "time";
			arr[4] = "she";
			arr[5] = "much";
			arr[6] = "many";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "have";
			arr[10] = "a";
			arr[11] = "few";
			arr[12] = "we";
			arr[13] = "good";
			arr[14] = "had";
			arr[15] = "has";
			list.push(new Question("У нее есть время.", "She has time", arr, "sound_6_7"));
			
			arr = new Array(15);
			arr[0] = "he";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "it";
			arr[4] = "she";
			arr[5] = "much";
			arr[6] = "many";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "have";
			arr[10] = "a";
			arr[11] = "knows";
			arr[12] = "we";
			arr[13] = "everybody";
			arr[14] = "had";
			arr[15] = "has";
			list.push(new Question("Все знаю это.", "Everybody knows it", arr, "sound_6_8"));
			
			arr = new Array(15);
			arr[0] = "he";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "it";
			arr[4] = "she";
			arr[5] = "much";
			arr[6] = "many";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "have";
			arr[10] = "a";
			arr[11] = "knows";
			arr[12] = "we";
			arr[13] = "everybody";
			arr[14] = "had";
			arr[15] = "has";
			list.push(new Question("Он знает всех.", "He knows everybody", arr, "sound_6_9"));
			
			arr = new Array(15);
			arr[0] = "he";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "it";
			arr[4] = "she";
			arr[5] = "help";
			arr[6] = "many";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "have";
			arr[10] = "nobody";
			arr[11] = "knows";
			arr[12] = "we";
			arr[13] = "everybody";
			arr[14] = "had";
			arr[15] = "has";
			list.push(new Question("Никто не поможет тебе.", "Nobody will help you", arr, "sound_6_10"));
			
			arr = new Array(15);
			arr[0] = "he";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "it";
			arr[4] = "she";
			arr[5] = "help";
			arr[6] = "many";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "have";
			arr[10] = "nobody";
			arr[11] = "knows";
			arr[12] = "somebody";
			arr[13] = "everybody";
			arr[14] = "had";
			arr[15] = "has";
			list.push(new Question("Кто-нибудь тебе поможет.", "Somebody will help you", arr, "sound_6_11"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "about";
			arr[4] = "she";
			arr[5] = "help";
			arr[6] = "many";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "everything";
			arr[10] = "nobody";
			arr[11] = "knows";
			arr[12] = "somebody";
			arr[13] = "everybody";
			arr[14] = "had";
			arr[15] = "know";
			list.push(new Question("Я знаю все о тебе.", "I know everything about you", arr, "sound_6_12"));
			
			arr = new Array(15);
			arr[0] = "he";
			arr[1] = "I";
			arr[2] = "will";
			arr[3] = "about";
			arr[4] = "she";
			arr[5] = "help";
			arr[6] = "many";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "everything";
			arr[10] = "nobody";
			arr[11] = "know";
			arr[12] = "nothing";
			arr[13] = "everybody";
			arr[14] = "it";
			arr[15] = "know";
			list.push(new Question("Я ничего не знаю об этом.", "I know nothing about it", arr, "sound_6_13"));
			
			arr = new Array(15);
			arr[0] = "he";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "who";
			arr[4] = "she";
			arr[5] = "from";
			arr[6] = "many";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "everything";
			arr[10] = "nobody";
			arr[11] = "knows";
			arr[12] = "hide";
			arr[13] = "what";
			arr[14] = "it";
			arr[15] = "know";
			list.push(new Question("Что ты скрываешь от меня?", "What do you hide from me", arr, "sound_6_14"));
			
			arr = new Array(15);
			arr[0] = "he";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "who";
			arr[4] = "she";
			arr[5] = "to";
			arr[6] = "many";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "everything";
			arr[10] = "something";
			arr[11] = "give";
			arr[12] = "eat";
			arr[13] = "what";
			arr[14] = "it";
			arr[15] = "know";
			list.push(new Question("Дай мне что-нибудь поесть.", "Give me something to eat", arr, "sound_6_15"));
			
			arr = new Array(15);
			arr[0] = "he";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "who";
			arr[4] = "she";
			arr[5] = "to";
			arr[6] = "many";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "everything";
			arr[10] = "something";
			arr[11] = "give";
			arr[12] = "somewhere";
			arr[13] = "went";
			arr[14] = "it";
			arr[15] = "know";
			list.push(new Question("Он куда-то пошел.", "He went somewhere", arr, "sound_6_16"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "who";
			arr[4] = "she";
			arr[5] = "to";
			arr[6] = "many";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "everything";
			arr[10] = "something";
			arr[11] = "give";
			arr[12] = "somewhere";
			arr[13] = "never";
			arr[14] = "it";
			arr[15] = "know";
			list.push(new Question("Я никогда не делаю этого.", "I never do it", arr, "sound_6_17"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "who";
			arr[4] = "she";
			arr[5] = "to";
			arr[6] = "many";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "everything";
			arr[10] = "something";
			arr[11] = "give";
			arr[12] = "somewhere";
			arr[13] = "never";
			arr[14] = "it";
			arr[15] = "sometimes";
			list.push(new Question("Иногда я это делаю.", "Sometimes I do it", arr, "sound_6_18"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "he";
			arr[4] = "she";
			arr[5] = "to";
			arr[6] = "does";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "everything";
			arr[10] = "something";
			arr[11] = "always";
			arr[12] = "somewhere";
			arr[13] = "never";
			arr[14] = "it";
			arr[15] = "sometimes";
			list.push(new Question("Он всегда это делает.", "He always does it", arr, "sound_6_19"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "he";
			arr[4] = "she";
			arr[5] = "to";
			arr[6] = "does";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "love";
			arr[10] = "something";
			arr[11] = "so";
			arr[12] = "much";
			arr[13] = "never";
			arr[14] = "it";
			arr[15] = "many";
			list.push(new Question("Я так тебя люблю.", "I love you so much", arr, "sound_6_20"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "there";
			arr[5] = "to";
			arr[6] = "does";
			arr[7] = "room";
			arr[8] = "you";
			arr[9] = "were";
			arr[10] = "chairs";
			arr[11] = "so";
			arr[12] = "much";
			arr[13] = "the";
			arr[14] = "it";
			arr[15] = "many";
			list.push(new Question("В комнате было много стульев.", "There were many chairs in the room", arr, "sound_6_21"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "my";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "there";
			arr[5] = "lot";
			arr[6] = "does";
			arr[7] = "students";
			arr[8] = "you";
			arr[9] = "friends";
			arr[10] = "of";
			arr[11] = "a";
			arr[12] = "much";
			arr[13] = "the";
			arr[14] = "are";
			arr[15] = "many";
			list.push(new Question("Многие из моих друзей - студенты.", "A lot of my friends are students", arr, "sound_6_22"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "do";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "sugar";
			arr[5] = "lot";
			arr[6] = "drink";
			arr[7] = "tea";
			arr[8] = "you";
			arr[9] = "friends";
			arr[10] = "with";
			arr[11] = "a";
			arr[12] = "much";
			arr[13] = "the";
			arr[14] = "are";
			arr[15] = "many";
			list.push(new Question("Ты пьешь чай с большим количеством сахара?", "Do you drink tea with much sugar", arr, "sound_6_23"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "do";
			arr[2] = "did";
			arr[3] = "in";
			arr[4] = "he";
			arr[5] = "lot";
			arr[6] = "school";
			arr[7] = "tea";
			arr[8] = "you";
			arr[9] = "friends";
			arr[10] = "with";
			arr[11] = "have";
			arr[12] = "much";
			arr[13] = "the";
			arr[14] = "are";
			arr[15] = "many";
			list.push(new Question("У него в школе было много друзей?", "Did he have many friends in the school", arr, "sound_6_24"));
			
			arr = new Array(15);
			arr[0] = "it's";
			arr[1] = "do";
			arr[2] = "so";
			arr[3] = "in";
			arr[4] = "me";
			arr[5] = "lot";
			arr[6] = "coffee";
			arr[7] = "tea";
			arr[8] = "you";
			arr[9] = "for";
			arr[10] = "with";
			arr[11] = "a";
			arr[12] = "much";
			arr[13] = "the";
			arr[14] = "are";
			arr[15] = "many";
			list.push(new Question("Очень много кофе для меня.", "It's so much coffee for me", arr, "sound_6_25"));
			
			arr = new Array(15);
			arr[0] = "will";
			arr[1] = "gave";
			arr[2] = "so";
			arr[3] = "in";
			arr[4] = "me";
			arr[5] = "lot";
			arr[6] = "money";
			arr[7] = "tea";
			arr[8] = "you";
			arr[9] = "for";
			arr[10] = "with";
			arr[11] = "a";
			arr[12] = "much";
			arr[13] = "the";
			arr[14] = "month";
			arr[15] = "many";
			list.push(new Question("У тебя будет много денег через месяц?", "Will you gave much money in a month", arr, "sound_6_26"));
			
			arr = new Array(15);
			arr[0] = "do";
			arr[1] = "have";
			arr[2] = "city";
			arr[3] = "in";
			arr[4] = "of";
			arr[5] = "lot";
			arr[6] = "money";
			arr[7] = "tea";
			arr[8] = "you";
			arr[9] = "for";
			arr[10] = "museums";
			arr[11] = "a";
			arr[12] = "much";
			arr[13] = "the";
			arr[14] = "your";
			arr[15] = "many";
			list.push(new Question("У вас много музеев в городе?", "Do you have a lot of museums in your city", arr, "sound_6_27"));
			
			arr = new Array(15);
			arr[0] = "there";
			arr[1] = "are";
			arr[2] = "children";
			arr[3] = "in";
			arr[4] = "of";
			arr[5] = "lot";
			arr[6] = "money";
			arr[7] = "tea";
			arr[8] = "you";
			arr[9] = "for";
			arr[10] = "kindergarten";
			arr[11] = "a";
			arr[12] = "much";
			arr[13] = "the";
			arr[14] = "your";
			arr[15] = "many";
			list.push(new Question("В детском садике много детей.", "There are many children in the kindergarten", arr, "sound_6_28"));
			
			arr = new Array(15);
			arr[0] = "does";
			arr[1] = "she";
			arr[2] = "dresses";
			arr[3] = "in";
			arr[4] = "of";
			arr[5] = "lot";
			arr[6] = "money";
			arr[7] = "tea";
			arr[8] = "you";
			arr[9] = "for";
			arr[10] = "wear";
			arr[11] = "a";
			arr[12] = "much";
			arr[13] = "the";
			arr[14] = "your";
			arr[15] = "many";
			list.push(new Question("Она носит много платьев?", "Does she wear many dresses", arr, "sound_6_29"));
			
			arr = new Array(15);
			arr[0] = "them";
			arr[1] = "she";
			arr[2] = "weren't";
			arr[3] = "in";
			arr[4] = "of";
			arr[5] = "lot";
			arr[6] = "happy";
			arr[7] = "tea";
			arr[8] = "you";
			arr[9] = "for";
			arr[10] = "wear";
			arr[11] = "a";
			arr[12] = "much";
			arr[13] = "the";
			arr[14] = "your";
			arr[15] = "many";
			list.push(new Question("Многие из них не были счастливы.", "Many of them weren't happy", arr, "sound_6_30"));
			
			arr = new Array(15);
			arr[0] = "did";
			arr[1] = "he";
			arr[2] = "drink";
			arr[3] = "in";
			arr[4] = "of";
			arr[5] = "lot";
			arr[6] = "juice";
			arr[7] = "or";
			arr[8] = "you";
			arr[9] = "for";
			arr[10] = "milk";
			arr[11] = "a";
			arr[12] = "much";
			arr[13] = "the";
			arr[14] = "your";
			arr[15] = "many";
			list.push(new Question("Он пил много сока или молока?", "Did he drink much juice or milk", arr, "sound_6_31"));
			
			arr = new Array(15);
			arr[0] = "my";
			arr[1] = "words";
			arr[2] = "drink";
			arr[3] = "in";
			arr[4] = "of";
			arr[5] = "lot";
			arr[6] = "necessary";
			arr[7] = "or";
			arr[8] = "you";
			arr[9] = "for";
			arr[10] = "milk";
			arr[11] = "a";
			arr[12] = "much";
			arr[13] = "the";
			arr[14] = "are";
			arr[15] = "many";
			list.push(new Question("Многие мои слова полезны для тебя.", "A lot of my words are necessary for you", arr, "sound_6_32"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "wish";
			arr[2] = "drink";
			arr[3] = "in";
			arr[4] = "of";
			arr[5] = "lot";
			arr[6] = "happiness";
			arr[7] = "or";
			arr[8] = "you";
			arr[9] = "for";
			arr[10] = "milk";
			arr[11] = "a";
			arr[12] = "much";
			arr[13] = "the";
			arr[14] = "are";
			arr[15] = "many";
			list.push(new Question("Я желаю тебе много счастья.", "I wish you much happiness", arr, "sound_6_33"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "will";
			arr[2] = "have";
			arr[3] = "in";
			arr[4] = "of";
			arr[5] = "lot";
			arr[6] = "workers";
			arr[7] = "or";
			arr[8] = "you";
			arr[9] = "for";
			arr[10] = "your";
			arr[11] = "a";
			arr[12] = "much";
			arr[13] = "factory";
			arr[14] = "are";
			arr[15] = "many";
			list.push(new Question("У тебя будет много рабочих на фабрике?", "Will you have many workers in your factory", arr, "sound_6_34"));
			
		}
	}

}