package  
{
	import flash.display.Sprite;
	
	/**
	 * ...
	 * @author Vladimir
	 */
	public class PageLesson_14 extends Sprite 
	{
		private var stateManager:StateManager;
		private var list:Vector.<Question> = new Vector.<Question>(); // список вопросов
		
		public function PageLesson_14(manager:StateManager) 
		{
			stateManager = manager;
			
			Add_1();
			
			
			var a:Lesson = new Lesson(list, stateManager, 14);
			addChild(a);
			a.x = 40;
			a.y = 25;
		}
		
		private function Add_1():void 
		{
			var arr:Array = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "got";
			arr[4] = "kill";
			arr[5] = "any";
			arr[6] = "to";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "from";
			arr[10] = "not";
			arr[11] = "a";
			arr[12] = "we";
			arr[13] = "for";
			arr[14] = "he";
			arr[15] = "coll";
			list.push(new Question("Мне позвонили.", "I got a coll", arr, "sound_14_1"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "got";
			arr[2] = "will";
			arr[3] = "why";
			arr[4] = "she";
			arr[5] = "a";
			arr[6] = "to";
			arr[7] = "talk";
			arr[8] = "you";
			arr[9] = "call";
			arr[10] = "not";
			arr[11] = "to";
			arr[12] = "we";
			arr[13] = "on";
			arr[14] = "Oleg";
			arr[15] = "they";
			list.push(new Question("Мне позвонил Олег.", "I got a call to Oleg", arr, "sound_14_2"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "why";
			arr[4] = "she";
			arr[5] = "call";
			arr[6] = "to";
			arr[7] = "talk";
			arr[8] = "you";
			arr[9] = "the";
			arr[10] = "back";
			arr[11] = "them";
			arr[12] = "we";
			arr[13] = "on";
			arr[14] = "talked";
			arr[15] = "later";
			list.push(new Question("Я перезвоню позже.", "I will call back later", arr, "sound_14_3"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "the";
			arr[4] = "she";
			arr[5] = "a";
			arr[6] = "to";
			arr[7] = "talk";
			arr[8] = "you";
			arr[9] = "leave";
			arr[10] = "can";
			arr[11] = "them";
			arr[12] = "we";
			arr[13] = "on";
			arr[14] = "message";
			arr[15] = "they";
			list.push(new Question("Могу ли я оставить сообщение?", "Can I leave a message", arr, "sound_14_4"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "why";
			arr[4] = "you";
			arr[5] = "when";
			arr[6] = "to";
			arr[7] = "talk";
			arr[8] = "you";
			arr[9] = "the";
			arr[10] = "can";
			arr[11] = "them";
			arr[12] = "we";
			arr[13] = "on";
			arr[14] = "talked";
			arr[15] = "call";
			list.push(new Question("Когда я могу тебе позвонить?", "When can I call you", arr, "sound_14_5"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "didn't";
			arr[2] = "will";
			arr[3] = "he";
			arr[4] = "she";
			arr[5] = "yesterday";
			arr[6] = "to";
			arr[7] = "talk";
			arr[8] = "you";
			arr[9] = "the";
			arr[10] = "not";
			arr[11] = "call";
			arr[12] = "we";
			arr[13] = "on";
			arr[14] = "back";
			arr[15] = "they";
			list.push(new Question("Он не перезвонил.", "He didn't call back", arr, "sound_14_6"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "him";
			arr[2] = "will";
			arr[3] = "but";
			arr[4] = "she";
			arr[5] = "he";
			arr[6] = "to";
			arr[7] = "talk";
			arr[8] = "didn't";
			arr[9] = "the";
			arr[10] = "back";
			arr[11] = "them";
			arr[12] = "we";
			arr[13] = "called";
			arr[14] = "talked";
			arr[15] = "call";
			list.push(new Question("Я позвонил ему, но он не перезвонил.", "I called him but he didn't call back", arr, "sound_14_7"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "but";
			arr[2] = "a";
			arr[3] = "why";
			arr[4] = "leave";
			arr[5] = "yesterday";
			arr[6] = "didn't";
			arr[7] = "talk";
			arr[8] = "you";
			arr[9] = "the";
			arr[10] = "he";
			arr[11] = "message";
			arr[12] = "you";
			arr[13] = "called";
			arr[14] = "talked";
			arr[15] = "Oleg";
			list.push(new Question("Олег позвонил тебе, но он не оставил сообдения.", "Oleg called you but he didn't leave a message", arr, "sound_14_8"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "did";
			arr[3] = "why";
			arr[4] = "somebody";
			arr[5] = "yesterday";
			arr[6] = "to";
			arr[7] = "talk";
			arr[8] = "you";
			arr[9] = "the";
			arr[10] = "not";
			arr[11] = "call";
			arr[12] = "we";
			arr[13] = "on";
			arr[14] = "talked";
			arr[15] = "they";
			list.push(new Question("Кто-нибудь звонил мне?", "Did somebody call me", arr, "sound_14_9"));
			
			arr = new Array(15);
			arr[0] = "If";
			arr[1] = "somebody";
			arr[2] = "will";
			arr[3] = "calls";
			arr[4] = "me";
			arr[5] = "yesterday";
			arr[6] = "to";
			arr[7] = "talk";
			arr[8] = "take";
			arr[9] = "the";
			arr[10] = "a";
			arr[11] = "them";
			arr[12] = "we";
			arr[13] = "on";
			arr[14] = "message";
			arr[15] = "they";
			list.push(new Question("Если кто-нибудь позвонит мне, прими сообщение.", "If somebody calls me take a message", arr, "sound_14_10"));
			
			arr = new Array(15);
			arr[0] = "If";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "go";
			arr[4] = "she";
			arr[5] = "yesterday";
			arr[6] = "to";
			arr[7] = "take";
			arr[8] = "you";
			arr[9] = "the";
			arr[10] = "you";
			arr[11] = "them";
			arr[12] = "we";
			arr[13] = "on";
			arr[14] = "talked";
			arr[15] = "they";
			list.push(new Question("Если ты пойдешь, возьми меня с собой.", "If you go take me with you", arr, "sound_14_11"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "when";
			arr[3] = "why";
			arr[4] = "she";
			arr[5] = "yesterday";
			arr[6] = "go";
			arr[7] = "talk";
			arr[8] = "you";
			arr[9] = "the";
			arr[10] = "not";
			arr[11] = "away";
			arr[12] = "we";
			arr[13] = "will";
			arr[14] = "talked";
			arr[15] = "miss";
			list.push(new Question("Когда ты уйдешь, я буду скучать.", "When you go away I will miss", arr, "sound_14_12"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "if";
			arr[2] = "will";
			arr[3] = "away";
			arr[4] = "she";
			arr[5] = "yesterday";
			arr[6] = "go";
			arr[7] = "come";
			arr[8] = "you";
			arr[9] = "the";
			arr[10] = "not";
			arr[11] = "them";
			arr[12] = "we";
			arr[13] = "on";
			arr[14] = "miss";
			arr[15] = "cry";
			list.push(new Question("Если ты придешь, я буду плакать.", "If you come I will cry", arr, "sound_14_13"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "day";
			arr[2] = "will";
			arr[3] = "get";
			arr[4] = "every";
			arr[5] = "yesterday";
			arr[6] = "a";
			arr[7] = "talk";
			arr[8] = "call";
			arr[9] = "the";
			arr[10] = "from";
			arr[11] = "a";
			arr[12] = "we";
			arr[13] = "film";
			arr[14] = "director";
			arr[15] = "they";
			list.push(new Question("Каждый день мне звонит режисер.", "Every day I get a call from a film director", arr, "sound_14_14"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "why";
			arr[4] = "who";
			arr[5] = "sent";
			arr[6] = "to";
			arr[7] = "talk";
			arr[8] = "you";
			arr[9] = "the";
			arr[10] = "not";
			arr[11] = "them";
			arr[12] = "we";
			arr[13] = "this";
			arr[14] = "talked";
			arr[15] = "letter";
			list.push(new Question("Кто послал это письмо?", "Who sent this letter", arr, "sound_14_15"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "why";
			arr[4] = "she";
			arr[5] = "yesterday";
			arr[6] = "to";
			arr[7] = "who";
			arr[8] = "you";
			arr[9] = "the";
			arr[10] = "not";
			arr[11] = "them";
			arr[12] = "we";
			arr[13] = "on";
			arr[14] = "saw";
			arr[15] = "they";
			list.push(new Question("Кто видел тебя?", "Who saw you", arr, "sound_14_16"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "why";
			arr[4] = "she";
			arr[5] = "who";
			arr[6] = "to";
			arr[7] = "talk";
			arr[8] = "you";
			arr[9] = "the";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "on";
			arr[14] = "see";
			arr[15] = "they";
			list.push(new Question("Кого ты видел?", "Who did you see", arr, "sound_14_17"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "why";
			arr[4] = "she";
			arr[5] = "yesterday";
			arr[6] = "to";
			arr[7] = "what";
			arr[8] = "you";
			arr[9] = "when";
			arr[10] = "not";
			arr[11] = "them";
			arr[12] = "do";
			arr[13] = "did";
			arr[14] = "talked";
			arr[15] = "they";
			list.push(new Question("Что ты сделал?", "What did you do", arr, "sound_14_18"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "when";
			arr[4] = "she";
			arr[5] = "what";
			arr[6] = "to";
			arr[7] = "talk";
			arr[8] = "you";
			arr[9] = "the";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "hear";
			arr[14] = "listen";
			arr[15] = "they";
			list.push(new Question("Что ты слышал?", "What did you hear", arr, "sound_14_19"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "why";
			arr[4] = "she";
			arr[5] = "who";
			arr[6] = "to";
			arr[7] = "talk";
			arr[8] = "you";
			arr[9] = "heard";
			arr[10] = "hear";
			arr[11] = "them";
			arr[12] = "we";
			arr[13] = "about";
			arr[14] = "talked";
			arr[15] = "it";
			list.push(new Question("Кто слышал об этом?", "Who heard about it", arr, "sound_14_20"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "why";
			arr[4] = "who";
			arr[5] = "yesterday";
			arr[6] = "do";
			arr[7] = "talk";
			arr[8] = "you";
			arr[9] = "the";
			arr[10] = "not";
			arr[11] = "them";
			arr[12] = "we";
			arr[13] = "on";
			arr[14] = "love";
			arr[15] = "loves";
			list.push(new Question("Кого ты любишь?", "Who do you love", arr, "sound_14_21"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "who";
			arr[3] = "why";
			arr[4] = "she";
			arr[5] = "yesterday";
			arr[6] = "to";
			arr[7] = "talk";
			arr[8] = "you";
			arr[9] = "the";
			arr[10] = "not";
			arr[11] = "loves";
			arr[12] = "love";
			arr[13] = "on";
			arr[14] = "talked";
			arr[15] = "they";
			list.push(new Question("Кто любит тебя?", "Who loves you", arr, "sound_14_22"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "why";
			arr[4] = "she";
			arr[5] = "ask";
			arr[6] = "to";
			arr[7] = "question";
			arr[8] = "you";
			arr[9] = "the";
			arr[10] = "not";
			arr[11] = "me";
			arr[12] = "we";
			arr[13] = "on";
			arr[14] = "talked";
			arr[15] = "another";
			list.push(new Question("Спроси что-нибудь полегче.", "Ask me another", arr, "sound_14_23"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "why";
			arr[4] = "she";
			arr[5] = "who";
			arr[6] = "to";
			arr[7] = "talk";
			arr[8] = "you";
			arr[9] = "the";
			arr[10] = "wants";
			arr[11] = "them";
			arr[12] = "we";
			arr[13] = "on";
			arr[14] = "drink";
			arr[15] = "want";
			list.push(new Question("Кто хочет выпить?", "Who wants to drink", arr, "sound_14_24"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "why";
			arr[4] = "she";
			arr[5] = "what";
			arr[6] = "to";
			arr[7] = "talk";
			arr[8] = "you";
			arr[9] = "the";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "on";
			arr[14] = "see";
			arr[15] = "they";
			list.push(new Question("Что ты видел?", "What did you see", arr, "sound_14_25"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "why";
			arr[4] = "she";
			arr[5] = "who";
			arr[6] = "to";
			arr[7] = "talk";
			arr[8] = "you";
			arr[9] = "the";
			arr[10] = "not";
			arr[11] = "them";
			arr[12] = "saw";
			arr[13] = "on";
			arr[14] = "this";
			arr[15] = "they";
			list.push(new Question("Кто видел это?", "Who saw this", arr, "sound_14_26"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "why";
			arr[4] = "she";
			arr[5] = "who";
			arr[6] = "to";
			arr[7] = "talk";
			arr[8] = "you";
			arr[9] = "understand";
			arr[10] = "not";
			arr[11] = "understands";
			arr[12] = "we";
			arr[13] = "on";
			arr[14] = "talked";
			arr[15] = "they";
			list.push(new Question("Кто понимает тебя?", "Who understands you", arr, "sound_14_27"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "who";
			arr[3] = "why";
			arr[4] = "she";
			arr[5] = "do";
			arr[6] = "to";
			arr[7] = "talk";
			arr[8] = "you";
			arr[9] = "the";
			arr[10] = "understand";
			arr[11] = "them";
			arr[12] = "we";
			arr[13] = "understands";
			arr[14] = "talked";
			arr[15] = "they";
			list.push(new Question("Кого ты понимаешь?", "Who do you understand", arr, "sound_14_28"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "why";
			arr[4] = "she";
			arr[5] = "who";
			arr[6] = "to";
			arr[7] = "talk";
			arr[8] = "you";
			arr[9] = "the";
			arr[10] = "not";
			arr[11] = "was";
			arr[12] = "we";
			arr[13] = "here";
			arr[14] = "there";
			arr[15] = "they";
			list.push(new Question("Кто был здесь?", "Who was here", arr, "sound_14_29"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "who";
			arr[3] = "why";
			arr[4] = "she";
			arr[5] = "did";
			arr[6] = "to";
			arr[7] = "talk";
			arr[8] = "you";
			arr[9] = "the";
			arr[10] = "see";
			arr[11] = "them";
			arr[12] = "we";
			arr[13] = "on";
			arr[14] = "here";
			arr[15] = "there";
			list.push(new Question("Кого ты видел здесь?", "Who did you see here", arr, "sound_14_30"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "why";
			arr[4] = "she";
			arr[5] = "who";
			arr[6] = "to";
			arr[7] = "talk";
			arr[8] = "you";
			arr[9] = "the";
			arr[10] = "not";
			arr[11] = "sent";
			arr[12] = "we";
			arr[13] = "on";
			arr[14] = "here";
			arr[15] = "there";
			list.push(new Question("Кто послал тебя сюда?", "Who sent you here", arr, "sound_14_31"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "did";
			arr[2] = "will";
			arr[3] = "why";
			arr[4] = "she";
			arr[5] = "who";
			arr[6] = "to";
			arr[7] = "talk";
			arr[8] = "you";
			arr[9] = "send";
			arr[10] = "spent";
			arr[11] = "them";
			arr[12] = "we";
			arr[13] = "here";
			arr[14] = "there";
			arr[15] = "they";
			list.push(new Question("Кого ты послал туда?", "Who did you send there", arr, "sound_14_32"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "why";
			arr[4] = "she";
			arr[5] = "who";
			arr[6] = "to";
			arr[7] = "talk";
			arr[8] = "you";
			arr[9] = "the";
			arr[10] = "not";
			arr[11] = "called";
			arr[12] = "we";
			arr[13] = "on";
			arr[14] = "calle";
			arr[15] = "they";
			list.push(new Question("Кто звонил тебе?", "Who called you", arr, "sound_14_33"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "who";
			arr[2] = "will";
			arr[3] = "why";
			arr[4] = "she";
			arr[5] = "did";
			arr[6] = "to";
			arr[7] = "talk";
			arr[8] = "you";
			arr[9] = "the";
			arr[10] = "not";
			arr[11] = "call";
			arr[12] = "we";
			arr[13] = "on";
			arr[14] = "calls";
			arr[15] = "they";
			list.push(new Question("Кому ты звонил?", "Who did you call", arr, "sound_14_34"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "why";
			arr[4] = "she";
			arr[5] = "who";
			arr[6] = "to";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "the";
			arr[10] = "not";
			arr[11] = "them";
			arr[12] = "we";
			arr[13] = "call";
			arr[14] = "talked";
			arr[15] = "they";
			list.push(new Question("Кому ты звонишь?", "Who do you call", arr, "sound_14_35"));
			
		}
	}

}

