package  
{
	import flash.display.Sprite;
	
	/**
	 * ...
	 * @author Vladimir
	 */
	public class PageLesson_2 extends Sprite 
	{
		private var stateManager:StateManager;
		private var list:Vector.<Question> = new Vector.<Question>(); // список вопросов
		
		public function PageLesson_2(manager:StateManager) 
		{
			stateManager = manager;
			
			Add_1();
			Add_2();
			Add_3();
			Add_4();
			Add_5();
			Add_6();
			Add_7();
			
			
			var a:Lesson = new Lesson(list, stateManager, 2);
			addChild(a);
			a.x = 40;
			a.y = 25;
			
			// добавляем к уроку конспект
			var wb:WorkBook = new WorkBook(new wb_2());
			a.AddWorkBook(wb);
			
			// добавляем к уроку словарь
			var dic:WorkBook = new WorkBook(new dic_2());
			a.AddDictionary(dic);
		}
		
		// in, from, to
		private function Add_7():void
		{
			var arr:Array = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "did";
			arr[4] = "take";
			arr[5] = "did";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "do";
			arr[9] = "how";
			arr[10] = "him";
			arr[11] = "does";
			arr[12] = "you";
			arr[13] = "to";
			arr[14] = "why";
			arr[15] = "come";
			list.push(new Question("Я приду к тебе.", "I will come to you", arr, "sound_2_1"));
			
			arr = new Array(15);
			arr[0] = "when";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "did";
			arr[4] = "take";
			arr[5] = "did";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "do";
			arr[9] = "how";
			arr[10] = "him";
			arr[11] = "does";
			arr[12] = "you";
			arr[13] = "to";
			arr[14] = "why";
			arr[15] = "come";
			list.push(new Question("Когда ты придешь ко мне?", "When will you come to me", arr, "sound_2_2"));
			
			arr = new Array(15);
			arr[0] = "when";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "did";
			arr[4] = "take";
			arr[5] = "did";
			arr[6] = "he";
			arr[7] = "go";
			arr[8] = "do";
			arr[9] = "how";
			arr[10] = "from";
			arr[11] = "London";
			arr[12] = "you";
			arr[13] = "to";
			arr[14] = "why";
			arr[15] = "come";
			list.push(new Question("Когда ты поедешь в Лондон?", "When will you go to London", arr, "sound_2_3"));
			
			arr = new Array(15);
			arr[0] = "when";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "from";
			arr[4] = "take";
			arr[5] = "did";
			arr[6] = "he";
			arr[7] = "go";
			arr[8] = "do";
			arr[9] = "how";
			arr[10] = "come";
			arr[11] = "London";
			arr[12] = "you";
			arr[13] = "to";
			arr[14] = "why";
			arr[15] = "come";
			list.push(new Question("Когда ты приедишь из Лондона?", "When will you come from London", arr, "sound_2_4"));
			
			arr = new Array(15);
			arr[0] = "work";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "from";
			arr[4] = "I";
			arr[5] = "did";
			arr[6] = "he";
			arr[7] = "go";
			arr[8] = "live";
			arr[9] = "in";
			arr[10] = "come";
			arr[11] = "London";
			arr[12] = "you";
			arr[13] = "to";
			arr[14] = "and";
			arr[15] = "come";
			list.push(new Question("Я живу и работаю в Лондоне", "I live and work in London", arr, "sound_2_5"));
		}
		
		// разные вопросы
		private function Add_6():void
		{
			var arr:Array = new Array(15);
			arr[0] = "who";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "did";
			arr[4] = "take";
			arr[5] = "did";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "do";
			arr[9] = "how";
			arr[10] = "him";
			arr[11] = "does";
			arr[12] = "you";
			arr[13] = "when";
			arr[14] = "why";
			arr[15] = "what";
			list.push(new Question("Что ты взял?", "What did you take", arr, "sound_2_6"));
			
			arr = new Array(15);
			arr[0] = "who";
			arr[1] = "do";
			arr[2] = "will";
			arr[3] = "did";
			arr[4] = "think";
			arr[5] = "did";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "do";
			arr[9] = "how";
			arr[10] = "him";
			arr[11] = "so";
			arr[12] = "you";
			arr[13] = "when";
			arr[14] = "why";
			arr[15] = "what";
			list.push(new Question("Почему ты так думаешь?", "Why do you think so", arr, "sound_2_7"));
			
			arr = new Array(15);
			arr[0] = "who";
			arr[1] = "do";
			arr[2] = "will";
			arr[3] = "did";
			arr[4] = "problem";
			arr[5] = "did";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "do";
			arr[9] = "how";
			arr[10] = "him";
			arr[11] = "does";
			arr[12] = "you";
			arr[13] = "when";
			arr[14] = "have";
			arr[15] = "what";
			list.push(new Question("Какая у тебя проблема?", "What problem do you have", arr, "sound_2_8"));
			
			arr = new Array(15);
			arr[0] = "who";
			arr[1] = "do";
			arr[2] = "will";
			arr[3] = "did";
			arr[4] = "live";
			arr[5] = "did";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "do";
			arr[9] = "how";
			arr[10] = "him";
			arr[11] = "does";
			arr[12] = "you";
			arr[13] = "when";
			arr[14] = "where";
			arr[15] = "what";
			list.push(new Question("Где ты живешь?", "Where do you live", arr, "sound_2_9"));
			
			arr = new Array(15);
			arr[0] = "who";
			arr[1] = "do";
			arr[2] = "will";
			arr[3] = "did";
			arr[4] = "work";
			arr[5] = "did";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "do";
			arr[9] = "how";
			arr[10] = "him";
			arr[11] = "does";
			arr[12] = "you";
			arr[13] = "when";
			arr[14] = "where";
			arr[15] = "what";
			list.push(new Question("Где ты работаешь?", "Where do you work", arr, "sound_2_10"));
			
			arr = new Array(15);
			arr[0] = "who";
			arr[1] = "do";
			arr[2] = "will";
			arr[3] = "did";
			arr[4] = "go";
			arr[5] = "did";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "do";
			arr[9] = "how";
			arr[10] = "him";
			arr[11] = "does";
			arr[12] = "you";
			arr[13] = "when";
			arr[14] = "where";
			arr[15] = "what";
			list.push(new Question("Куда она пошла?", "Where did she go", arr, "sound_2_11"));
			
			arr = new Array(15);
			arr[0] = "who";
			arr[1] = "do";
			arr[2] = "will";
			arr[3] = "did";
			arr[4] = "go";
			arr[5] = "did";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "see";
			arr[9] = "how";
			arr[10] = "him";
			arr[11] = "does";
			arr[12] = "you";
			arr[13] = "when";
			arr[14] = "where";
			arr[15] = "what";
			list.push(new Question("Когда ты его увидишь?", "When will you see him", arr, "sound_2_12"));
			
			arr = new Array(15);
			arr[0] = "who";
			arr[1] = "do";
			arr[2] = "will";
			arr[3] = "did";
			arr[4] = "work";
			arr[5] = "did";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "see";
			arr[9] = "how";
			arr[10] = "him";
			arr[11] = "does";
			arr[12] = "you";
			arr[13] = "when";
			arr[14] = "where";
			arr[15] = "what";
			list.push(new Question("Как ты работаешь?", "How do you work", arr, "sound_2_13"));
			
			arr = new Array(15);
			arr[0] = "who";
			arr[1] = "do";
			arr[2] = "will";
			arr[3] = "did";
			arr[4] = "work";
			arr[5] = "did";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "see";
			arr[9] = "how";
			arr[10] = "him";
			arr[11] = "does";
			arr[12] = "you";
			arr[13] = "when";
			arr[14] = "where";
			arr[15] = "what";
			list.push(new Question("Как она работает?", "How does she work", arr, "sound_2_14"));
			
			arr = new Array(15);
			arr[0] = "who";
			arr[1] = "do";
			arr[2] = "will";
			arr[3] = "did";
			arr[4] = "travel";
			arr[5] = "did";
			arr[6] = "he";
			arr[7] = "travels";
			arr[8] = "see";
			arr[9] = "how";
			arr[10] = "him";
			arr[11] = "does";
			arr[12] = "you";
			arr[13] = "when";
			arr[14] = "where";
			arr[15] = "what";
			list.push(new Question("Где ты путешествовал?", "Where did you travel", arr, "sound_2_15"));
			
			arr = new Array(15);
			arr[0] = "who";
			arr[1] = "do";
			arr[2] = "will";
			arr[3] = "did";
			arr[4] = "travel";
			arr[5] = "did";
			arr[6] = "he";
			arr[7] = "travels";
			arr[8] = "see";
			arr[9] = "how";
			arr[10] = "him";
			arr[11] = "does";
			arr[12] = "you";
			arr[13] = "when";
			arr[14] = "where";
			arr[15] = "what";
			list.push(new Question("Когда ты будешь путешествовать?", "When will you travel", arr, "sound_2_16"));
			
			arr = new Array(15);
			arr[0] = "who";
			arr[1] = "do";
			arr[2] = "will";
			arr[3] = "did";
			arr[4] = "travel";
			arr[5] = "did";
			arr[6] = "he";
			arr[7] = "travels";
			arr[8] = "see";
			arr[9] = "how";
			arr[10] = "him";
			arr[11] = "does";
			arr[12] = "you";
			arr[13] = "when";
			arr[14] = "where";
			arr[15] = "they";
			list.push(new Question("Где они путешествуют?", "Where do they travel", arr, "sound_2_17"));
			
		}
		
		// allow
		private function Add_5():void
		{
			var arr:Array = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "allow";
			arr[4] = "him";
			arr[5] = "allowed";
			arr[6] = "us";
			arr[7] = "them";
			arr[8] = "you";
			arr[9] = "allows";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "he";
			arr[14] = "do";
			arr[15] = "her";
			list.push(new Question("Ты позволишь ему?", "Will you allow him", arr, "sound_2_18"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "allow";
			arr[4] = "him";
			arr[5] = "allowed";
			arr[6] = "us";
			arr[7] = "them";
			arr[8] = "you";
			arr[9] = "allows";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "he";
			arr[14] = "do";
			arr[15] = "she";
			list.push(new Question("Она позволит им.", "She will allow them", arr, "sound_2_19"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "allow";
			arr[4] = "him";
			arr[5] = "allowed";
			arr[6] = "us";
			arr[7] = "them";
			arr[8] = "you";
			arr[9] = "allows";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "he";
			arr[14] = "do";
			arr[15] = "she";
			list.push(new Question("Я не позволю тебе.", "I will not allow you", arr, "sound_2_20"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "allow";
			arr[4] = "him";
			arr[5] = "allowed";
			arr[6] = "us";
			arr[7] = "them";
			arr[8] = "you";
			arr[9] = "allows";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "he";
			arr[14] = "do";
			arr[15] = "she";
			list.push(new Question("Ты позволяешь мне?", "Do you allow me", arr, "sound_2_21"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "allow";
			arr[4] = "him";
			arr[5] = "allowed";
			arr[6] = "us";
			arr[7] = "them";
			arr[8] = "you";
			arr[9] = "allows";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "he";
			arr[14] = "do";
			arr[15] = "does";
			list.push(new Question("Он позволяет нам?", "Does he allow us", arr, "sound_2_22"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "allow";
			arr[4] = "him";
			arr[5] = "allowed";
			arr[6] = "us";
			arr[7] = "them";
			arr[8] = "you";
			arr[9] = "allows";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "he";
			arr[14] = "do";
			arr[15] = "does";
			list.push(new Question("Я позволяю им.", "I allow them", arr, "sound_2_23"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "allow";
			arr[4] = "him";
			arr[5] = "allowed";
			arr[6] = "us";
			arr[7] = "them";
			arr[8] = "you";
			arr[9] = "allows";
			arr[10] = "her";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "she";
			arr[14] = "do";
			arr[15] = "does";
			list.push(new Question("Она позволяет ей.", "She allows her", arr, "sound_2_24"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "allow";
			arr[4] = "him";
			arr[5] = "allowed";
			arr[6] = "us";
			arr[7] = "them";
			arr[8] = "you";
			arr[9] = "allows";
			arr[10] = "her";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "don't";
			arr[14] = "do";
			arr[15] = "does";
			list.push(new Question("Я не позволяю ей.", "I don't allow her", arr, "sound_2_25"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "allow";
			arr[4] = "him";
			arr[5] = "allowed";
			arr[6] = "he";
			arr[7] = "them";
			arr[8] = "you";
			arr[9] = "allows";
			arr[10] = "her";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "don't";
			arr[14] = "do";
			arr[15] = "doesn't";
			list.push(new Question("Он не позволяет мне.", "He doesn't allow me", arr, "sound_2_26"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "allow";
			arr[4] = "him";
			arr[5] = "allowed";
			arr[6] = "he";
			arr[7] = "them";
			arr[8] = "you";
			arr[9] = "allows";
			arr[10] = "her";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "don't";
			arr[14] = "do";
			arr[15] = "doesn't";
			list.push(new Question("Ты позволяешь ему?", "Do you allow him", arr, "sound_2_27"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "allow";
			arr[4] = "him";
			arr[5] = "allowed";
			arr[6] = "he";
			arr[7] = "them";
			arr[8] = "you";
			arr[9] = "allows";
			arr[10] = "her";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "don't";
			arr[14] = "do";
			arr[15] = "she";
			list.push(new Question("Она позволила ему.", "She allowed him", arr, "sound_2_28"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "allow";
			arr[4] = "him";
			arr[5] = "allowed";
			arr[6] = "he";
			arr[7] = "them";
			arr[8] = "you";
			arr[9] = "allows";
			arr[10] = "her";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "don't";
			arr[14] = "do";
			arr[15] = "didn't";
			list.push(new Question("Я не позволял им.", "I didn't allow them", arr, "sound_2_29"));
			
			// вопросительные
			arr = new Array(15);
			arr[0] = "who";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "allow";
			arr[4] = "him";
			arr[5] = "allowed";
			arr[6] = "he";
			arr[7] = "them";
			arr[8] = "you";
			arr[9] = "allows";
			arr[10] = "her";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "when";
			arr[14] = "why";
			arr[15] = "what";
			list.push(new Question("Когда ты позволишь мне?", "When will you allow me", arr, "sound_2_30"));
			
			arr = new Array(15);
			arr[0] = "who";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "allow";
			arr[4] = "him";
			arr[5] = "allowed";
			arr[6] = "he";
			arr[7] = "them";
			arr[8] = "you";
			arr[9] = "allows";
			arr[10] = "her";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "when";
			arr[14] = "why";
			arr[15] = "what";
			list.push(new Question("Зачем ты им позволил?", "Why did you allow them", arr, "sound_2_31"));
			
			arr = new Array(15);
			arr[0] = "who";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "allow";
			arr[4] = "him";
			arr[5] = "allowed";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "you";
			arr[9] = "allows";
			arr[10] = "her";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "when";
			arr[14] = "why";
			arr[15] = "what";
			list.push(new Question("Что она тебе позволит?", "What will she allow you", arr, "sound_2_32"));
			
			arr = new Array(15);
			arr[0] = "who";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "allow";
			arr[4] = "him";
			arr[5] = "allowed";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "you";
			arr[9] = "allows";
			arr[10] = "her";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "when";
			arr[14] = "why";
			arr[15] = "what";
			list.push(new Question("Кто тебе позволил?", "Who allowed you", arr, "sound_2_33"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "allow";
			arr[4] = "him";
			arr[5] = "allowed";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "was";
			arr[9] = "allows";
			arr[10] = "her";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "am";
			arr[14] = "why";
			arr[15] = "what";
			list.push(new Question("Почему мне позволили?", "Why am I allowed", arr, "sound_2_34"));
			
			arr = new Array(15);
			arr[0] = "who";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "allow";
			arr[4] = "him";
			arr[5] = "allowed";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "you";
			arr[9] = "allows";
			arr[10] = "her";
			arr[11] = "does";
			arr[12] = "we";
			arr[13] = "when";
			arr[14] = "why";
			arr[15] = "what";
			list.push(new Question("Что он позволяет?", "What does he allow", arr, "sound_2_35"));
			
			arr = new Array(15);
			arr[0] = "who";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "allow";
			arr[4] = "they";
			arr[5] = "allowed";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "do";
			arr[9] = "allows";
			arr[10] = "her";
			arr[11] = "does";
			arr[12] = "we";
			arr[13] = "when";
			arr[14] = "why";
			arr[15] = "what";
			list.push(new Question("Почему они позволяют ей?", "Why do they allow her", arr, "sound_2_36"));
			
			arr = new Array(15);
			arr[0] = "who";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "allow";
			arr[4] = "they";
			arr[5] = "did";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "do";
			arr[9] = "how";
			arr[10] = "her";
			arr[11] = "does";
			arr[12] = "you";
			arr[13] = "when";
			arr[14] = "why";
			arr[15] = "what";
			list.push(new Question("Каким образом она позволила тебе?", "How did she allow you", arr, "sound_2_37"));
			
		}
		
		// ask
		private function Add_4():void
		{
			var arr:Array = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "asked";
			arr[4] = "him";
			arr[5] = "ask";
			arr[6] = "us";
			arr[7] = "them";
			arr[8] = "you";
			arr[9] = "asks";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "he";
			arr[14] = "do";
			arr[15] = "her";
			list.push(new Question("Ты спросишь его?", "Will you ask him", arr, "sound_2_38"));
			
			arr = new Array(15);
			arr[0] = "they";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "asked";
			arr[4] = "him";
			arr[5] = "ask";
			arr[6] = "us";
			arr[7] = "them";
			arr[8] = "you";
			arr[9] = "asks";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "he";
			arr[14] = "do";
			arr[15] = "her";
			list.push(new Question("Они попросят тебя.", "They will ask you", arr, "sound_2_39"));
			
			arr = new Array(15);
			arr[0] = "they";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "asked";
			arr[4] = "him";
			arr[5] = "ask";
			arr[6] = "us";
			arr[7] = "them";
			arr[8] = "you";
			arr[9] = "asks";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "he";
			arr[14] = "do";
			arr[15] = "she";
			list.push(new Question("Она не спросит нас.", "She will not ask us", arr, "sound_2_40"));
			
			arr = new Array(15);
			arr[0] = "they";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "asked";
			arr[4] = "him";
			arr[5] = "ask";
			arr[6] = "us";
			arr[7] = "them";
			arr[8] = "you";
			arr[9] = "asks";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "he";
			arr[14] = "do";
			arr[15] = "she";
			list.push(new Question("Они меня спрашивают?", "Do they ask me", arr, "sound_2_41"));
			
			arr = new Array(15);
			arr[0] = "they";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "asked";
			arr[4] = "him";
			arr[5] = "ask";
			arr[6] = "us";
			arr[7] = "them";
			arr[8] = "you";
			arr[9] = "asks";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "does";
			arr[13] = "he";
			arr[14] = "do";
			arr[15] = "she";
			list.push(new Question("Она просит тебя?", "Does she ask you", arr, "sound_2_42"));
			
			arr = new Array(15);
			arr[0] = "they";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "asked";
			arr[4] = "him";
			arr[5] = "ask";
			arr[6] = "us";
			arr[7] = "them";
			arr[8] = "you";
			arr[9] = "asks";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "does";
			arr[13] = "he";
			arr[14] = "do";
			arr[15] = "I";
			list.push(new Question("Я прошу тебя.", "I ask you", arr, "sound_2_43"));
			
			arr = new Array(15);
			arr[0] = "they";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "asked";
			arr[4] = "him";
			arr[5] = "ask";
			arr[6] = "us";
			arr[7] = "them";
			arr[8] = "you";
			arr[9] = "asks";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "does";
			arr[13] = "he";
			arr[14] = "do";
			arr[15] = "I";
			list.push(new Question("Он спрашивает у меня.", "He asks me", arr, "sound_2_44"));
			
			arr = new Array(15);
			arr[0] = "they";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "asked";
			arr[4] = "him";
			arr[5] = "ask";
			arr[6] = "us";
			arr[7] = "them";
			arr[8] = "you";
			arr[9] = "asks";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "does";
			arr[13] = "he";
			arr[14] = "do";
			arr[15] = "I";
			list.push(new Question("Я не спрашиваю тебя.", "I do not ask you", arr, "sound_2_45"));
			
			arr = new Array(15);
			arr[0] = "they";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "asked";
			arr[4] = "him";
			arr[5] = "ask";
			arr[6] = "us";
			arr[7] = "them";
			arr[8] = "you";
			arr[9] = "asks";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "does";
			arr[13] = "he";
			arr[14] = "do";
			arr[15] = "her";
			list.push(new Question("Он не просит ее.", "He does not ask her", arr, "sound_2_46"));
			
			arr = new Array(15);
			arr[0] = "they";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "asked";
			arr[4] = "him";
			arr[5] = "ask";
			arr[6] = "she";
			arr[7] = "them";
			arr[8] = "you";
			arr[9] = "asks";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "does";
			arr[13] = "he";
			arr[14] = "do";
			arr[15] = "her";
			list.push(new Question("Она спрашивала его?", "Did she ask him", arr, "sound_2_47"));
			
			arr = new Array(15);
			arr[0] = "they";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "asked";
			arr[4] = "him";
			arr[5] = "ask";
			arr[6] = "she";
			arr[7] = "I";
			arr[8] = "you";
			arr[9] = "asks";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "does";
			arr[13] = "he";
			arr[14] = "do";
			arr[15] = "her";
			list.push(new Question("Я спрашивал тебя.", "I asked you", arr, "sound_2_48"));
			
			arr = new Array(15);
			arr[0] = "they";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "asked";
			arr[4] = "him";
			arr[5] = "ask";
			arr[6] = "she";
			arr[7] = "them";
			arr[8] = "you";
			arr[9] = "asks";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "does";
			arr[13] = "he";
			arr[14] = "do";
			arr[15] = "her";
			list.push(new Question("Он не спрашивал их.", "He did not ask them", arr, "sound_2_49"));
			
			// вопросы
			arr = new Array(15);
			arr[0] = "who";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "ask";
			arr[4] = "them";
			arr[5] = "did";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "do";
			arr[9] = "how";
			arr[10] = "her";
			arr[11] = "does";
			arr[12] = "you";
			arr[13] = "when";
			arr[14] = "why";
			arr[15] = "what";
			list.push(new Question("Что ты спрашивала их?", "What did you ask them", arr, "sound_2_50"));
			
			arr = new Array(15);
			arr[0] = "who";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "ask";
			arr[4] = "them";
			arr[5] = "did";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "do";
			arr[9] = "how";
			arr[10] = "her";
			arr[11] = "asked";
			arr[12] = "you";
			arr[13] = "when";
			arr[14] = "why";
			arr[15] = "what";
			list.push(new Question("Кто ее спрашивал?", "Who asked her", arr, "sound_2_51"));
			
			arr = new Array(15);
			arr[0] = "who";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "ask";
			arr[4] = "them";
			arr[5] = "did";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "do";
			arr[9] = "how";
			arr[10] = "her";
			arr[11] = "does";
			arr[12] = "you";
			arr[13] = "when";
			arr[14] = "why";
			arr[15] = "what";
			list.push(new Question("Когда ты спросил ее?", "When did you ask her", arr, "sound_2_52"));
			
			arr = new Array(15);
			arr[0] = "who";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "ask";
			arr[4] = "them";
			arr[5] = "did";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "asked";
			arr[9] = "how";
			arr[10] = "him";
			arr[11] = "was";
			arr[12] = "you";
			arr[13] = "when";
			arr[14] = "why";
			arr[15] = "what";
			list.push(new Question("Зачем его спрашивали?", "Why was he asked", arr, "sound_2_53"));
			
			arr = new Array(15);
			arr[0] = "who";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "ask";
			arr[4] = "I";
			arr[5] = "did";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "do";
			arr[9] = "how";
			arr[10] = "him";
			arr[11] = "does";
			arr[12] = "you";
			arr[13] = "when";
			arr[14] = "why";
			arr[15] = "what";
			list.push(new Question("Что мне спросить?", "What will I ask", arr, "sound_2_54"));
			
			arr = new Array(15);
			arr[0] = "who";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "ask";
			arr[4] = "them";
			arr[5] = "did";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "do";
			arr[9] = "how";
			arr[10] = "him";
			arr[11] = "does";
			arr[12] = "you";
			arr[13] = "when";
			arr[14] = "why";
			arr[15] = "what";
			list.push(new Question("Почему ты спрашиваешь меня?", "Why do you ask me", arr, "sound_2_55"));
			
		}
		
		// listen
		private function Add_3():void
		{
			var arr:Array = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "listens";
			arr[4] = "him";
			arr[5] = "listened";
			arr[6] = "us";
			arr[7] = "them";
			arr[8] = "you";
			arr[9] = "listen";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "he";
			arr[14] = "to";
			arr[15] = "her";
			list.push(new Question("Ты будешь слушать меня?", "Will you listen to me", arr, "sound_2_56"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "listens";
			arr[4] = "him";
			arr[5] = "listened";
			arr[6] = "us";
			arr[7] = "them";
			arr[8] = "you";
			arr[9] = "listen";
			arr[10] = "not";
			arr[11] = "to";
			arr[12] = "we";
			arr[13] = "he";
			arr[14] = "she";
			arr[15] = "her";
			list.push(new Question("Она будет тебя слушать.", "She will listen to you", arr, "sound_2_57"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "listens";
			arr[4] = "him";
			arr[5] = "listened";
			arr[6] = "to";
			arr[7] = "them";
			arr[8] = "you";
			arr[9] = "listen";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "he";
			arr[14] = "she";
			arr[15] = "her";
			list.push(new Question("Мы не будем слушать ее.", "We will not listen to her", arr, "sound_2_58"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "listens";
			arr[4] = "him";
			arr[5] = "listened";
			arr[6] = "us";
			arr[7] = "to";
			arr[8] = "you";
			arr[9] = "listen";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "he";
			arr[14] = "she";
			arr[15] = "do";
			list.push(new Question("Ты слушаешь меня?", "Do you listen to me", arr, "sound_2_59"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "listens";
			arr[4] = "him";
			arr[5] = "listened";
			arr[6] = "to";
			arr[7] = "them";
			arr[8] = "you";
			arr[9] = "listen";
			arr[10] = "not";
			arr[11] = "does";
			arr[12] = "we";
			arr[13] = "he";
			arr[14] = "she";
			arr[15] = "do";
			list.push(new Question("Он слушает тебя?", "Does he listen to you", arr, "sound_2_60"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "listens";
			arr[4] = "him";
			arr[5] = "listened";
			arr[6] = "us";
			arr[7] = "to";
			arr[8] = "you";
			arr[9] = "listen";
			arr[10] = "not";
			arr[11] = "does";
			arr[12] = "we";
			arr[13] = "he";
			arr[14] = "she";
			arr[15] = "do";
			list.push(new Question("Я тебя слушаю.", "I listen to you", arr, "sound_2_61"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "listens";
			arr[4] = "him";
			arr[5] = "listened";
			arr[6] = "us";
			arr[7] = "to";
			arr[8] = "you";
			arr[9] = "listen";
			arr[10] = "not";
			arr[11] = "does";
			arr[12] = "we";
			arr[13] = "he";
			arr[14] = "she";
			arr[15] = "do";
			list.push(new Question("Она слушает нас.", "She listens to us", arr, "sound_2_62"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "listens";
			arr[4] = "him";
			arr[5] = "listened";
			arr[6] = "us";
			arr[7] = "to";
			arr[8] = "you";
			arr[9] = "listen";
			arr[10] = "not";
			arr[11] = "does";
			arr[12] = "we";
			arr[13] = "he";
			arr[14] = "she";
			arr[15] = "do";
			list.push(new Question("Ты меня не слушаешь.", "You do not listen to me", arr, "sound_2_63"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "listens";
			arr[4] = "him";
			arr[5] = "listened";
			arr[6] = "us";
			arr[7] = "her";
			arr[8] = "you";
			arr[9] = "listen";
			arr[10] = "not";
			arr[11] = "does";
			arr[12] = "we";
			arr[13] = "he";
			arr[14] = "she";
			arr[15] = "to";
			list.push(new Question("Он не слушает ее.", "He does not listen to her", arr, "sound_2_64"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "listens";
			arr[4] = "him";
			arr[5] = "listened";
			arr[6] = "us";
			arr[7] = "to";
			arr[8] = "you";
			arr[9] = "listen";
			arr[10] = "not";
			arr[11] = "does";
			arr[12] = "we";
			arr[13] = "he";
			arr[14] = "she";
			arr[15] = "did";
			list.push(new Question("Ты слушал меня?", "Did you listen to me", arr, "sound_2_65"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "listens";
			arr[4] = "him";
			arr[5] = "listened";
			arr[6] = "to";
			arr[7] = "her";
			arr[8] = "you";
			arr[9] = "listen";
			arr[10] = "not";
			arr[11] = "does";
			arr[12] = "we";
			arr[13] = "them";
			arr[14] = "she";
			arr[15] = "did";
			list.push(new Question("Она слушала их.", "She listened to them", arr, "sound_2_66"));
			
			arr = new Array(15);
			arr[0] = "to";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "listens";
			arr[4] = "him";
			arr[5] = "listened";
			arr[6] = "us";
			arr[7] = "her";
			arr[8] = "you";
			arr[9] = "listen";
			arr[10] = "not";
			arr[11] = "does";
			arr[12] = "we";
			arr[13] = "them";
			arr[14] = "he";
			arr[15] = "did";
			list.push(new Question("Он не слушал тебя.", "He did not listen to you", arr, "sound_2_67"));
		}
		
		// know
		private function Add_2():void
		{
			var arr:Array = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "knew";
			arr[4] = "him";
			arr[5] = "saw";
			arr[6] = "us";
			arr[7] = "them";
			arr[8] = "you";
			arr[9] = "recognize";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "he";
			arr[14] = "youre";
			arr[15] = "her";
			list.push(new Question("Ты узнаешь ее?", "Will you recognize her", arr, "sound_2_68"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "knew";
			arr[4] = "him";
			arr[5] = "saw";
			arr[6] = "us";
			arr[7] = "them";
			arr[8] = "you";
			arr[9] = "recognize";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "he";
			arr[14] = "youre";
			arr[15] = "her";
			list.push(new Question("Он узнает их.", "He will recognize them", arr, "sound_2_69"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "knew";
			arr[4] = "him";
			arr[5] = "do";
			arr[6] = "us";
			arr[7] = "them";
			arr[8] = "you";
			arr[9] = "recognize";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "he";
			arr[14] = "she";
			arr[15] = "her";
			list.push(new Question("Она не узнает его.", "She will not recognize him", arr, "sound_2_70"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "knew";
			arr[4] = "him";
			arr[5] = "do";
			arr[6] = "us";
			arr[7] = "them";
			arr[8] = "you";
			arr[9] = "know";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "he";
			arr[14] = "she";
			arr[15] = "they";
			list.push(new Question("Они знают меня?", "Do they know me", arr, "sound_2_71"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "knew";
			arr[4] = "him";
			arr[5] = "do";
			arr[6] = "us";
			arr[7] = "them";
			arr[8] = "you";
			arr[9] = "know";
			arr[10] = "not";
			arr[11] = "her";
			arr[12] = "we";
			arr[13] = "he";
			arr[14] = "she";
			arr[15] = "does";
			list.push(new Question("Он знает ее?", "Does he know her", arr, "sound_2_72"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "knew";
			arr[4] = "him";
			arr[5] = "do";
			arr[6] = "us";
			arr[7] = "them";
			arr[8] = "you";
			arr[9] = "know";
			arr[10] = "not";
			arr[11] = "her";
			arr[12] = "we";
			arr[13] = "he";
			arr[14] = "she";
			arr[15] = "does";
			list.push(new Question("Я знаю тебя.", "I know you", arr, "sound_2_73"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "knew";
			arr[4] = "him";
			arr[5] = "do";
			arr[6] = "us";
			arr[7] = "them";
			arr[8] = "you";
			arr[9] = "know";
			arr[10] = "not";
			arr[11] = "her";
			arr[12] = "we";
			arr[13] = "he";
			arr[14] = "she";
			arr[15] = "knows";
			list.push(new Question("Он знает его.", "He knows him", arr, "sound_2_74"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "knew";
			arr[4] = "him";
			arr[5] = "do";
			arr[6] = "us";
			arr[7] = "them";
			arr[8] = "you";
			arr[9] = "know";
			arr[10] = "not";
			arr[11] = "her";
			arr[12] = "we";
			arr[13] = "he";
			arr[14] = "she";
			arr[15] = "knows";
			list.push(new Question("Ты не знаешь ее.", "You do not know her", arr, "sound_2_75"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "knew";
			arr[4] = "him";
			arr[5] = "do";
			arr[6] = "us";
			arr[7] = "them";
			arr[8] = "you";
			arr[9] = "know";
			arr[10] = "doesn't";
			arr[11] = "her";
			arr[12] = "we";
			arr[13] = "he";
			arr[14] = "she";
			arr[15] = "knows";
			list.push(new Question("Она его не знает.", "She doesn't know him", arr, "sound_2_76"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "knew";
			arr[4] = "him";
			arr[5] = "did";
			arr[6] = "us";
			arr[7] = "them";
			arr[8] = "you";
			arr[9] = "know";
			arr[10] = "doesn't";
			arr[11] = "her";
			arr[12] = "we";
			arr[13] = "he";
			arr[14] = "she";
			arr[15] = "knows";
			list.push(new Question("Она знала их?", "Did she know them", arr, "sound_2_77"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "knew";
			arr[4] = "him";
			arr[5] = "did";
			arr[6] = "us";
			arr[7] = "them";
			arr[8] = "you";
			arr[9] = "know";
			arr[10] = "doesn't";
			arr[11] = "her";
			arr[12] = "we";
			arr[13] = "he";
			arr[14] = "she";
			arr[15] = "knows";
			list.push(new Question("Я знал его.", "I knew him", arr, "sound_2_78"));
			
			arr = new Array(15);
			arr[0] = "didn't";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "knew";
			arr[4] = "him";
			arr[5] = "do";
			arr[6] = "us";
			arr[7] = "them";
			arr[8] = "you";
			arr[9] = "know";
			arr[10] = "doesn't";
			arr[11] = "her";
			arr[12] = "we";
			arr[13] = "he";
			arr[14] = "she";
			arr[15] = "knows";
			list.push(new Question("Мы не знали ее.", "We didn't know her", arr, "sound_2_79"));
		}
		
		// see
		private function Add_1():void
		{
			var arr:Array = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "see";
			arr[4] = "him";
			arr[5] = "saw";
			arr[6] = "us";
			arr[7] = "them";
			arr[8] = "you";
			arr[9] = "builds";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "sees";
			arr[14] = "youre";
			arr[15] = "her";
			list.push(new Question("Ты увидишь меня?", "Will you see me", arr, "sound_2_80"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "see";
			arr[4] = "him";
			arr[5] = "saw";
			arr[6] = "us";
			arr[7] = "them";
			arr[8] = "you";
			arr[9] = "he";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "sees";
			arr[14] = "youre";
			arr[15] = "her";
			list.push(new Question("Он увидит нас.", "He will see us", arr, "sound_2_81"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "see";
			arr[4] = "him";
			arr[5] = "saw";
			arr[6] = "us";
			arr[7] = "them";
			arr[8] = "you";
			arr[9] = "he";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "sees";
			arr[14] = "youre";
			arr[15] = "her";
			list.push(new Question("Я не увижу ее.", "I will not see her", arr, "sound_2_82"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "see";
			arr[4] = "him";
			arr[5] = "saw";
			arr[6] = "us";
			arr[7] = "them";
			arr[8] = "you";
			arr[9] = "he";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "sees";
			arr[14] = "do";
			arr[15] = "her";
			list.push(new Question("Ты видишь нас?", "Do you see us", arr, "sound_2_83"));
			
			arr = new Array(15);
			arr[0] = "does";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "see";
			arr[4] = "him";
			arr[5] = "saw";
			arr[6] = "us";
			arr[7] = "them";
			arr[8] = "you";
			arr[9] = "he";
			arr[10] = "she";
			arr[11] = "did";
			arr[12] = "we";
			arr[13] = "sees";
			arr[14] = "do";
			arr[15] = "her";
			list.push(new Question("Она видит его?", "Does she see him", arr, "sound_2_84"));
			
			arr = new Array(15);
			arr[0] = "does";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "see";
			arr[4] = "him";
			arr[5] = "saw";
			arr[6] = "us";
			arr[7] = "them";
			arr[8] = "you";
			arr[9] = "he";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "they";
			arr[13] = "sees";
			arr[14] = "do";
			arr[15] = "her";
			list.push(new Question("Они видят его.", "They see him", arr, "sound_2_85"));
			
			arr = new Array(15);
			arr[0] = "does";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "see";
			arr[4] = "him";
			arr[5] = "saw";
			arr[6] = "us";
			arr[7] = "them";
			arr[8] = "you";
			arr[9] = "he";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "they";
			arr[13] = "sees";
			arr[14] = "do";
			arr[15] = "her";
			list.push(new Question("Он видит ее.", "He sees her", arr, "sound_2_86"));
			
			arr = new Array(15);
			arr[0] = "does";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "see";
			arr[4] = "him";
			arr[5] = "saw";
			arr[6] = "us";
			arr[7] = "them";
			arr[8] = "you";
			arr[9] = "he";
			arr[10] = "not";
			arr[11] = "did";
			arr[12] = "they";
			arr[13] = "sees";
			arr[14] = "do";
			arr[15] = "her";
			list.push(new Question("Они не видят меня.", "They do not see me", arr, "sound_2_87"));
			
			arr = new Array(15);
			arr[0] = "does";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "see";
			arr[4] = "him";
			arr[5] = "saw";
			arr[6] = "us";
			arr[7] = "them";
			arr[8] = "you";
			arr[9] = "he";
			arr[10] = "not";
			arr[11] = "she";
			arr[12] = "they";
			arr[13] = "sees";
			arr[14] = "do";
			arr[15] = "her";
			list.push(new Question("Она не видит их.", "She does not see them", arr, "sound_2_88"));
			
			arr = new Array(15);
			arr[0] = "does";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "see";
			arr[4] = "him";
			arr[5] = "saw";
			arr[6] = "us";
			arr[7] = "did";
			arr[8] = "you";
			arr[9] = "he";
			arr[10] = "not";
			arr[11] = "doesn't";
			arr[12] = "they";
			arr[13] = "sees";
			arr[14] = "do";
			arr[15] = "her";
			list.push(new Question("Ты видела нас?", "Did you see us", arr, "sound_2_89"));
			
			arr = new Array(15);
			arr[0] = "does";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "see";
			arr[4] = "him";
			arr[5] = "saw";
			arr[6] = "us";
			arr[7] = "them";
			arr[8] = "you";
			arr[9] = "he";
			arr[10] = "not";
			arr[11] = "is";
			arr[12] = "they";
			arr[13] = "sees";
			arr[14] = "do";
			arr[15] = "her";
			list.push(new Question("Они увидели его.", "They saw him", arr, "sound_2_90"));
			
			arr = new Array(15);
			arr[0] = "does";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "see";
			arr[4] = "him";
			arr[5] = "saw";
			arr[6] = "she";
			arr[7] = "didn't";
			arr[8] = "you";
			arr[9] = "he";
			arr[10] = "not";
			arr[11] = "is";
			arr[12] = "they";
			arr[13] = "sees";
			arr[14] = "do";
			arr[15] = "her";
			list.push(new Question("Она не увидела тебя.", "She didn't see you", arr, "sound_2_91"));
		}
		
	}

}