package  
{
	import flash.display.Sprite;
	
	/**
	 * ...
	 * @author Vladimir
	 */
	public class PageLesson_3 extends Sprite 
	{
		
		private var stateManager:StateManager;
		private var list:Vector.<Question> = new Vector.<Question>(); // список вопросов
		
		public function PageLesson_3(manager:StateManager) 
		{
			stateManager = manager;
			
			Add_1();
			Add_2();
			Add_3();
			Add_4();
			Add_5();
			Add_6();
			Add_7();
			
			var a:Lesson = new Lesson(list, stateManager, 3);
			addChild(a);
			a.x = 40;
			a.y = 25;
			
			// добавляем к уроку конспект
			var wb:WorkBook = new WorkBook(new wb_3());
			a.AddWorkBook(wb);
			
			// добавляем к уроку словарь
			var dic:WorkBook = new WorkBook(new dic_3());
			a.AddDictionary(dic);
		}
		
		// like
		private function Add_7():void
		{
			var arr:Array = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "he";
			arr[4] = "she";
			arr[5] = "to";
			arr[6] = "does";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "like";
			arr[10] = "exactly";
			arr[11] = "always";
			arr[12] = "looks";
			arr[13] = "never";
			arr[14] = "it";
			arr[15] = "Madonna";
			list.push(new Question("Она выглядит точно как Мадонна.", "She looks exactly like Madonna", arr, "sound_3_1"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "star";
			arr[4] = "she";
			arr[5] = "to";
			arr[6] = "a";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "like";
			arr[10] = "exactly";
			arr[11] = "always";
			arr[12] = "looks";
			arr[13] = "look";
			arr[14] = "it";
			arr[15] = "really";
			list.push(new Question("Ты действительно похожа на звезду.", "You really look like a star", arr, "sound_3_2"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "his";
			arr[4] = "she";
			arr[5] = "to";
			arr[6] = "he";
			arr[7] = "do";
			arr[8] = "you";
			arr[9] = "like";
			arr[10] = "tall";
			arr[11] = "always";
			arr[12] = "very";
			arr[13] = "look";
			arr[14] = "is";
			arr[15] = "brother";
			list.push(new Question("Как и его брат, он очень высокий.", "Like his brother he is very tall", arr, "sound_3_3"));
			
			arr = new Array(15);
			arr[0] = "at";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "his";
			arr[4] = "she";
			arr[5] = "to";
			arr[6] = "he";
			arr[7] = "don't";
			arr[8] = "you";
			arr[9] = "like";
			arr[10] = "tall";
			arr[11] = "mother";
			arr[12] = "very";
			arr[13] = "look";
			arr[14] = "is";
			arr[15] = "my";
			list.push(new Question("Не смотри на меня как моя мама.", "Don't look at me like my mother", arr, "sound_3_4"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "me";
			arr[2] = "will";
			arr[3] = "his";
			arr[4] = "she";
			arr[5] = "to";
			arr[6] = "he";
			arr[7] = "hate";
			arr[8] = "you";
			arr[9] = "like";
			arr[10] = "tall";
			arr[11] = "people";
			arr[12] = "rain";
			arr[13] = "look";
			arr[14] = "is";
			arr[15] = "many";
			list.push(new Question("Как и многие люди я терпеть не могу дождь.", "Like many people I hate rain", arr, "sound_3_5"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "my";
			arr[2] = "will";
			arr[3] = "his";
			arr[4] = "she";
			arr[5] = "to";
			arr[6] = "he";
			arr[7] = "hate";
			arr[8] = "you";
			arr[9] = "like";
			arr[10] = "juice";
			arr[11] = "son";
			arr[12] = "prefers";
			arr[13] = "look";
			arr[14] = "is";
			arr[15] = "me";
			list.push(new Question("Мой сын как и я предпочитает сок.", "My son is like me prefers juice", arr, "sound_3_6"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "my";
			arr[2] = "will";
			arr[3] = "not";
			arr[4] = "she";
			arr[5] = "to";
			arr[6] = "he";
			arr[7] = "hate";
			arr[8] = "you";
			arr[9] = "like";
			arr[10] = "pie";
			arr[11] = "a";
			arr[12] = "pizza";
			arr[13] = "look";
			arr[14] = "is";
			arr[15] = "me";
			list.push(new Question("Пицца не похожа на пирог.", "Pizza is not like a pie", arr, "sound_3_7"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "my";
			arr[2] = "will";
			arr[3] = "does";
			arr[4] = "she";
			arr[5] = "to";
			arr[6] = "her";
			arr[7] = "hate";
			arr[8] = "you";
			arr[9] = "like";
			arr[10] = "pie";
			arr[11] = "a";
			arr[12] = "talks";
			arr[13] = "brother";
			arr[14] = "is";
			arr[15] = "me";
			list.push(new Question("Она разговаривает как ее брат.", "She talks like her brother does", arr, "sound_3_8"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "my";
			arr[2] = "will";
			arr[3] = "does";
			arr[4] = "he";
			arr[5] = "to";
			arr[6] = "her";
			arr[7] = "father";
			arr[8] = "you";
			arr[9] = "like";
			arr[10] = "pie";
			arr[11] = "a";
			arr[12] = "looks";
			arr[13] = "brother";
			arr[14] = "is";
			arr[15] = "his";
			list.push(new Question("Он похож на своего папу.", "He looks like his father", arr, "sound_3_9"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "my";
			arr[2] = "will";
			arr[3] = "does";
			arr[4] = "he";
			arr[5] = "to";
			arr[6] = "her";
			arr[7] = "parents";
			arr[8] = "you";
			arr[9] = "like";
			arr[10] = "pie";
			arr[11] = "a";
			arr[12] = "looks";
			arr[13] = "love";
			arr[14] = "is";
			arr[15] = "me";
			list.push(new Question("Я люблю тебя также как и мои родители.", "I love you like my parents", arr, "sound_3_10"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "my";
			arr[2] = "will";
			arr[3] = "does";
			arr[4] = "he";
			arr[5] = "to";
			arr[6] = "her";
			arr[7] = "cinema";
			arr[8] = "you";
			arr[9] = "like";
			arr[10] = "went";
			arr[11] = "the";
			arr[12] = "looks";
			arr[13] = "classmates";
			arr[14] = "is";
			arr[15] = "me";
			list.push(new Question("Как и мои одноклассники,я пошел в кино.", "Like my classmates I went to the cinema", arr, "sound_3_11"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "my";
			arr[2] = "will";
			arr[3] = "not";
			arr[4] = "he";
			arr[5] = "to";
			arr[6] = "her";
			arr[7] = "mine";
			arr[8] = "your";
			arr[9] = "like";
			arr[10] = "went";
			arr[11] = "the";
			arr[12] = "looks";
			arr[13] = "business";
			arr[14] = "is";
			arr[15] = "me";
			list.push(new Question("Твой бизнес не такой как мой.", "Your business is not like mine", arr, "sound_3_12"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "my";
			arr[2] = "Samsung";
			arr[3] = "not";
			arr[4] = "he";
			arr[5] = "to";
			arr[6] = "also";
			arr[7] = "love";
			arr[8] = "your";
			arr[9] = "like";
			arr[10] = "LG";
			arr[11] = "the";
			arr[12] = "looks";
			arr[13] = "Nokia";
			arr[14] = "is";
			arr[15] = "and";
			list.push(new Question("Как Nokia и LG я также люблю Samsung.", "Like Nokia and LG I also love Samsung", arr, "sound_3_13"));
			
			arr = new Array(15);
			arr[0] = "my";
			arr[1] = "my";
			arr[2] = "husband";
			arr[3] = "not";
			arr[4] = "he";
			arr[5] = "to";
			arr[6] = "sailor";
			arr[7] = "love";
			arr[8] = "your";
			arr[9] = "like";
			arr[10] = "father";
			arr[11] = "the";
			arr[12] = "looks";
			arr[13] = "a";
			arr[14] = "is";
			arr[15] = "and";
			list.push(new Question("Мой муж как и мой отец - моряк.", "My husband is like my father a sailor", arr, "sound_3_14"));
			
			arr = new Array(15);
			arr[0] = "her";
			arr[1] = "my";
			arr[2] = "brother";
			arr[3] = "not";
			arr[4] = "he";
			arr[5] = "to";
			arr[6] = "beautiful";
			arr[7] = "love";
			arr[8] = "your";
			arr[9] = "like";
			arr[10] = "also";
			arr[11] = "the";
			arr[12] = "looks";
			arr[13] = "a";
			arr[14] = "is";
			arr[15] = "she";
			list.push(new Question("Как и ее брат, она тоже красивая.", "Like her brother she is also beautiful", arr, "sound_3_15"));
			
			arr = new Array(15);
			arr[0] = "her";
			arr[1] = "my";
			arr[2] = "many";
			arr[3] = "happy";
			arr[4] = "he";
			arr[5] = "to";
			arr[6] = "other";
			arr[7] = "love";
			arr[8] = "your";
			arr[9] = "like";
			arr[10] = "was";
			arr[11] = "the";
			arr[12] = "looks";
			arr[13] = "a";
			arr[14] = "is";
			arr[15] = "students";
			list.push(new Question("Как и многие другие студенты он был счастлив.", "Like many other students he was happy", arr, "sound_3_16"));
			
			arr = new Array(15);
			arr[0] = "her";
			arr[1] = "my";
			arr[2] = "many";
			arr[3] = "happy";
			arr[4] = "he";
			arr[5] = "to";
			arr[6] = "Father";
			arr[7] = "love";
			arr[8] = "your";
			arr[9] = "like";
			arr[10] = "was";
			arr[11] = "the";
			arr[12] = "looks";
			arr[13] = "a";
			arr[14] = "is";
			arr[15] = "Christmas";
			list.push(new Question("Он похож на Деда Мороза.", "He looks like Father Christmas", arr, "sound_3_17"));
			
			arr = new Array(15);
			arr[0] = "her";
			arr[1] = "my";
			arr[2] = "many";
			arr[3] = "very";
			arr[4] = "he";
			arr[5] = "to";
			arr[6] = "that";
			arr[7] = "interesting";
			arr[8] = "your";
			arr[9] = "like";
			arr[10] = "was";
			arr[11] = "this";
			arr[12] = "looks";
			arr[13] = "a";
			arr[14] = "is";
			arr[15] = "book";
			list.push(new Question("Эта книга как и та очень интересная.", "This book like that is very interesting", arr, "sound_3_18"));
			
			arr = new Array(15);
			arr[0] = "her";
			arr[1] = "my";
			arr[2] = "many";
			arr[3] = "same";
			arr[4] = "he";
			arr[5] = "to";
			arr[6] = "this";
			arr[7] = "magazine";
			arr[8] = "your";
			arr[9] = "like";
			arr[10] = "was";
			arr[11] = "the";
			arr[12] = "looks";
			arr[13] = "a";
			arr[14] = "is";
			arr[15] = "yours";
			list.push(new Question("Этот журнал тaкой же как и твой.", "This magazine is the same like yours", arr, "sound_3_19"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "my";
			arr[2] = "can";
			arr[3] = "very";
			arr[4] = "he";
			arr[5] = "to";
			arr[6] = "it";
			arr[7] = "you";
			arr[8] = "your";
			arr[9] = "like";
			arr[10] = "was";
			arr[11] = "this";
			arr[12] = "looks";
			arr[13] = "do";
			arr[14] = "is";
			arr[15] = "book";
			list.push(new Question("Я могу это сделать также как и ты.", "I can do it like you", arr, "sound_3_20"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "my";
			arr[2] = "he";
			arr[3] = "very";
			arr[4] = "he";
			arr[5] = "to";
			arr[6] = "it";
			arr[7] = "you";
			arr[8] = "works";
			arr[9] = "like";
			arr[10] = "was";
			arr[11] = "this";
			arr[12] = "looks";
			arr[13] = "a";
			arr[14] = "is";
			arr[15] = "manager";
			list.push(new Question("Он работает в качестве мененджера.", "He works like a manager", arr, "sound_3_21"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "my";
			arr[2] = "he";
			arr[3] = "want";
			arr[4] = "not";
			arr[5] = "to";
			arr[6] = "it";
			arr[7] = "you";
			arr[8] = "works";
			arr[9] = "like";
			arr[10] = "was";
			arr[11] = "now";
			arr[12] = "looks";
			arr[13] = "do";
			arr[14] = "is";
			arr[15] = "sleep";
			list.push(new Question("Как и ты я не хочу сейчас спать.", "Like you I do not want to sleep now", arr, "sound_3_22"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "my";
			arr[2] = "he";
			arr[3] = "have";
			arr[4] = "him";
			arr[5] = "to";
			arr[6] = "it";
			arr[7] = "you";
			arr[8] = "this";
			arr[9] = "like";
			arr[10] = "was";
			arr[11] = "now";
			arr[12] = "looks";
			arr[13] = "book";
			arr[14] = "is";
			arr[15] = "read";
			list.push(new Question("Ты прочел эту книгу как и он?", "Have you read this book like him", arr, "sound_3_23"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "my";
			arr[2] = "he";
			arr[3] = "has";
			arr[4] = "him";
			arr[5] = "to";
			arr[6] = "it";
			arr[7] = "you";
			arr[8] = "emotions";
			arr[9] = "like";
			arr[10] = "was";
			arr[11] = "now";
			arr[12] = "looks";
			arr[13] = "everybody";
			arr[14] = "is";
			arr[15] = "read";
			list.push(new Question("Как и у всех у него есть эмоции.", "Like everybody he has emotions", arr, "sound_3_24"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "will";
			arr[2] = "he";
			arr[3] = "has";
			arr[4] = "him";
			arr[5] = "to";
			arr[6] = "don't";
			arr[7] = "you";
			arr[8] = "mind";
			arr[9] = "like";
			arr[10] = "was";
			arr[11] = "now";
			arr[12] = "looks";
			arr[13] = "drink";
			arr[14] = "is";
			arr[15] = "coffee";
			list.push(new Question("Вы не против, если я выпью кофе как и он?", "Don't you mind I will drink coffee like him", arr, "sound_3_25"));
			
			arr = new Array(15);
			arr[0] = "wear";
			arr[1] = "my";
			arr[2] = "he";
			arr[3] = "has";
			arr[4] = "him";
			arr[5] = "to";
			arr[6] = "do";
			arr[7] = "you";
			arr[8] = "her";
			arr[9] = "like";
			arr[10] = "was";
			arr[11] = "now";
			arr[12] = "looks";
			arr[13] = "trousers";
			arr[14] = "or";
			arr[15] = "skirts";
			list.push(new Question("Ты носишь брюки или юбки как она?", "Do you wear trousers or skirts like her", arr, "sound_3_26"));
			
			arr = new Array(15);
			arr[0] = "yellow";
			arr[1] = "my";
			arr[2] = "he";
			arr[3] = "this";
			arr[4] = "him";
			arr[5] = "to";
			arr[6] = "do";
			arr[7] = "you";
			arr[8] = "her";
			arr[9] = "like";
			arr[10] = "was";
			arr[11] = "Sun";
			arr[12] = "looks";
			arr[13] = "colour";
			arr[14] = "is";
			arr[15] = "a";
			list.push(new Question("Этот желтый цвет как солнце.", "This yellow colour is like a Sun", arr, "sound_3_27"));
			
			arr = new Array(15);
			arr[0] = "shoes";
			arr[1] = "my";
			arr[2] = "he";
			arr[3] = "yours";
			arr[4] = "are";
			arr[5] = "to";
			arr[6] = "do";
			arr[7] = "you";
			arr[8] = "her";
			arr[9] = "like";
			arr[10] = "was";
			arr[11] = "Sun";
			arr[12] = "looks";
			arr[13] = "colour";
			arr[14] = "do";
			arr[15] = "see";
			list.push(new Question("Мои туфли как твои, ты видишь?", "My shoes are like yours do you see", arr, "sound_3_28"));
		}
		
		// is
		private function Add_6():void
		{
			var arr:Array = new Array(15);
			arr[0] = "I";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "to";
			arr[5] = "your";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "what";
			arr[9] = "are";
			arr[10] = "name";
			arr[11] = "is";
			arr[12] = "you";
			arr[13] = "not";
			arr[14] = "speak";
			arr[15] = "when";
			list.push(new Question("Как тебя зовут?", "What is your name", arr, "sound_3_29"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "to";
			arr[5] = "your";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "what";
			arr[9] = "are";
			arr[10] = "name";
			arr[11] = "is";
			arr[12] = "you";
			arr[13] = "his";
			arr[14] = "Ivan";
			arr[15] = "when";
			list.push(new Question("Его зовут Иван.", "His name is Ivan", arr, "sound_3_30"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "to";
			arr[5] = "your";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "what";
			arr[9] = "are";
			arr[10] = "name";
			arr[11] = "is";
			arr[12] = "you";
			arr[13] = "his";
			arr[14] = "Olga";
			arr[15] = "her";
			list.push(new Question("Ее зовут Ольга.", "Her name is Olga", arr, "sound_3_31"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "my";
			arr[5] = "your";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "what";
			arr[9] = "are";
			arr[10] = "name";
			arr[11] = "is";
			arr[12] = "you";
			arr[13] = "his";
			arr[14] = "Vladimir";
			arr[15] = "her";
			list.push(new Question("Меня зовут Владимир.", "My name is Vladimir", arr, "sound_3_32"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "my";
			arr[5] = "your";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "our";
			arr[9] = "are";
			arr[10] = "name";
			arr[11] = "is";
			arr[12] = "you";
			arr[13] = "his";
			arr[14] = "friend";
			arr[15] = "her";
			list.push(new Question("Он наш друг.", "He is our friend", arr, "sound_3_33"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "my";
			arr[5] = "your";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "our";
			arr[9] = "are";
			arr[10] = "name";
			arr[11] = "is";
			arr[12] = "you";
			arr[13] = "his";
			arr[14] = "friend";
			arr[15] = "her";
			list.push(new Question("Он ее друг.", "He is her friend", arr, "sound_3_34"));
			
			arr = new Array(15);
			arr[0] = "it";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "their";
			arr[5] = "your";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "our";
			arr[9] = "are";
			arr[10] = "name";
			arr[11] = "is";
			arr[12] = "you";
			arr[13] = "his";
			arr[14] = "problem";
			arr[15] = "her";
			list.push(new Question("Это их проблема.", "It is their problem", arr, "sound_3_35"));
		}
		
		// to
		private function Add_5():void
		{
			var arr:Array = new Array(15);
			arr[0] = "I";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "to";
			arr[5] = "be";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "do";
			arr[9] = "are";
			arr[10] = "want";
			arr[11] = "is";
			arr[12] = "you";
			arr[13] = "not";
			arr[14] = "speak";
			arr[15] = "when";
			list.push(new Question("Я хочу говорить.", "I want to speak", arr, "sound_3_36"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "to";
			arr[5] = "be";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "do";
			arr[9] = "are";
			arr[10] = "want";
			arr[11] = "is";
			arr[12] = "you";
			arr[13] = "not";
			arr[14] = "speak";
			arr[15] = "when";
			list.push(new Question("Я не хочу говорить.", "I do not want to speak", arr, "sound_3_37"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "to";
			arr[5] = "be";
			arr[6] = "dance";
			arr[7] = "she";
			arr[8] = "do";
			arr[9] = "with";
			arr[10] = "want";
			arr[11] = "is";
			arr[12] = "you";
			arr[13] = "not";
			arr[14] = "like";
			arr[15] = "when";
			list.push(new Question("Мне нравится танцевать с тобой.", "I like to dance with you", arr, "sound_3_38"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "to";
			arr[5] = "be";
			arr[6] = "come";
			arr[7] = "she";
			arr[8] = "do";
			arr[9] = "with";
			arr[10] = "want";
			arr[11] = "is";
			arr[12] = "you";
			arr[13] = "to";
			arr[14] = "came";
			arr[15] = "when";
			list.push(new Question("Я хочу прийти к тебе.", "I want to come to you", arr, "sound_3_39"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "to";
			arr[5] = "be";
			arr[6] = "dance";
			arr[7] = "she";
			arr[8] = "don't";
			arr[9] = "with";
			arr[10] = "want";
			arr[11] = "is";
			arr[12] = "you";
			arr[13] = "her";
			arr[14] = "want";
			arr[15] = "when";
			list.push(new Question("Я не хочу танцевать с ней.", "I don't want to dance with her", arr, "sound_3_40"));
			
			arr = new Array(15);
			arr[0] = "do";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "to";
			arr[5] = "be";
			arr[6] = "dance";
			arr[7] = "she";
			arr[8] = "don't";
			arr[9] = "with";
			arr[10] = "want";
			arr[11] = "is";
			arr[12] = "you";
			arr[13] = "her";
			arr[14] = "want";
			arr[15] = "when";
			list.push(new Question("Ты хочешь танцевать?", "Do you want to dance", arr, "sound_3_41"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "to";
			arr[5] = "be";
			arr[6] = "dance";
			arr[7] = "she";
			arr[8] = "don't";
			arr[9] = "with";
			arr[10] = "want";
			arr[11] = "is";
			arr[12] = "you";
			arr[13] = "her";
			arr[14] = "want";
			arr[15] = "when";
			list.push(new Question("Когда ты захочешь танцевать?", "When will you want to dance", arr, "sound_3_42"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "to";
			arr[5] = "be";
			arr[6] = "dance";
			arr[7] = "she";
			arr[8] = "don't";
			arr[9] = "with";
			arr[10] = "want";
			arr[11] = "we";
			arr[12] = "you";
			arr[13] = "her";
			arr[14] = "want";
			arr[15] = "when";
			list.push(new Question("Мы будем танцевать.", "We will dance", arr, "sound_3_43"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "to";
			arr[5] = "be";
			arr[6] = "dance";
			arr[7] = "she";
			arr[8] = "don't";
			arr[9] = "with";
			arr[10] = "want";
			arr[11] = "we";
			arr[12] = "you";
			arr[13] = "her";
			arr[14] = "want";
			arr[15] = "when";
			list.push(new Question("Я хочу танцевать.", "I want to dance", arr, "sound_3_44"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "to";
			arr[5] = "be";
			arr[6] = "speak";
			arr[7] = "she";
			arr[8] = "don't";
			arr[9] = "doesn't";
			arr[10] = "want";
			arr[11] = "we";
			arr[12] = "you";
			arr[13] = "her";
			arr[14] = "didn't";
			arr[15] = "when";
			list.push(new Question("Она не хочет говорить.", "She doesn't want to speak", arr, "sound_3_45"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "to";
			arr[5] = "be";
			arr[6] = "work";
			arr[7] = "she";
			arr[8] = "don't";
			arr[9] = "doesn't";
			arr[10] = "worked";
			arr[11] = "we";
			arr[12] = "you";
			arr[13] = "her";
			arr[14] = "want";
			arr[15] = "when";
			list.push(new Question("Я хочу работать.", "I want to work", arr, "sound_3_46"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "to";
			arr[5] = "be";
			arr[6] = "work";
			arr[7] = "she";
			arr[8] = "don't";
			arr[9] = "doesn't";
			arr[10] = "worked";
			arr[11] = "he";
			arr[12] = "you";
			arr[13] = "her";
			arr[14] = "want";
			arr[15] = "when";
			list.push(new Question("Он не хочет работать.", "He doesn't want to work", arr, "sound_3_47"));
			
			arr = new Array(15);
			arr[0] = "they";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "to";
			arr[5] = "be";
			arr[6] = "draw";
			arr[7] = "she";
			arr[8] = "don't";
			arr[9] = "doesn't";
			arr[10] = "draws";
			arr[11] = "he";
			arr[12] = "you";
			arr[13] = "her";
			arr[14] = "want";
			arr[15] = "when";
			list.push(new Question("Они хотят рисовать.", "They want to draw", arr, "sound_3_48"));
			
			arr = new Array(15);
			arr[0] = "do";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "to";
			arr[5] = "be";
			arr[6] = "draw";
			arr[7] = "she";
			arr[8] = "don't";
			arr[9] = "doesn't";
			arr[10] = "build";
			arr[11] = "he";
			arr[12] = "you";
			arr[13] = "her";
			arr[14] = "want";
			arr[15] = "when";
			list.push(new Question("Ты хочешь построить?", "Do you want to build", arr, "sound_3_49"));
			
			arr = new Array(15);
			arr[0] = "do";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "to";
			arr[5] = "be";
			arr[6] = "draw";
			arr[7] = "she";
			arr[8] = "don't";
			arr[9] = "doesn't";
			arr[10] = "build";
			arr[11] = "he";
			arr[12] = "you";
			arr[13] = "why";
			arr[14] = "want";
			arr[15] = "when";
			list.push(new Question("Почему вы не хотите построить?", "Why don't you want to build", arr, "sound_3_50"));
			
			arr = new Array(15);
			arr[0] = "do";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "to";
			arr[5] = "be";
			arr[6] = "didn't";
			arr[7] = "she";
			arr[8] = "don't";
			arr[9] = "doesn't";
			arr[10] = "build";
			arr[11] = "he";
			arr[12] = "you";
			arr[13] = "why";
			arr[14] = "want";
			arr[15] = "when";
			list.push(new Question("Он не хотел строить.", "He didn't want to build", arr, "sound_3_51"));
			
			arr = new Array(15);
			arr[0] = "they";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "to";
			arr[5] = "be";
			arr[6] = "didn't";
			arr[7] = "she";
			arr[8] = "don't";
			arr[9] = "doesn't";
			arr[10] = "draw";
			arr[11] = "he";
			arr[12] = "you";
			arr[13] = "why";
			arr[14] = "want";
			arr[15] = "when";
			list.push(new Question("Они захотят рисовать.", "They will want to draw", arr, "sound_3_52"));
			
			arr = new Array(15);
			arr[0] = "they";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "to";
			arr[5] = "be";
			arr[6] = "didn't";
			arr[7] = "she";
			arr[8] = "wants";
			arr[9] = "doesn't";
			arr[10] = "draw";
			arr[11] = "who";
			arr[12] = "you";
			arr[13] = "why";
			arr[14] = "want";
			arr[15] = "when";
			list.push(new Question("Кто хочет рисовать?", "Who wants to draw", arr, "sound_3_53"));
		}
		
		// there
		private function Add_4():void
		{
			var arr:Array = new Array(15);
			arr[0] = "I";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "there";
			arr[5] = "be";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "do";
			arr[9] = "are";
			arr[10] = "were";
			arr[11] = "is";
			arr[12] = "you";
			arr[13] = "not";
			arr[14] = "was";
			arr[15] = "when";
			list.push(new Question("Когда ты будешь там?", "When will you be there", arr, "sound_3_54"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "there";
			arr[5] = "be";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "do";
			arr[9] = "are";
			arr[10] = "were";
			arr[11] = "is";
			arr[12] = "you";
			arr[13] = "we";
			arr[14] = "was";
			arr[15] = "when";
			list.push(new Question("Мы будем там.", "We will be there", arr, "sound_3_55"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "there";
			arr[5] = "be";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "do";
			arr[9] = "are";
			arr[10] = "were";
			arr[11] = "is";
			arr[12] = "you";
			arr[13] = "not";
			arr[14] = "was";
			arr[15] = "when";
			list.push(new Question("Меня там не будет.", "I will not be there", arr, "sound_3_56"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "there";
			arr[5] = "be";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "do";
			arr[9] = "are";
			arr[10] = "were";
			arr[11] = "is";
			arr[12] = "they";
			arr[13] = "not";
			arr[14] = "was";
			arr[15] = "when";
			list.push(new Question("Они там?", "Are they there", arr, "sound_3_57"));
			
			arr = new Array(15);
			arr[0] = "It";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "there";
			arr[5] = "be";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "do";
			arr[9] = "are";
			arr[10] = "were";
			arr[11] = "is";
			arr[12] = "you";
			arr[13] = "not";
			arr[14] = "was";
			arr[15] = "when";
			list.push(new Question("Это там.", "It is there", arr, "sound_3_58"));
			
			arr = new Array(15);
			arr[0] = "It";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "there";
			arr[5] = "be";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "do";
			arr[9] = "are";
			arr[10] = "were";
			arr[11] = "is";
			arr[12] = "you";
			arr[13] = "not";
			arr[14] = "was";
			arr[15] = "when";
			list.push(new Question("Его там нет.", "He is not there", arr, "sound_3_59"));
			
			arr = new Array(15);
			arr[0] = "It";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "there";
			arr[5] = "be";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "do";
			arr[9] = "why";
			arr[10] = "were";
			arr[11] = "is";
			arr[12] = "you";
			arr[13] = "not";
			arr[14] = "was";
			arr[15] = "when";
			list.push(new Question("Зачем ты был там?", "Why were you there", arr, "sound_3_60"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "there";
			arr[5] = "be";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "do";
			arr[9] = "why";
			arr[10] = "were";
			arr[11] = "is";
			arr[12] = "you";
			arr[13] = "not";
			arr[14] = "was";
			arr[15] = "when";
			list.push(new Question("Я был там.", "I was there", arr, "sound_3_61"));
			
			arr = new Array(15);
			arr[0] = "they";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "there";
			arr[5] = "be";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "do";
			arr[9] = "why";
			arr[10] = "were";
			arr[11] = "is";
			arr[12] = "you";
			arr[13] = "not";
			arr[14] = "was";
			arr[15] = "when";
			list.push(new Question("Их там не было.", "They were not there", arr, "sound_3_62"));
		}
		
		// London
		private function Add_3():void
		{
			var arr:Array = new Array(15);
			arr[0] = "I";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "London";
			arr[5] = "be";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "do";
			arr[9] = "are";
			arr[10] = "were";
			arr[11] = "is";
			arr[12] = "you";
			arr[13] = "not";
			arr[14] = "was";
			arr[15] = "when";
			list.push(new Question("Когда ты будешь в Лондоне?", "When will you be in London", arr, "sound_3_63"));
			
			arr = new Array(15);
			arr[0] = "we";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "London";
			arr[5] = "be";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "do";
			arr[9] = "are";
			arr[10] = "were";
			arr[11] = "is";
			arr[12] = "you";
			arr[13] = "not";
			arr[14] = "was";
			arr[15] = "when";
			list.push(new Question("Мы будем в Лондоне.", "We will be in London", arr, "sound_3_64"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "London";
			arr[5] = "be";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "do";
			arr[9] = "are";
			arr[10] = "were";
			arr[11] = "is";
			arr[12] = "you";
			arr[13] = "not";
			arr[14] = "was";
			arr[15] = "when";
			list.push(new Question("Она не будет в Лондоне.", "She will not be in London", arr, "sound_3_65"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "London";
			arr[5] = "be";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "do";
			arr[9] = "are";
			arr[10] = "were";
			arr[11] = "is";
			arr[12] = "you";
			arr[13] = "not";
			arr[14] = "was";
			arr[15] = "when";
			list.push(new Question("Он в Лондоне?", "Is he in London", arr, "sound_3_66"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "London";
			arr[5] = "be";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "do";
			arr[9] = "are";
			arr[10] = "were";
			arr[11] = "is";
			arr[12] = "you";
			arr[13] = "not";
			arr[14] = "was";
			arr[15] = "when";
			list.push(new Question("Я в Лондоне.", "I am in London", arr, "sound_3_67"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "London";
			arr[5] = "be";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "do";
			arr[9] = "are";
			arr[10] = "were";
			arr[11] = "is";
			arr[12] = "you";
			arr[13] = "not";
			arr[14] = "was";
			arr[15] = "when";
			list.push(new Question("Тебя нет в Лондоне.", "You are not in London", arr, "sound_3_68"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "London";
			arr[5] = "be";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "do";
			arr[9] = "are";
			arr[10] = "were";
			arr[11] = "is";
			arr[12] = "you";
			arr[13] = "not";
			arr[14] = "was";
			arr[15] = "when";
			list.push(new Question("Когда я был в Лондоне?", "When was I in London", arr, "sound_3_69"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "London";
			arr[5] = "be";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "do";
			arr[9] = "are";
			arr[10] = "were";
			arr[11] = "is";
			arr[12] = "you";
			arr[13] = "not";
			arr[14] = "was";
			arr[15] = "when";
			list.push(new Question("Она была в Лондоне.", "She was in London", arr, "sound_3_70"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "in";
			arr[4] = "London";
			arr[5] = "be";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "do";
			arr[9] = "are";
			arr[10] = "were";
			arr[11] = "is";
			arr[12] = "you";
			arr[13] = "not";
			arr[14] = "was";
			arr[15] = "when";
			list.push(new Question("Я не был в Лондоне.", "I was not in London", arr, "sound_3_71"));
		}
		
		// friend
		private function Add_2():void
		{
			var arr:Array = new Array(15);
			arr[0] = "I";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "did";
			arr[4] = "friend";
			arr[5] = "be";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "do";
			arr[9] = "are";
			arr[10] = "were";
			arr[11] = "does";
			arr[12] = "you";
			arr[13] = "not";
			arr[14] = "my";
			arr[15] = "there";
			list.push(new Question("Ты будешь моим другом?", "Will you be my friend", arr, "sound_3_72"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "did";
			arr[4] = "friend";
			arr[5] = "be";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "do";
			arr[9] = "are";
			arr[10] = "here";
			arr[11] = "does";
			arr[12] = "you";
			arr[13] = "not";
			arr[14] = "my";
			arr[15] = "your";
			list.push(new Question("Он будет твоим другом.", "He will be your friend", arr, "sound_3_73"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "did";
			arr[4] = "friend";
			arr[5] = "be";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "do";
			arr[9] = "to";
			arr[10] = "here";
			arr[11] = "want";
			arr[12] = "you";
			arr[13] = "not";
			arr[14] = "my";
			arr[15] = "your";
			list.push(new Question("Я хочу быть твоим другом.", "I want to be your friend", arr, "sound_3_74"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "did";
			arr[4] = "friend";
			arr[5] = "be";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "do";
			arr[9] = "are";
			arr[10] = "here";
			arr[11] = "to";
			arr[12] = "are";
			arr[13] = "not";
			arr[14] = "my";
			arr[15] = "your";
			list.push(new Question("Я не буду твоим другом.", "I will not be your friend", arr, "sound_3_75"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "is";
			arr[4] = "friend";
			arr[5] = "be";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "do";
			arr[9] = "are";
			arr[10] = "was";
			arr[11] = "does";
			arr[12] = "you";
			arr[13] = "not";
			arr[14] = "my";
			arr[15] = "your";
			list.push(new Question("Он твой друг?", "Is he your friend", arr, "sound_3_76"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "is";
			arr[4] = "friend";
			arr[5] = "be";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "do";
			arr[9] = "are";
			arr[10] = "was";
			arr[11] = "does";
			arr[12] = "you";
			arr[13] = "not";
			arr[14] = "my";
			arr[15] = "your";
			list.push(new Question("Ты мой друг.", "You are my friend", arr, "sound_3_77"));
			
			arr = new Array(15);
			arr[0] = "they";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "is";
			arr[4] = "friend";
			arr[5] = "be";
			arr[6] = "he";
			arr[7] = "friends";
			arr[8] = "do";
			arr[9] = "are";
			arr[10] = "was";
			arr[11] = "does";
			arr[12] = "you";
			arr[13] = "not";
			arr[14] = "my";
			arr[15] = "your";
			list.push(new Question("Они не мои друзья.", "They are not my friends", arr, "sound_3_78"));
			
			arr = new Array(15);
			arr[0] = "they";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "is";
			arr[4] = "friend";
			arr[5] = "be";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "do";
			arr[9] = "are";
			arr[10] = "was";
			arr[11] = "does";
			arr[12] = "you";
			arr[13] = "not";
			arr[14] = "my";
			arr[15] = "your";
			list.push(new Question("Он был моим другом?", "Was he my friend", arr, "sound_3_79"));
			
			arr = new Array(15);
			arr[0] = "they";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "is";
			arr[4] = "friend";
			arr[5] = "be";
			arr[6] = "he";
			arr[7] = "I";
			arr[8] = "do";
			arr[9] = "are";
			arr[10] = "was";
			arr[11] = "does";
			arr[12] = "you";
			arr[13] = "their";
			arr[14] = "my";
			arr[15] = "your";
			list.push(new Question("Я был их другом.", "I was their friend", arr, "sound_3_80"));
			
			arr = new Array(15);
			arr[0] = "friends";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "his";
			arr[4] = "friend";
			arr[5] = "be";
			arr[6] = "he";
			arr[7] = "were";
			arr[8] = "do";
			arr[9] = "are";
			arr[10] = "was";
			arr[11] = "does";
			arr[12] = "you";
			arr[13] = "their";
			arr[14] = "not";
			arr[15] = "your";
			list.push(new Question("Мы не были его друзьями.", "We were not his friends", arr, "sound_3_81"));
		}
		
		// here
		private function Add_1():void 
		{
			var arr:Array = new Array(15);
			arr[0] = "I";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "did";
			arr[4] = "take";
			arr[5] = "be";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "do";
			arr[9] = "are";
			arr[10] = "here";
			arr[11] = "does";
			arr[12] = "you";
			arr[13] = "not";
			arr[14] = "why";
			arr[15] = "there";
			list.push(new Question("Ты будешь здесь?", "Will you be here", arr, "sound_3_82"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "did";
			arr[4] = "take";
			arr[5] = "be";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "were";
			arr[9] = "are";
			arr[10] = "here";
			arr[11] = "does";
			arr[12] = "you";
			arr[13] = "not";
			arr[14] = "was";
			arr[15] = "there";
			list.push(new Question("Она будет здесь.", "She will be here", arr, "sound_3_83"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "did";
			arr[4] = "take";
			arr[5] = "be";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "were";
			arr[9] = "are";
			arr[10] = "here";
			arr[11] = "does";
			arr[12] = "you";
			arr[13] = "not";
			arr[14] = "was";
			arr[15] = "there";
			list.push(new Question("Он не будет здесь.", "He will not be here", arr, "sound_3_84"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "did";
			arr[4] = "take";
			arr[5] = "be";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "were";
			arr[9] = "are";
			arr[10] = "here";
			arr[11] = "does";
			arr[12] = "you";
			arr[13] = "not";
			arr[14] = "was";
			arr[15] = "there";
			list.push(new Question("Меня не будет здесь.", "I will not be here", arr, "sound_3_85"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "am";
			arr[2] = "will";
			arr[3] = "did";
			arr[4] = "take";
			arr[5] = "be";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "were";
			arr[9] = "are";
			arr[10] = "here";
			arr[11] = "does";
			arr[12] = "you";
			arr[13] = "not";
			arr[14] = "was";
			arr[15] = "there";
			list.push(new Question("Ты здесь?", "Are you here", arr, "sound_3_86"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "did";
			arr[4] = "take";
			arr[5] = "be";
			arr[6] = "he";
			arr[7] = "she";
			arr[8] = "were";
			arr[9] = "are";
			arr[10] = "here";
			arr[11] = "does";
			arr[12] = "you";
			arr[13] = "not";
			arr[14] = "was";
			arr[15] = "there";
			list.push(new Question("Мы здесь.", "We are here", arr, "sound_3_87"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "did";
			arr[4] = "take";
			arr[5] = "be";
			arr[6] = "am";
			arr[7] = "she";
			arr[8] = "were";
			arr[9] = "are";
			arr[10] = "here";
			arr[11] = "does";
			arr[12] = "you";
			arr[13] = "not";
			arr[14] = "was";
			arr[15] = "there";
			list.push(new Question("Я не здесь.", "I am not here", arr, "sound_3_88"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "did";
			arr[4] = "take";
			arr[5] = "be";
			arr[6] = "am";
			arr[7] = "she";
			arr[8] = "were";
			arr[9] = "are";
			arr[10] = "here";
			arr[11] = "does";
			arr[12] = "you";
			arr[13] = "not";
			arr[14] = "was";
			arr[15] = "they";
			list.push(new Question("Они были здесь?", "Were they here", arr, "sound_3_89"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "did";
			arr[4] = "take";
			arr[5] = "be";
			arr[6] = "am";
			arr[7] = "she";
			arr[8] = "were";
			arr[9] = "are";
			arr[10] = "here";
			arr[11] = "does";
			arr[12] = "you";
			arr[13] = "not";
			arr[14] = "was";
			arr[15] = "they";
			list.push(new Question("Я был здесь.", "I was here", arr, "sound_3_90"));
			
			arr = new Array(15);
			arr[0] = "I";
			arr[1] = "we";
			arr[2] = "will";
			arr[3] = "did";
			arr[4] = "take";
			arr[5] = "be";
			arr[6] = "am";
			arr[7] = "she";
			arr[8] = "were";
			arr[9] = "are";
			arr[10] = "here";
			arr[11] = "does";
			arr[12] = "you";
			arr[13] = "not";
			arr[14] = "was";
			arr[15] = "they";
			list.push(new Question("Мы не были здесь.", "We were not here", arr, "sound_3_91"));
			
			
		}
		
	}

}